import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile,readdir,copyFile} from 'node:fs/promises';
import path from 'node:path';
import ts from 'typescript';
const root=path.resolve('.');const out=path.join(root,'.sites-runtime/ui-test-modules');
async function compile(dir){for(const entry of await readdir(path.join(root,dir),{withFileTypes:true})){const rel=path.join(dir,entry.name);if(entry.isDirectory()){await compile(rel);continue;}if(!/\.(tsx?|json)$/.test(rel))continue;const target=path.join(out,rel.replace(/\.tsx?$/,'.js'));await mkdir(path.dirname(target),{recursive:true});if(rel.endsWith('.json')){await copyFile(path.join(root,rel),target);continue;}let code=ts.transpileModule(await readFile(path.join(root,rel),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;code=code.replace(/from (['"])([^'"]+)\1/g,(match,quote,spec)=>{if(!spec.startsWith('.')&&!spec.startsWith('@/'))return match;const original=spec.startsWith('@/')?path.join(root,spec.slice(2)):path.resolve(root,path.dirname(rel),spec);let dest=path.relative(path.join(root,path.dirname(rel)),original).replaceAll(path.sep,'/');if(!dest.startsWith('.'))dest='./'+dest;return `from '${dest.endsWith('.json')?dest:dest+'.js'}'${dest.endsWith('.json')?" with {type:'json'}":''}`;});await writeFile(target,code)}}
await compile('app');await compile('lib');await compile('components');
const {translate,matchesSearch,dictionary}=await import(path.join(out,'lib/i18n/translate.js'));
const {newRun}=await import(path.join(out,'lib/game/state.js'));const {makePlan,deadlines}=await import(path.join(out,'lib/game/planner.js'));const {crops,bundles,fish,events,purchaseOptions,SEASONS,GOALS}=await import(path.join(out,'lib/game/data.js'));
let passed=0;const test=(name,fn)=>{fn();passed++;console.log('PASS',name)};
test('Every catalog item, bundle, villager and purchase has Chinese text',()=>{for(const entry of [...crops,...bundles,...fish,...events,...purchaseOptions]){assert(!/[A-Za-z]/.test(translate(entry.name,'zh-CN')),entry.name);for(const item of entry.items??[])assert(!/[A-Za-z]/.test(translate(item.name,'zh-CN')),item.name)}});
test('All planner messages translate across seasons, weather and goals',()=>{for(const season of SEASONS)for(let day=1;day<=28;day++)for(const goal of GOALS)for(const weather of ['Rain','Sunny','Unknown']){const run={...newRun(),date:{year:2,season,day},weather,goal,level:5,gold:10000,unlocks:['Bus','Island'],tomorrow:'Rain'};for(const task of makePlan(run))for(const key of ['name','detail','why','skip','category','confidence'])assert(!/[A-Za-z]/.test(translate(task[key],'zh-CN')),task[key]);for(const item of deadlines(run)){assert(!/[A-Za-z]/.test(translate(item.name,'zh-CN')),item.name);assert(!/[A-Za-z]/.test(translate(item.detail,'zh-CN')),item.detail)}}});
test('English labels remain exact; Chinese and English search both work',()=>{for(const s of Object.keys(dictionary))assert.equal(translate(s,'en'),s);assert(matchesSearch('Parsnip','防风'));assert(matchesSearch('Parsnip','PARS'));assert(matchesSearch('Spring Crops','春季作物'));assert(!matchesSearch('Parsnip','南瓜'))});
test('Dates, quantities and template grammar translate correctly',()=>{assert.equal(translate('Spring 13, Year 2','zh-CN'),'第2年春季13日');assert.equal(translate('Keep one for Spring Crops. Use owned seeds or another open seller. Water it every day.','zh-CN'),'为春季作物收集包留一个，每天记得浇水。请用已有种子，或去其他营业中的商店购买。');assert.equal(translate('Parsnip, 5 required gold quality, not donated','zh-CN'),'防风草，需要5个金星品质，尚未献祭');assert.equal(translate('Private task text 你好','zh-CN'),'Private task text 你好')});
const {JSDOM}=await import('jsdom');const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:'http://localhost'});
for(const key of ['window','document','HTMLElement','HTMLInputElement','HTMLFormElement','HTMLSelectElement','HTMLOptionElement','HTMLButtonElement','NodeFilter','Element','Node','DocumentFragment','MutationObserver','CustomEvent','Event','MouseEvent','KeyboardEvent','DOMParser'])globalThis[key]=dom.window[key];
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});globalThis.localStorage=dom.window.localStorage;globalThis.getComputedStyle=dom.window.getComputedStyle.bind(dom.window);globalThis.requestAnimationFrame=cb=>setTimeout(cb,0);globalThis.cancelAnimationFrame=clearTimeout;
let reduce=false;dom.window.matchMedia=()=>({matches:reduce,addEventListener(){},removeEventListener(){}});globalThis.ResizeObserver=class{observe(){}unobserve(){}disconnect(){}};HTMLElement.prototype.scrollIntoView=function(){};HTMLElement.prototype.hasPointerCapture=()=>false;HTMLElement.prototype.setPointerCapture=function(){};HTMLElement.prototype.releasePointerCapture=function(){};
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const React=await import('react');const {createRoot}=await import('react-dom/client');const {act}=React;
const {LocaleProvider,LanguageSwitch,renderLocalized}=await import(path.join(out,'app/locale-provider.js'));const {default:PixelEffects}=await import(path.join(out,'app/pixel-effects.js'));const {default:FarmJournal}=await import(path.join(out,'app/farm-journal.js'));
const run=newRun();const baseline=JSON.stringify(run);const requests=[];
globalThis.fetch=async(url,opts)=>{requests.push([url,opts]);if(opts?.method==='PUT'){const data=JSON.parse(opts.body);assert.deepEqual({...data.state,done:run.done},run);assert(data.state.done.length===1);return new Response(JSON.stringify({revision:1}),{status:200})}return new Response(JSON.stringify({state:run,revision:0}),{status:200})};
localStorage.setItem('farm-journal-language','zh-CN');const rootUI=createRoot(document.getElementById('root'));
await act(async()=>{rootUI.render(React.createElement(LocaleProvider,null,React.createElement(FarmJournal),React.createElement(PixelEffects)));await new Promise(r=>setTimeout(r,30))});
const text=()=>document.body.textContent;const button=label=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===label);
assert(text().includes('今日计划'));assert(text().includes('星露谷农场手记'));assert.equal(document.documentElement.lang,'zh-CN');console.log('PASS remembered language renders the Chinese journal');passed++;
await act(async()=>button('English').click());assert(text().includes('Today’s plan'));assert.equal(localStorage.getItem('farm-journal-language'),'en');assert.equal(document.querySelectorAll('.pixel-burst').length,1);assert.equal(JSON.stringify(run),baseline);console.log('PASS language switch preserves farm data and produces a click sparkle');passed++;
await act(async()=>button('简体中文').click());assert.equal(document.documentElement.lang,'zh-CN');await act(async()=>document.querySelector('.farm-check').click());await act(async()=>button('保存农场').click());assert(requests.some(([,options])=>options?.method==='PUT'));console.log('PASS saving from Chinese UI submits the original canonical farm state');passed++;
// Exercise all tab panels through the controlled primitive's mouse-down event.
async function tab(label){const el=[...document.querySelectorAll('[role="tab"]')].find(x=>x.textContent.trim()===label);assert(el,'Missing tab '+label);await act(async()=>{el.dispatchEvent(new MouseEvent('mousedown',{bubbles:true,button:0}));el.click()})}
await tab('收藏');assert(text().includes('我的收藏'));assert(text().includes('防风草'));assert(text().includes('春季作物收集包'));
await tab('物品栏');assert(text().includes('添加物资'));await tab('钓鱼');assert(text().includes('钓鱼手册'));await tab('计划');assert(text().includes('提前计划'));await tab('农作物');assert(text().includes('作物账本'));await tab('比较');assert(text().includes('两种选择'));await tab('更多');assert(text().includes('慢慢打理自己的小天地'));console.log('PASS all four views and nested sections render Chinese labels');passed++;
await act(async()=>button('新建农场').click());assert(document.querySelector('[role="alertdialog"]'));assert(text().includes('开始一个新农场？'));await act(async()=>button('保留当前农场').click());
const motion=[...document.querySelectorAll('label')].find(x=>x.textContent.includes('互动特效'));assert(motion);await act(async()=>motion.querySelector('button').click());assert.equal(localStorage.getItem('farm-journal-effects'),'off');assert.equal(document.querySelectorAll('.pixel-burst').length,0);await act(async()=>button('English').click());assert.equal(document.querySelectorAll('.pixel-burst').length,0);console.log('PASS localized reset dialog and effects preference work');passed++;
await act(async()=>rootUI.unmount());localStorage.setItem('farm-journal-effects','on');reduce=true;const second=createRoot(document.getElementById('root'));await act(async()=>second.render(React.createElement(LocaleProvider,null,React.createElement(LanguageSwitch),React.createElement(PixelEffects))));await act(async()=>button('简体中文').click());assert.equal(document.querySelectorAll('.pixel-burst').length,0);await act(async()=>second.unmount());console.log('PASS reduced-motion prevents particle effects');passed++;
test('User-authored text and semantic identifiers stay unchanged',()=>{const element=React.createElement('button',{value:'Spring',id:'Spring','aria-label':'Save farm'},'Save farm');const localized=renderLocalized(element,'zh-CN');assert.equal(localized.props.value,'Spring');assert.equal(localized.props.id,'Spring');assert.equal(localized.props.children,'保存农场');assert.equal(localized.props['aria-label'],'保存农场');const personal=React.createElement('span',{translate:'no'},'Spring');assert.equal(renderLocalized(personal,'zh-CN').props.children,'Spring')});
console.log(`${passed} localization and interaction checks passed.`);
