'use client';
import {useId,useState} from 'react';
import {useLocale} from './locale-provider';
import {crops,SEASONS} from '@/lib/game/data';
import {addExistingPlot} from '@/lib/game/planner';
import type {RunState,Plot} from '@/lib/game/state';
import {InfoTip} from './item-tooltip';
import {RichText,Sprite} from './farm-ui';
export default function ExistingCropForm({run,onAdd}:{run:RunState;onAdd:(plot:Plot)=>void}){
 const {locale,t}=useLocale();const say=(en:string,cn:string)=>locale==='zh-CN'?cn:en;
 const [choice,setChoice]=useState('Parsnip'),[name,setName]=useState(''),[quantity,setQuantity]=useState(1),[remaining,setRemaining]=useState(0),[location,setLocation]=useState<NonNullable<Plot['location']>>('Farm'),[regrow,setRegrow]=useState(0),[sell,setSell]=useState(0),[yieldCount,setYieldCount]=useState(1),[seasons,setSeasons]=useState<string[]>([run.date.season]),[message,setMessage]=useState('');
 const harvestId=useId();
 const custom=choice==='custom';
 return <details className="manual-crop gap-top" translate="no"><summary>{say('＋ Add an existing crop','＋ 添加已种植作物')}</summary><p className="small muted gap-top">{say('Missing from your import? Add the crop here, including crops outside the catalog. This records an existing planting without charging for seeds.','导入时遗漏了作物？在此补录，也可添加目录外的作物。此操作只记录已种植作物，不扣除种子费用。')}</p><form onSubmit={e=>{e.preventDefault();try{const plot=addExistingPlot(run,{crop:custom?name:choice,quantity,daysUntilHarvest:remaining,location,customCrop:custom?{regrow,sell,yield:yieldCount,seasons:seasons as RunState['date']['season'][]}:undefined});onAdd(plot);setMessage(say('Crop added. Add another if needed.','作物已添加，可继续补录。'));}catch(e){setMessage(e instanceof Error&&e.name!=='ZodError'?t(e.message):say('Check quantities and select at least one growing season.','请核对数量，并至少选择一个生长季节。'));}}}>
 <div className="form-grid gap-top"><label className="field">{say('Crop','作物')}<span className="crop-native-choice">{!custom&&<Sprite name={choice} size={28}/>}<select value={choice} onChange={e=>{setChoice(e.target.value);setMessage('')}}>{crops.map(c=><option key={c.name} value={c.name}>{t(c.name)}</option>)}<option value="custom">{say('Other crop / modded crop','其他作物 / 模组作物')}</option></select></span></label>{custom&&<label className="field">{say('Crop name','作物名称')}<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>}
 <label className="field">{say('Planted tiles','已种植地块')}<input type="number" required min={1} max={9999} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label>
 <label className="field" htmlFor={harvestId}><span>{say('Days until next harvest','距离下次收获天数')} <InfoTip label="Harvest timing" text="Enter 0 if ready today. Use the remaining days, not the crop’s full growth time. Watering pauses or growth bonuses may change your estimate." chinese="今天可收获请填 0。填写剩余天数，而非完整生长周期。漏浇水或生长加速可能影响预计日期。"/></span><input id={harvestId} type="number" required min={0} max={365} value={remaining} onChange={e=>setRemaining(Number(e.target.value))}/></label>
 <label className="field">{say('Growing location','种植地点')}<select value={location} onChange={e=>setLocation(e.target.value as typeof location)}><option value="Farm">{say('Outdoor farm','室外农场')}</option><option value="Greenhouse">{say('Greenhouse / indoor','温室 / 室内')}</option><option value="IslandWest">{say('Ginger Island','姜岛')}</option></select></label></div>
 {custom&&<><p className="small muted gap-top"><RichText text={say('Add these details to include this crop in harvest forecasts. Leave sale price at 0 if unknown; its income estimate will be 0g. Custom crops use your values and are not ranked as new seed purchases.','以下数据将用于收获预测。若不知道售价，可填 0，收入估算也将为 0 金。自定义作物使用你填写的数据，不参与新种子购买排名。')}/></p><div className="form-grid gap-top"><label className="field">{say('Regrowth days (0 = one harvest)','再生天数（0 = 仅收获一次）')}<input type="number" required min={0} max={365} value={regrow} onChange={e=>setRegrow(Number(e.target.value))}/></label><label className="field">{say('Base sale price per item (g)','单个作物基础售价（金）')}<input type="number" required min={0} max={999999999} value={sell} onChange={e=>setSell(Number(e.target.value))}/></label><label className="field">{say('Minimum items per tile','每块地最低产量')}<input type="number" required min={1} max={999} value={yieldCount} onChange={e=>setYieldCount(Number(e.target.value))}/></label></div><fieldset className="crop-seasons"><legend>{say('Outdoor growing seasons','室外生长季节')}</legend>{SEASONS.map(s=><label key={s}><input type="checkbox" checked={seasons.includes(s)} onChange={e=>setSeasons(e.target.checked?[...seasons,s]:seasons.filter(x=>x!==s))}/>{t(s)}</label>)}</fieldset></>}
 <button className="btn primary gap-top" type="submit">{say('Add crop to calendar','添加到日历')}</button>{message&&<p className="small gap-top" role="status">{message}</p>}
 </form></details>;
}
