'use client';
import {useLocale,LanguageSwitch} from './locale-provider';
import {useEffect,useRef,useState,useCallback} from 'react';
import {CloudRain,Sun,Cloud,Check as CheckIcon} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {WEATHER,DAILY_LUCK,newRun,runSchema,type RunState,type GameDate} from '@/lib/game/state';
import {makePlan,startNextDay,deadlines,dateLabel,nextDate,gold,bundleDone,available,type Task,recordHarvest,suggestionKey,eventsOn,absoluteDay,fromDay,plotAlive,plotCrop} from '@/lib/game/planner';
import {bundles,LEVELS,wiki} from '@/lib/game/data';
import {Sprite,Choice,NumberField} from './farm-ui';
import FarmCalendar from './farm-calendar';
import PlanView from './plan-view';
import CollectionView from './collection-view';
import MoreView from './more-view';
import OnboardingDialog from './onboarding-dialog';
import DayStartDialog from './day-start-dialog';
import {InfoTip} from './item-tooltip';
import SaveImportDialog from './save-import-dialog';
import KrobusBuddy from './krobus-buddy';
import {createJournalBackup} from '@/lib/game/journal-backup';
export type UpdateRun=(next:RunState|((previous:RunState)=>RunState),reason?:string)=>void;
const WeatherIcon=({weather}:{weather:string})=>weather==='Rain'||weather==='Storm'||weather==='Green Rain'?<CloudRain size={26}/>:weather==='Sunny'?<Sun size={26}/>:<Cloud size={26}/>;
export default function FarmJournal(){
 const {render,t,locale,effects,setLocale,setEffects,taskLimit:limit,setTaskLimit:setLimit}=useLocale();
 const[dayStartOpen,setDayStartOpen]=useState(false);
 const[importOpen,setImportOpen]=useState(false);const[importMode,setImportMode]=useState<'game'|'journal'>('game');
 const[run,setRun]=useState<RunState>(newRun);const[tab,setTab]=useState('Play');const[loaded,setLoaded]=useState(false);const[setupOpen,setSetupOpen]=useState(false);const[setupFirstRun,setSetupFirstRun]=useState(false);const[status,setStatus]=useState('Loading farm…');const[error,setError]=useState('');const[message,setMessage]=useState('');const[dirty,setDirty]=useState(false);const[saving,setSaving]=useState(false);const[detail,setDetail]=useState<Task|null>(null);const[checkin,setCheckin]=useState(false);const[selected,setSelected]=useState<GameDate>(newRun().date);const[calendarView,setCalendarView]=useState<GameDate>(newRun().date);const revision=useRef(0);const runRef=useRef(run);const generation=useRef(0);
 const loadFarm=useCallback(async()=>{try{const response=await fetch('/api/run');const data=await response.json() as {error?:string;state?:unknown;revision:number;notice?:string};if(!response.ok)throw new Error(data.error);if(!Number.isSafeInteger(data.revision)||data.revision<0)throw new Error('Invalid saved-farm response.');if(data.notice)setMessage(data.notice);if(data.state){const saved=runSchema.parse(data.state);setRun(saved);runRef.current=saved;setSelected(saved.date);setCalendarView(saved.date);revision.current=data.revision;setStatus('Farm saved');setSetupOpen(false);}else{setStatus('New farm · not saved');revision.current=0;let seen=false;try{seen=localStorage.getItem('farm-journal-onboarding-seen')==='yes';}catch{}if(!seen){setSetupFirstRun(true);setSetupOpen(true);}}setLoaded(true);setDirty(false);}catch(e){setError(e instanceof Error?e.message:'Could not load your farm.');setStatus('Draft only');setLoaded(true);}},[]);
 // Loading persisted external state on mount is intentional; edits are handled explicitly.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void loadFarm();},[loadFarm]);
 const update:UpdateRun=useCallback((next,reason)=>{const changed=typeof next==='function'?next(runRef.current):next;const result=runSchema.safeParse(changed);if(!result.success){setError('Check your date and quantities. The last valid farm is preserved.');return;}const state=reason?{...result.data,history:[reason,...result.data.history].slice(0,20)}:result.data;runRef.current=state;setRun(state);generation.current++;setDirty(true);setStatus('Unsaved changes');},[]);
 const save=async(state:RunState=runRef.current,submitted:number=generation.current)=>{if(saving)return;setSaving(true);setError('');try{const response=await fetch('/api/run',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state,revision:revision.current})});const data=await response.json() as {error?:string;state?:unknown;revision:number;notice?:string};if(!response.ok)throw new Error(data.error);if(!Number.isSafeInteger(data.revision)||data.revision<1)throw new Error('Could not verify saved revision. Reload before saving again.');revision.current=data.revision;if(submitted===generation.current){setDirty(false);setStatus('Farm saved');}else setStatus('Unsaved changes');}catch(e){setError(e instanceof Error?e.message:'Could not save. Export your draft and retry.');setStatus('Save needs attention');}finally{setSaving(false)}};
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'read_farm_plan',title:t('Read today’s farm plan'),description:t('Read the current farm date, priorities and deadlines without changing the farm.'),inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(typeof input!=='object'||input===null||Array.isArray(input)||Object.keys(input).length)throw new Error('No inputs expected.');return {date:runRef.current.date,tasks:makePlan(runRef.current),deadlines:deadlines(runRef.current)}}},{signal:controller.signal})).catch(()=>{setMessage('Browser assistant tools are unavailable. The journal controls still work.');});return()=>controller.abort()},[t]);
 const markSetupSeen=()=>{try{localStorage.setItem('farm-journal-onboarding-seen','yes')}catch{}};
 const skipSetup=()=>{markSetupSeen();setSetupOpen(false);setSetupFirstRun(false);setMessage('You can run the setup guide anytime from More.');};
 const completeSetup=(configured:RunState)=>{const valid=runSchema.parse(configured);runRef.current=valid;setRun(valid);setSelected(valid.date);setCalendarView(valid.date);generation.current++;const submitted=generation.current;setDirty(true);setStatus('Unsaved changes');markSetupSeen();setSetupOpen(false);setSetupFirstRun(false);setMessage('Setup complete. Your calendar is ready.');void save(valid,submitted);};
 const openSetup=()=>{setSetupFirstRun(false);setSetupOpen(true);};
 const exportFarm=()=>{try{const backup=createJournalBackup(runRef.current,{locale,effects,taskLimit:limit});const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const a=document.createElement('a');const name=runRef.current.name.replace(/[^a-z0-9_-]/gi,'-').replace(/-+/g,'-').slice(0,50)||'my-farm';a.href=url;a.download=`stardew-journal-${name}-${backup.exportedAt.slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Backup downloaded. Your farm is packed and ready to travel.');}catch{setError('The download did not work. Try again before closing this tab.');}};

 const allTasks=makePlan(run);const harvestInbox=run.plots.filter(p=>p.nextHarvest<=absoluteDay(run.date)+3&&plotAlive(p,fromDay(Math.max(absoluteDay(run.date),p.nextHarvest)))).sort((a,b)=>a.nextHarvest-b.nextHarvest);const tasks=allTasks.slice(0,limit===99?99:Math.min(limit,run.level===1?3:run.level===2?5:99));const misses=deadlines(run);const complete=bundles.filter(b=>bundleDone(run,b)).length;
 const toggleTask=(task:Task)=>update(r=>({...r,done:r.done.includes(task.id)?r.done.filter(id=>id!==task.id):[...r.done,task.id],notes:r.notes.map(n=>task.id.endsWith(':note-'+n.id)?{...n,done:!r.done.includes(task.id)}:n)}));const toggleSuggestion=(task:Task)=>update(r=>({...r,mutedSuggestions:r.mutedSuggestions.includes(suggestionKey(task))?r.mutedSuggestions.filter(key=>key!==suggestionKey(task)):[...r.mutedSuggestions,suggestionKey(task)]}));
 const selectDate=(d:GameDate)=>{setSelected(d);setCalendarView(d);setTab('Plan')};
 const advance=(weather:RunState['weather'],luck:RunState['luck'])=>{const next=startNextDay(runRef.current,weather,luck);update(next,`Moved to ${dateLabel(next.date)}. Plan recalculated.`);setSelected(next.date);setCalendarView(next.date);setDayStartOpen(false);setTab('Play')};
 return render(<div className="farm-app" data-season={run.date.season}><a className="skip-link" href="#main">Skip to today’s plan</a><header className="site-header"><div className="header-inner"><div className="brand"><KrobusBuddy/><div><div className="brand-name pixel">Stardew Farm Journal</div><p>IN KROBUS WE TRUST</p></div></div><div className="header-right"><LanguageSwitch/><span className="save-status" role="status">{saving?'Saving farm…':status}</span><button className="btn" disabled={!loaded||saving||(!dirty&&status==='Farm saved')} onClick={()=>void save()}>{saving?'Saving…':'Save farm'}</button></div></div></header>
 <main className="journal" id="main"><Tabs value={tab} onValueChange={setTab}><div className="nav-strip"><TabsList className="farm-tabs" aria-label="Farm journal navigation">{[['Play','Parsnip'],['Plan','Calendar'],['Collection','Bundle Green'],['More','Sunflower']].map(([name,sprite])=><TabsTrigger value={name} key={name}><Sprite name={sprite} size={26}/>{name}</TabsTrigger>)}</TabsList><div className="nav-caption"><span translate="no">{run.name}</span> · {LEVELS[run.level-1]} · {run.goal}</div></div>
 {error&&<div className="error-note" role="alert">{error} <button className="btn quiet compact" onClick={exportFarm}>Export draft</button><button className="btn quiet compact" onClick={()=>setError('')}>Dismiss</button></div>}
 {message&&<div className="preview-note" role="status">{message} <button className="btn quiet compact" onClick={()=>setMessage('')}>Dismiss</button></div>}
 {!loaded?<div className="loading-screen"><Sprite name="Parsnip"/><h1>Opening your farm journal…</h1></div>:<>
 <TabsContent value="Play"><div className="topline"><div className="date-display"><span className="date-number">{run.date.day}</span><div><p className="eyebrow"><span translate="no">{run.name}</span> · Year {run.date.year}</p><h1 className="season-title">{run.date.season}, {['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][(run.date.day-1)%7]}</h1></div></div><div className="day-controls"><button className="btn quiet weather-strip" onClick={()=>setCheckin(true)} aria-label="Update today’s weather"><WeatherIcon weather={run.weather}/><span>{run.weather}</span><span className="small"> · {run.luck==='Unknown'?'Luck not checked':`${t('Luck')}: ${t(run.luck)}`}</span><span className="muted small">Update weather & luck</span></button><button className="btn primary next-day-button" title="Set tomorrow’s weather and luck" disabled={run.date.year===999&&run.date.season==='Winter'&&run.date.day===28} onClick={()=>setDayStartOpen(true)}>Next day <span aria-hidden="true">→</span></button></div></div>

 {harvestInbox.length>0&&<section className="paper harvest-inbox"><div className="section-heading ruled"><div><h2>Ready in your fields</h2><p className="small muted">A little harvest check, for today and the next few days.</p></div><button className="btn compact" onClick={()=>setTab('Plan')}>Open crop planner</button></div><div className="harvest-inbox-list">{harvestInbox.map(p=>{const ready=p.nextHarvest<=absoluteDay(run.date),crop=plotCrop(p);return <div className="harvest-inbox-row" key={p.id}><Sprite name={p.crop}/><div><strong>{p.quantity} {p.crop}</strong><p className="small muted">{ready?'Ready today':'Ready '+dateLabel(fromDay(p.nextHarvest))}{crop?' · at least '+p.quantity*crop.yield+' to gather':''}</p></div>{ready?<button data-cozy-effect="harvest" className="btn primary compact" onClick={()=>update(recordHarvest(run,p.id),'Harvested '+p.quantity+' '+p.crop+'.')}>Record harvest</button>:<span className="small muted">Coming up</span>}</div>})}</div></section>}
 <div className="play-layout"><div><section className="paper"><div className="section-heading ruled"><h2>A good day, one step at a time</h2><span className="small muted">{tasks.filter(t=>!run.done.includes(t.id)).length<=3?'A gentle day':'Lots to look forward to'}</span></div>
 {misses[0]&&<div className="mobile-only small danger-text" style={{marginBottom:12}}>Don’t miss: {misses[0].name} · {misses[0].detail}</div>}
 {[0,1,2].map(group=>{const grouped=tasks.filter(t=>t.group===group);return grouped.length?<div key={group}><h3 className="task-group-title">{['If you do one thing','Then, if you like','Only if it sounds fun'][group]}</h3><div className="task-list">{grouped.map((task,i)=><div className={`task-row ${group===0&&i===0?'first ':''}${run.done.includes(task.id)?'completed':''}`} key={task.id}><Sprite name={task.entity}/><div><button className="task-title" translate={task.category==='Personal'?'no':undefined} onClick={()=>setDetail(task)}>{task.name}</button><InfoTip label="Why this task?" text={`${task.category} · ${task.confidence}. ${task.why}`} chinese={`${t(task.category)} · ${t(task.confidence)}。${t(task.why)}`}/><p className="task-meta">{task.detail}</p></div><Checkbox className="farm-check" checked={run.done.includes(task.id)} onCheckedChange={()=>toggleTask(task)} aria-label={`Mark ${task.name} ${run.done.includes(task.id)?'incomplete':'complete'}`}/></div>)}</div></div>:null})}
 {!tasks.length&&<p className="empty-note">A quiet day. Check your fields, or pin a task in Plan.</p>}
 <div className="essentials"><span className="small muted">Keep it manageable</span><div className="button-group">{[[3,'3 tasks'],[5,'5 tasks'],[99,'Full plan']].map(([n,label])=><button className={'btn compact '+(limit===n?'selected':'')} key={n} onClick={()=>setLimit(n as number)}>{label}</button>)}</div></div></section>
 <section className="outlook" aria-label="Three-day outlook">{[0,1,2].map(offset=>{const d=nextDate(run.date,offset),weather=offset===0?run.weather:offset===1?run.tomorrow:'Unknown',forecast=makePlan({...run,date:d,weather,luck:offset===0?run.luck:'Unknown'}),calendar=eventsOn(run,d).filter(e=>e.type==='festival'||e.type==='birthday'),upcoming=deadlines({...run,date:d,weather,tomorrow:offset===0?run.tomorrow:'Unknown'}).filter(x=>x.day===d.day||(offset===0&&x.name==='Catfish opportunity')),harvests=run.plots.filter(p=>p.nextHarvest===absoluteDay(d));return <div className="outlook-day" key={offset}><h3>{['Today','Tomorrow','Day after'][offset]}</h3><p className="muted">{d.season} {d.day} · {weather}</p><p className="outlook-activity" translate={forecast[0]?.category==='Personal'?'no':undefined}>{forecast[0]?.name??'See where the day takes you'}</p>{calendar.map(e=><p className="outlook-note" key={e.name}>On the calendar: {e.name}</p>)}{upcoming.map(e=><p className="outlook-note" key={e.name}>Coming up: {e.name}</p>)}{harvests.map(p=><p className="outlook-note" key={p.id}>Harvest: {p.quantity} {p.crop}</p>)}{!calendar.length&&!upcoming.length&&!harvests.length&&<p className="small muted">Room for whatever feels good.</p>}</div>})}</section>
 <section className="checkin"><div className="section-heading"><h2>Today at a glance</h2></div><div className="balance-strip"><div><span className="small muted">In your wallet</span><strong>{gold(run.gold)}</strong></div><div><span className="small muted">Available to spend <InfoTip label="Available gold" text="Your wallet minus your minimum gold reserve and any gold reserved for purchases. Future harvest income is not included." chinese="当前金币减去最低预留金币及为购买项目预留的金币。不包含未来收获收入。"/></span><strong>{gold(available(run,'Gold'))}</strong></div><div><span className="small muted">Mine progress</span><strong>Floor {run.mineFloor} / 120</strong></div></div></section>
 </div><aside><section className="notice"><div className="section-heading" style={{marginBottom:0}}><h2>Don’t miss</h2><span className="eyebrow">This season</span></div>{misses.length?misses.slice(0,3).map((m,i)=><div className="deadline-row" key={i}><Sprite name={m.entity} size={36}/><div><strong>{m.name}</strong><p className={m.urgent?'urgent':''}>{m.detail}</p></div></div>):<p className="small gap-top">No tracked deadlines coming up. Enjoy the breathing room.</p>}</section><FarmCalendar run={run} view={calendarView} selected={run.date} onView={setCalendarView} onSelect={selectDate}/><section className="gap-top"><div className="section-heading"><h3>Community Center</h3><span className="small">{complete} / 30 bundles</span></div><Progress value={complete/30*100} className="progress" aria-label={`${complete} of 30 standard bundles completed`}/><button className="btn quiet compact gap-top" onClick={()=>setTab('Collection')}>Open collection</button></section></aside></div>
 {run.history.length>0&&<details className="gap-top small"><summary>{Math.min(3,run.history.length)} recent plan changes</summary><ul>{run.history.slice(0,3).map((x,i)=><li key={i}>{x}</li>)}</ul></details>}
 </TabsContent>
 <TabsContent value="Plan"><PlanView run={run} update={update} selected={selected} setSelected={setSelected} view={calendarView} setView={setCalendarView}/></TabsContent>
 <TabsContent value="Collection"><CollectionView run={run} update={update}/></TabsContent>
 <TabsContent value="More"><MoreView run={run} update={update} onRestore={()=>{setImportMode('journal');setImportOpen(true)}} onImport={()=>{setImportMode('game');setImportOpen(true)}} onExport={exportFarm} onMessage={setMessage} onError={setError} onReload={loadFarm} onSetup={openSetup}/></TabsContent>
 </>}
 </Tabs></main><footer className="footer"><span>Unofficial fan companion · Stardew Valley © ConcernedApe</span><span>Game data & sprites: <a href="https://stardewvalleywiki.com/" target="_blank" rel="noreferrer">Stardew Valley Wiki</a> · 1.6 planning · <button onClick={()=>setTab('More')} style={{textDecoration:'underline'}}>Sources & scope</button></span></footer>
 {importOpen&&<SaveImportDialog mode={importMode} base={run} onClose={()=>{setImportOpen(false);if(setupFirstRun)setSetupOpen(true)}} onApply={imported=>{update(imported.run);if(imported.preferences){setLocale(imported.preferences.locale);setEffects(imported.preferences.effects);setLimit(imported.preferences.taskLimit);}setSelected(imported.run.date);setCalendarView(imported.run.date);setMessage(imported.summary);setTab('Play');markSetupSeen();setSetupOpen(false);setSetupFirstRun(false);setImportOpen(false)}}/>}
 {setupOpen&&<OnboardingDialog open={setupOpen} firstRun={setupFirstRun} base={run} onComplete={completeSetup} onSkip={skipSetup} onImport={()=>{setImportMode('game');setSetupOpen(false);setImportOpen(true)}}/>}
 <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="farm-dialog"><DialogTitle translate={detail?.category==='Personal'?'no':undefined}>{detail?.name}</DialogTitle><DialogDescription>{detail?.detail}</DialogDescription>{detail&&<><div className="description"><Sprite name={detail.entity} size={64}/><h3>Why it could be a good fit</h3><p>{detail.why}</p><h3>If today gets busy</h3><p>{detail.skip}</p><p className="small muted">Checking this off saves your progress. Update gold, supplies and harvests whenever you like.</p></div><div className="button-group"><button className="btn primary" onClick={()=>{toggleTask(detail);setDetail(null)}}><CheckIcon size={16}/>{run.done.includes(detail.id)?'Mark incomplete':'Mark complete'}</button><button className="btn" onClick={()=>{toggleSuggestion(detail);setDetail(null)}}>Hide this kind of suggestion</button><a className="btn" href={wiki(detail.entity==='Calendar'?'Festivals':detail.entity)} target="_blank" rel="noreferrer">Wiki details</a></div></>}</DialogContent></Dialog>
 {dayStartOpen&&<DayStartDialog run={run} onCancel={()=>setDayStartOpen(false)} onStart={advance}/>}
 <Dialog open={checkin} onOpenChange={setCheckin}><DialogContent className="farm-dialog"><DialogTitle>How’s the farm feeling today?</DialogTitle><DialogDescription>Tell me what’s new, and I’ll freshen up today’s plan.</DialogDescription><div className="form-grid"><NumberField label="Gold" value={run.gold} onChange={gold=>update({...run,gold})}/><NumberField label="Deepest mine floor" value={run.mineFloor} max={120} onChange={mineFloor=>update({...run,mineFloor})}/><Choice label="Weather today" value={run.weather} options={WEATHER} onChange={weather=>update({...run,weather:weather as RunState['weather']},`Weather updated to ${weather}. Plan recalculated.`)}/><Choice label="Daily luck" value={run.luck} options={DAILY_LUCK} onChange={luck=>update({...run,luck:luck as RunState['luck']})}/><Choice label="TV forecast: tomorrow" value={run.tomorrow} options={WEATHER} onChange={tomorrow=>update({...run,tomorrow:tomorrow as RunState['tomorrow']},`Tomorrow’s forecast: ${tomorrow}.`)}/></div><button className="btn primary" onClick={()=>setCheckin(false)}>Back to today</button></DialogContent></Dialog>
 </div>);
}
