'use client';
import {useLocale} from './locale-provider';
import {ChevronLeft,ChevronRight,Flag,Gift} from 'lucide-react';
import {Sprite} from './farm-ui';
import {eventsOn,absoluteDay,fromDay,dateLabel} from '@/lib/game/planner';
import type {RunState,GameDate} from '@/lib/game/state';
export default function FarmCalendar({run,view,selected,onView,onSelect,large=false}:{run:RunState;view:GameDate;selected:GameDate;onView:(d:GameDate)=>void;onSelect:(d:GameDate)=>void;large?:boolean}){
 const {render,locale}=useLocale();
 const first=absoluteDay({...view,day:1});
 return render(<section className={'calendar-frame '+(large?'month-large':'')} aria-label="Season calendar" data-season={view.season}><div className="calendar-head"><button className="btn quiet compact" aria-label="Previous season" disabled={first===1} onClick={()=>onView(fromDay(first-1))}><ChevronLeft size={18}/></button><h2>{view.season} <span className="muted">·</span> Year {view.year}</h2><button className="btn quiet compact" aria-label="Next season" onClick={()=>onView(fromDay(first+28))}><ChevronRight size={18}/></button></div><div className="calendar-week">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span key={d}>{d==='Sun'&&locale==='zh-CN'?'日':d}</span>)}</div><div className="calendar-grid">{Array.from({length:28},(_,i)=>{const date={...view,day:i+1};const day=absoluteDay(date);const es=eventsOn(run,date);const plots=run.plots.filter(p=>p.nextHarvest===day);const isToday=day===absoluteDay(run.date);const note=run.notes.filter(n=>absoluteDay(n.date)===day&&!n.done);const count=es.length+plots.length+note.length;const display=plots[0]?.crop??es.find(e=>e.type==='birthday')?.name;return <button key={i} className={'calendar-day '+(isToday?'today ':'')+(day===absoluteDay(selected)?'selected ':'')+(day<absoluteDay(run.date)?'past':'')} data-event={plots.length?'harvest':es.some(e=>e.type==='festival')?'festival':es.some(e=>e.type==='birthday')?'birthday':undefined} aria-label={`${dateLabel(date)}${isToday?', today':''}${es.length?', '+es.map(e=>e.type==='birthday'?e.name+' birthday':e.name).join(', '):''}${plots.length?', harvest '+plots.map(p=>p.crop).join(', '):''}`} aria-pressed={day===absoluteDay(selected)} onClick={()=>onSelect(date)} onKeyDown={e=>{const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7}[e.key];if(delta){e.preventDefault();const next=fromDay(day+delta);onSelect(next);if(next.season!==view.season||next.year!==view.year)onView(next);else (e.currentTarget.parentElement?.children[next.day-1] as HTMLButtonElement)?.focus();}}}><span className="day-n">{i+1}</span><span className="day-icon">{display?<Sprite name={display} size={28}/>:es.some(e=>e.type==='festival')?<Flag size={20} color="#a66038"/>:note.length?<span className="pixel">✎</span>:null}</span>{count>1&&<span className="day-more">+{count-1}</span>}</button>})}</div><div className="calendar-foot">Select a day to look ahead. <span aria-hidden="true">·</span> <Gift size={12} style={{display:'inline'}}/> Birthdays & harvests</div></section>);
}
