'use client';
/* eslint-disable @next/next/no-img-element -- Community Center room previews use canonical Stardew Valley Wiki room art. */
import {useLocale,LanguageSwitch} from './locale-provider';
import {useEffect,useRef,useState,useCallback,useMemo} from 'react';
import {CloudRain,Sun,Cloud,Check as CheckIcon,RefreshCw} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {WEATHER,DAILY_LUCK,newRun,runSchema,type RunState,type GameDate,type ActivityDay} from '@/lib/game/state';
import {makePlan,makeSimplePlan,startNextDay,startNextDaySimple,deadlines,dateLabel,nextDate,gold,bundleDone,type Task,recordHarvest,eventsOn,absoluteDay,fromDay,plotAlive,plotCrop,lastPlantDay,needed,greenRainPossible} from '@/lib/game/planner';
import {bundles,LEVELS,wiki,festivalSprite} from '@/lib/game/data';
import {Sprite,Choice,NumberField,RichText,GoldAmount} from './farm-ui';
import FarmCalendar from './farm-calendar';
import PlanView from './plan-view';
import CollectionView from './collection-view';
import MoreView from './more-view';
import EncyclopediaView from './encyclopedia-view';
import OnboardingDialog from './onboarding-dialog';
import ModeChoiceDialog from './mode-choice-dialog';
import DayStartDialog from './day-start-dialog';
import {InfoTip,ObtainBlock} from './item-tooltip';
import SaveImportDialog from './save-import-dialog';
import KrobusBuddy from './krobus-buddy';
import {createJournalBackup} from '@/lib/game/journal-backup';
import {captureActivity,closeActivityDay,dayEntry,brokenRecords,personalRecords} from '@/lib/game/activity';
import {communityRoomImages} from '@/lib/game/community';
import {machineBatchesForDate,machineReadyAt,readyMachineBatches} from '@/lib/game/machines';
import {localPreferenceStorage,markSimpleNextDayIntroSeen,shouldShowSimpleNextDayIntro} from '@/lib/ui/local-preferences';
import {SeasonalDetails,MorningReminder,HarvestPreview,SeasonTransition,DailySummary,RecordToast,Scrapbook,type RecapPeriod} from './farm-moments';
import SeasonalJunimos from './seasonal-junimos';
import PlannerNotepad from './planner-notepad';
export type UpdateRun=(next:RunState|((previous:RunState)=>RunState),reason?:string)=>void;
const WeatherIcon=({weather}:{weather:string})=>weather==='Rain'||weather==='Storm'||weather==='Green Rain'?<CloudRain size={26}/>:weather==='Sunny'?<Sun size={26}/>:<Cloud size={26}/>;

export default function FarmJournal(){
 const {render,t,locale,effects,setLocale,setEffects,taskLimit:limit,setTaskLimit:setLimit}=useLocale();
 const[recapPeriod,setRecapPeriod]=useState<RecapPeriod|null>(null);const[dailySummary,setDailySummary]=useState<ActivityDay|null>(null);const[records,setRecords]=useState<ReturnType<typeof personalRecords>>([]);const[goodCatch,setGoodCatch]=useState<{crop:string;days:number}|null>(null);
 const[importCheck,setImportCheck]=useState<RunState|null>(null);
 const[dayStartOpen,setDayStartOpen]=useState(false);
 const[importOpen,setImportOpen]=useState(false);const[importMode,setImportMode]=useState<'game'|'journal'>('game');
 const[run,setRun]=useState<RunState>(newRun);const[tab,setTab]=useState('Play');const[planSection,setPlanSection]=useState('Calendar');const[loaded,setLoaded]=useState(false);const[modeChoiceOpen,setModeChoiceOpen]=useState(false);const[setupOpen,setSetupOpen]=useState(false);const[setupFirstRun,setSetupFirstRun]=useState(false);const[status,setStatus]=useState('Loading farm…');const[error,setError]=useState('');const[message,setMessage]=useState('');const[dirty,setDirty]=useState(false);const[saving,setSaving]=useState(false);const[detail,setDetail]=useState<Task|null>(null);const[checkin,setCheckin]=useState(false);const[selected,setSelected]=useState<GameDate>(newRun().date);const[calendarView,setCalendarView]=useState<GameDate>(newRun().date);const revision=useRef(0);const runRef=useRef(run);const generation=useRef(0);const simpleNextDayIntroSeenRef=useRef(false);
 const loadFarm=useCallback(async()=>{try{const response=await fetch('/api/run');const data=await response.json() as {error?:string;state?:unknown;revision:number;notice?:string};if(!response.ok)throw new Error(data.error);if(!Number.isSafeInteger(data.revision)||data.revision<0)throw new Error('Invalid saved-farm response.');if(data.notice)setMessage(data.notice);let modeSeen=false;let storedMode:RunState['plannerMode']|null=null;let onboardingSeen=false;try{modeSeen=localStorage.getItem('pelican-planner-mode-choice-seen')==='yes';const raw=localStorage.getItem('pelican-planner-mode');storedMode=raw==='simple'||raw==='full'?raw:null;onboardingSeen=(localStorage.getItem('pelican-planner-onboarding-seen')??localStorage.getItem('farm-journal-onboarding-seen'))==='yes';}catch{}if(data.state){const parsed=runSchema.parse(data.state);const saved=storedMode?{...parsed,plannerMode:storedMode}:parsed;setRun(saved);runRef.current=saved;setSelected(saved.date);setCalendarView(saved.date);revision.current=data.revision;setStatus('Farm saved');setSetupOpen(false);if(!modeSeen)setModeChoiceOpen(true);}else{const fresh={...newRun(),plannerMode:storedMode??'full'} as RunState;setRun(fresh);runRef.current=fresh;setSelected(fresh.date);setCalendarView(fresh.date);setStatus('New farm · not saved');revision.current=0;if(!onboardingSeen){setSetupFirstRun(true);if(modeSeen)setSetupOpen(true);else setModeChoiceOpen(true);}}setLoaded(true);setDirty(false);}catch(e){setError(e instanceof Error?e.message:'Could not load your farm.');setStatus('Draft only');setLoaded(true);}},[]);
 // Loading persisted external state on mount is intentional; edits are handled explicitly.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void loadFarm();},[loadFarm]);
 const update:UpdateRun=useCallback((next,reason)=>{try{const previous=runRef.current;const changed=typeof next==='function'?next(previous):next;const tracked=captureActivity(previous,changed);const result=runSchema.safeParse(tracked);if(!result.success){setError('Check your date and quantities. The last valid farm is preserved.');return;}const state=reason?{...result.data,history:[reason,...result.data.history].slice(0,20)}:result.data;
 if(changed.activity===previous.activity&&absoluteDay(changed.date)===absoluteDay(previous.date)){const broken=brokenRecords(previous,state);if(broken.length)setRecords(broken);const planted=changed.plots.find(p=>!previous.plots.some(old=>old.id===p.id)&&absoluteDay(p.planted)===absoluteDay(previous.date)&&needed(previous,p.crop));if(planted){const crop=plotCrop(planted);const spare=crop?lastPlantDay(crop,previous.date.season)-previous.date.day:-1;if(spare>=0&&spare<=1)setGoodCatch({crop:planted.crop,days:spare});}}
 runRef.current=state;setRun(state);generation.current++;setDirty(true);setStatus('Unsaved changes');}catch(e){setError(e instanceof Error?e.message:'Check your date and quantities. The last valid farm is preserved.');}},[]);
 useEffect(()=>{if(!records.length||recapPeriod||dayStartOpen)return;const timer=window.setTimeout(()=>setRecords([]),9000);return()=>window.clearTimeout(timer)},[records,recapPeriod,dayStartOpen]);
 const save=async(state:RunState=runRef.current,submitted:number=generation.current)=>{if(saving)return;setSaving(true);setError('');try{const response=await fetch('/api/run',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state,revision:revision.current})});const data=await response.json() as {error?:string;state?:unknown;revision:number;notice?:string};if(!response.ok)throw new Error(data.error);if(!Number.isSafeInteger(data.revision)||data.revision<1)throw new Error('Could not verify saved revision. Reload before saving again.');revision.current=data.revision;if(submitted===generation.current){setDirty(false);setStatus('Farm saved');}else setStatus('Unsaved changes');}catch(e){setError(e instanceof Error?e.message:'Could not save. Export your draft and retry.');setStatus('Save needs attention');}finally{setSaving(false)}};
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'read_farm_plan',title:t('Read today’s farm plan'),description:t('Read the current farm date, priorities and deadlines without changing the farm.'),inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(typeof input!=='object'||input===null||Array.isArray(input)||Object.keys(input).length)throw new Error('No inputs expected.');const current=runRef.current;return {date:current.date,mode:current.plannerMode,tasks:current.plannerMode==='simple'?makeSimplePlan(current):makePlan(current),deadlines:deadlines(current)}}},{signal:controller.signal})).catch(()=>{setMessage('Browser assistant tools are unavailable. The journal controls still work.');});return()=>controller.abort()},[t]);
 const markSetupSeen=()=>{try{localStorage.setItem('pelican-planner-onboarding-seen','yes')}catch{}};
 const choosePlannerMode=(plannerMode:RunState['plannerMode'])=>{try{localStorage.setItem('pelican-planner-mode-choice-seen','yes');localStorage.setItem('pelican-planner-mode',plannerMode)}catch{}setModeChoiceOpen(false);update(current=>({...current,plannerMode}),`Switched to ${plannerMode==='simple'?'Simple':'Full'} Mode.`);if(setupFirstRun)setSetupOpen(true);else setMessage(`${plannerMode==='simple'?'Simple':'Full'} Mode is on. You can switch back anytime.`);};
 const skipSetup=()=>{markSetupSeen();setSetupOpen(false);setSetupFirstRun(false);setMessage('You can run the setup guide anytime from More.');};
 const completeSetup=(configured:RunState)=>{setRecapPeriod(null);setDailySummary(null);setRecords([]);setGoodCatch(null);const valid=runSchema.parse(configured);runRef.current=valid;setRun(valid);setSelected(valid.date);setCalendarView(valid.date);generation.current++;const submitted=generation.current;setDirty(true);setStatus('Unsaved changes');markSetupSeen();setSetupOpen(false);setSetupFirstRun(false);setMessage('Setup complete. Your calendar is ready.');void save(valid,submitted);};
 const openSetup=()=>{setSetupFirstRun(false);setSetupOpen(true);};
 const exportFarm=()=>{try{const backup=createJournalBackup(runRef.current,{locale,effects,taskLimit:limit});const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const a=document.createElement('a');const name=runRef.current.name.replace(/[^a-z0-9_-]/gi,'-').replace(/-+/g,'-').slice(0,50)||'my-farm';a.href=url;a.download=`pelican-planner-${name}-${backup.exportedAt.slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Backup downloaded. Your farm is packed and ready to travel.');}catch{setError('The download did not work. Try again before closing this tab.');}};

 const allTasks=useMemo(()=>run.plannerMode==='simple'?makeSimplePlan(run):makePlan(run),[run]);const harvestInbox=run.plots.filter(p=>p.nextHarvest<=absoluteDay(run.date)&&plotAlive(p,fromDay(Math.max(absoluteDay(run.date),p.nextHarvest)))).sort((a,b)=>a.nextHarvest-b.nextHarvest);const machineInbox=readyMachineBatches(run);const tasks=run.plannerMode==='simple'?allTasks.slice(0,3):allTasks.slice(0,limit===99?99:Math.min(limit,run.level===1?3:run.level===2?5:99));const misses=deadlines(run);const complete=bundles.filter(b=>bundleDone(run,b)).length;
 const toggleTask=(task:Task)=>update(r=>{const completing=!r.done.includes(task.id);const unlock=task.id.endsWith(':fishing-intro')?'Fishing Rod':task.id.endsWith(':community-center-intro')?'Forest Magic':null;return {...r,done:completing?[...r.done,task.id]:r.done.filter(id=>id!==task.id),unlocks:completing&&unlock?[...new Set([...r.unlocks,unlock])]:r.unlocks,notes:r.notes.map(n=>task.id.endsWith(':note-'+n.id)?{...n,done:completing}:n)}});
 const selectDate=(d:GameDate)=>{setSelected(d);setCalendarView(d);setTab('Plan')};
 const advance=(weather:RunState['weather'],luck:RunState['luck'],activity:ActivityDay)=>{try{const previous=runRef.current;const closed=closeActivityDay(previous,activity);const next=previous.plannerMode==='simple'?startNextDaySimple(closed):startNextDay(closed,weather,luck);update(next,`Moved to ${dateLabel(next.date)}. Plan recalculated.`);const broken=brokenRecords(previous,closed);if(broken.length)setRecords(broken);setDailySummary(previous.plannerMode==='simple'?null:next.activity.showDaily?dayEntry(closed):null);if(previous.date.day===28)setRecapPeriod({date:previous.date,year:previous.date.season==='Winter'});setGoodCatch(null);setSelected(next.date);setCalendarView(next.date);setDayStartOpen(false);setTab('Play')}catch(e){setError(e instanceof Error?e.message:'Could not start the next day.');}};
 const requestNextDay=()=>{const current=runRef.current;if(current.plannerMode==='full'){setDayStartOpen(true);return;}if(shouldShowSimpleNextDayIntro(simpleNextDayIntroSeenRef.current,localPreferenceStorage())){simpleNextDayIntroSeenRef.current=true;markSimpleNextDayIntroSeen(localPreferenceStorage());setDayStartOpen(true);return;}simpleNextDayIntroSeenRef.current=true;advance('Unknown','Unknown',dayEntry(current));};
 const outlook=useMemo(()=>[0,1,2].map(offset=>{const d=nextDate(run.date,offset),weather=offset===0?run.weather:offset===1?run.tomorrow:'Unknown';return {d,weather,forecast:run.plannerMode==='simple'?makeSimplePlan({...run,date:d,weather:'Unknown',luck:'Unknown'}):makePlan({...run,date:d,weather,luck:offset===0?run.luck:'Unknown'}),calendar:eventsOn(run,d).filter(e=>e.type==='festival'||e.type==='birthday'),upcoming:deadlines({...run,date:d,weather,tomorrow:offset===0?run.tomorrow:'Unknown'}).filter(x=>x.day===d.day||(offset===0&&x.name==='Catfish opportunity')),harvests:run.plots.filter(p=>p.nextHarvest===absoluteDay(d)),machines:machineBatchesForDate(run,d)}}),[run]);
 const simpleGoalLabel=run.goal==='Maximum Profit'?'Make money':run.goal==='Community Center'||run.goal==='Fast Greenhouse'?'Community Center':'A bit of everything';
 const navItems=run.plannerMode==='simple'?[{value:'Play',label:'Today',sprite:'Parsnip'},{value:'Plan',label:'Season',sprite:'Calendar'},{value:'Collection',label:'Bundles',sprite:'Bundle Green'},{value:'Encyclopedia',label:'Encyclopedia',sprite:'Dwarf Icon'},{value:'More',label:'More',sprite:'Sunflower'}]:[{value:'Play',label:'Play',sprite:'Parsnip'},{value:'Plan',label:'Plan',sprite:'Calendar'},{value:'Collection',label:'Collection',sprite:'Bundle Green'},{value:'Encyclopedia',label:'Encyclopedia',sprite:'Dwarf Icon'},{value:'More',label:'More',sprite:'Sunflower'}];
 return render(<div className="farm-app" data-season={run.date.season}><SeasonalJunimos season={run.date.season}/><SeasonalDetails key={run.date.season} season={run.date.season}/><a className="skip-link" href="#main">Skip to today’s plan</a><header className="site-header"><div className="header-inner"><div className="brand"><KrobusBuddy run={run} taskCount={allTasks.length}/><div className="brand-copy"><div className="brand-name pixel">Pelican Planner</div><p>IN KROBUS WE TRUST</p></div></div><div className="header-right"><LanguageSwitch/><span className="save-status" role="status">{saving?'Saving farm…':status}</span><button className="btn" disabled={!loaded||saving||(!dirty&&status==='Farm saved')} onClick={()=>void save()}>{saving?'Saving…':'Save farm'}</button></div></div></header>
 <div className="planner-workspace"><PlannerNotepad/><main className="journal" id="main"><Tabs value={tab} onValueChange={setTab}><div className="nav-strip"><TabsList className="farm-tabs" aria-label="Farm journal navigation">{navItems.map(item=><TabsTrigger value={item.value} key={item.value}><Sprite name={item.sprite} size={26}/>{item.label}</TabsTrigger>)}</TabsList><div className="planner-mode-switch" role="tablist" aria-label="Planner mode"><button role="tab" aria-selected={run.plannerMode==='simple'} className={run.plannerMode==='simple'?'active':''} onClick={()=>run.plannerMode!=='simple'&&choosePlannerMode('simple')}>Simple</button><button role="tab" aria-selected={run.plannerMode==='full'} className={run.plannerMode==='full'?'active':''} onClick={()=>run.plannerMode!=='full'&&choosePlannerMode('full')}>Full</button></div><div className="nav-caption"><span translate="no">{run.name}</span> · {run.plannerMode==='simple'?`${run.simpleFarmSize} farm · ${simpleGoalLabel}`:`${LEVELS[run.level-1]} · ${run.goal}`}</div></div>
 {error&&<div className="error-note" role="alert">{error} <button className="btn quiet compact" onClick={exportFarm}>Export draft</button><button className="btn quiet compact" onClick={()=>setError('')}>Dismiss</button></div>}
 {importCheck&&<div className="import-confidence" role="status" translate="no"><Sprite name="Calendar" size={32}/><p><strong>{locale==='zh-CN'?'农场已读入':'Your farm came through'}</strong><span>{t(dateLabel(importCheck.date))} · <GoldAmount value={importCheck.gold}/> · {locale==='zh-CN'?'矿井层数':'Mine floor'} {importCheck.mineFloor} · {importCheck.plots.reduce((n,p)=>n+p.quantity,0)} {locale==='zh-CN'?'块在种作物':'growing crop tiles'}</span></p><button className="btn quiet compact" onClick={()=>setImportCheck(null)}>{t('Dismiss')}</button></div>}
 {message&&<div className="preview-note" role="status">{message} <button className="btn quiet compact" onClick={()=>setMessage('')}>Dismiss</button></div>}
 {!loaded?<div className="loading-screen"><Sprite name="Parsnip"/><h1>Opening your farm journal…</h1></div>:<>
 <TabsContent value="Play"><div className="topline"><div className="date-display"><span className="date-number" key={absoluteDay(run.date)}>{run.date.day}</span><div><p className="eyebrow"><span translate="no">{run.name}</span> · Year {run.date.year}</p><h1 className="season-title">{run.date.season}, {['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][(run.date.day-1)%7]}</h1></div></div><div className="day-controls">{run.plannerMode==='full'&&<div className="weather-controls" aria-label="Today’s weather and luck"><button className="weather-status-button weather-button" onClick={()=>setCheckin(true)} aria-label={`Weather: ${run.weather}. Update weather and luck.`}><WeatherIcon weather={run.weather}/><span><small>Weather</small><strong>{run.weather}</strong></span></button><button className="weather-status-button luck-button" onClick={()=>setCheckin(true)} aria-label={`${run.luck==='Unknown'?'Luck not checked':`Luck: ${t(run.luck)}`}. Update weather and luck.`}><Sprite name="Rabbit's Foot" size={28}/><span><small>Luck</small><strong>{run.luck==='Unknown'?'Not checked':t(run.luck)}</strong></span></button><button className="weather-update-button" onClick={()=>setCheckin(true)} aria-label="Update weather and luck"><RefreshCw size={18}/><span>Update</span></button></div>}<button className="btn primary next-day-button" title={run.plannerMode==='simple'?'Move to the next day':'Set tomorrow’s weather and luck'} disabled={run.date.year===999&&run.date.season==='Winter'&&run.date.day===28} onClick={requestNextDay}><Sprite name="Calendar" size={20}/>Next day <span aria-hidden="true">→</span></button></div></div>

 {run.plannerMode==='full'&&<MorningReminder key={absoluteDay(run.date)} run={run}/>}
 {dailySummary&&<DailySummary entry={dailySummary} run={run} onClose={()=>setDailySummary(null)}/>}
 {goodCatch&&<div className="good-catch" role="status" translate="no"><Sprite name={goodCatch.crop} size={32}/><p>{locale==='zh-CN'?`赶上啦！${t(goodCatch.crop)}已种下，距离最后播种日${goodCatch.days===0?'就是今天':'还剩1天'}。记得每天浇水。`:`Good catch! You planted ${goodCatch.crop} ${goodCatch.days===0?'on its last planting day':'with 1 day to spare'}. Keep it watered.`}</p><button className="btn quiet compact" onClick={()=>setGoodCatch(null)}>{t('Dismiss')}</button></div>}
 <SeasonTransition run={run}/>{run.plannerMode==='full'&&<HarvestPreview run={run}/>}
 {harvestInbox.length>0&&<section className="paper harvest-inbox"><div className="section-heading ruled"><div><h2>Ready to harvest</h2></div><button className="btn compact" onClick={()=>setTab('Plan')}><Sprite name="Parsnip" size={20}/>Open crop planner</button></div><div className="harvest-inbox-list">{harvestInbox.map(p=>{const ready=p.nextHarvest<=absoluteDay(run.date),crop=plotCrop(p);return <div className="harvest-inbox-row" key={p.id}><Sprite name={p.crop}/><div><strong>{p.quantity} {p.crop}</strong><p className="small muted">{ready?'Ready today':'Ready '+dateLabel(fromDay(p.nextHarvest))}{crop?' · at least '+p.quantity*crop.yield+' to gather':''}</p></div>{ready?<button data-cozy-effect="harvest" className="btn primary compact" onClick={()=>update(recordHarvest(run,p.id),'Harvested '+p.quantity+' '+p.crop+'.')}>Record harvest</button>:<span className="small muted">Coming up</span>}</div>})}</div></section>}
 {machineInbox.length>0&&<section className="paper harvest-inbox machine-inbox" translate="no"><div className="section-heading ruled"><div><p className="eyebrow">Machine reminder</p><h2>Machine pickups</h2></div><button className="btn compact" onClick={()=>{setPlanSection('Machines');setTab('Plan')}}><Sprite name="Keg" size={20}/>Open machine planner</button></div><div className="harvest-inbox-list">{machineInbox.map(batch=>{const ready=machineReadyAt(batch.started,batch.startedTime,batch.processingMinutes);return <div className="harvest-inbox-row" key={batch.id}><Sprite name={batch.machine}/><div><strong>{batch.quantity}× {batch.product}</strong><p className="small muted">{batch.machine} · due {dateLabel(ready.date)} at {ready.time}</p></div><button className="btn primary compact" onClick={()=>update({...run,machineBatches:run.machineBatches.map(x=>x.id===batch.id?{...x,collected:true}:x)},`Collected ${batch.quantity} ${batch.product}.`)}>Collected</button></div>})}</div></section>}
 <div className={`play-layout ${run.plannerMode==='simple'?'simple-play-layout':''}`}><div><section className="paper"><div className="section-heading ruled play-plan-heading"><h2>Today</h2></div>
 {misses[0]&&<div className="mobile-only small danger-text mobile-deadline" style={{marginBottom:12}}><Sprite name={misses[0].entity} size={22}/><span>{misses[0].name} · <RichText text={misses[0].detail}/></span></div>}
 {run.plannerMode==='simple'?<div className="simple-today-list">{tasks.map((task,i)=><div className={`task-row simple-task-row ${i===0?'first ':''}${run.done.includes(task.id)?'completed':''}`} key={task.id}><InfoTip label="Why this task?" text={task.why} trigger={<Sprite name={task.entity} size={44}/>} obtainFor={task.entity} year={run.date.year}/><div><button className="task-title" translate={task.category==='Personal'?'no':undefined} onClick={()=>setDetail(task)}>{task.name}</button><p className="task-meta"><RichText text={task.detail}/></p></div><Checkbox className="farm-check" checked={run.done.includes(task.id)} onCheckedChange={()=>toggleTask(task)} aria-label={`Mark ${task.name} ${run.done.includes(task.id)?'incomplete':'complete'}`}/></div>)}</div>:[0,1,2].map(group=>{const grouped=tasks.filter(t=>t.group===group);const labels=['Priority','Next','Optional'];const groupSprites=['Parsnip','Calendar','Sunflower'];return grouped.length?<div key={group}><h3 className="task-group-title sprite-heading"><Sprite name={groupSprites[group]} size={23}/><span>{labels[group]}</span></h3><div className="task-list">{grouped.map((task,i)=><div className={`task-row ${group===0&&i===0?'first ':''}${run.done.includes(task.id)?'completed':''}`} key={task.id}><InfoTip label="Why this task?" text={`${task.category} · ${task.confidence}. ${task.why}`} chinese={`${t(task.category)} · ${t(task.confidence)}。${t(task.why)}`} trigger={<Sprite name={task.entity}/>} obtainFor={task.entity} year={run.date.year}/><div><button className="task-title" translate={task.category==='Personal'?'no':undefined} onClick={()=>setDetail(task)}>{task.name}</button><p className="task-meta"><RichText text={task.detail}/></p></div><Checkbox className="farm-check" checked={run.done.includes(task.id)} onCheckedChange={()=>toggleTask(task)} aria-label={`Mark ${task.name} ${run.done.includes(task.id)?'incomplete':'complete'}`}/></div>)}</div></div>:null})}
 {!tasks.length&&<p className="empty-note">No planned tasks.</p>}
 {run.plannerMode==='full'&&<div className="essentials"><span className="small muted">Tasks shown</span><div className="button-group">{[[3,'3 tasks'],[5,'5 tasks'],[99,'Full plan']].map(([n,label])=><button className={'btn compact '+(limit===n?'selected':'')} key={n} onClick={()=>setLimit(n as number)}>{label}</button>)}</div></div>}</section>
 {run.plannerMode==='simple'?<section className="simple-coming-up"><div className="section-heading"><h2>Coming up</h2><button className="btn quiet compact" onClick={()=>setTab('Plan')}><Sprite name="Calendar" size={20}/>See season</button></div><div className="simple-coming-grid">{outlook.slice(1).map(({d,forecast,calendar,upcoming,harvests,machines},index)=>{const lead=forecast[0];return <div className="simple-coming-card" key={index}><strong>{index===0?'Tomorrow':'Day After'} · {d.season} {d.day}</strong><div className="outlook-main">{lead&&<Sprite name={lead.entity} size={30}/>}<span>{lead?.name??'Open day'}</span></div>{calendar[0]&&<small>{calendar[0].name}</small>}{upcoming[0]&&<small>{upcoming[0].name}</small>}{harvests[0]&&<small>{harvests[0].quantity} {harvests[0].crop} ready</small>}{machines[0]&&<small>{machines[0].quantity}× {machines[0].product} ready</small>}</div>})}</div></section>:<section className="outlook" aria-label="Three-day outlook">{outlook.map(({d,weather,forecast,calendar,upcoming,harvests,machines},offset)=>{const lead=forecast[0];return <div className="outlook-day" key={offset}><h3>{['Today','Tomorrow','Day After'][offset]}</h3><p className="muted">{d.season} {d.day}{run.plannerMode==='full'?` · ${weather}`:''}</p><div className="outlook-main">{lead&&<Sprite name={lead.entity} size={32}/>}<p className="outlook-activity" translate={lead?.category==='Personal'?'no':undefined}>{lead?.name??'No priority task'}</p></div>{calendar.map(e=><p className="outlook-note sprite-note" key={e.name}><Sprite name={e.type==='birthday'?e.name:e.type==='festival'?festivalSprite(e.name):'Calendar'} size={22}/><span>{e.name}</span></p>)}{upcoming.map(e=><p className="outlook-note sprite-note" key={e.name}><Sprite name={e.entity} size={22}/><span>{e.name}</span></p>)}{harvests.map(p=><p className="outlook-note sprite-note" key={p.id}><Sprite name={p.crop} size={22}/><span>{p.quantity} {p.crop} ready</span></p>)}{machines.map(b=><p className="outlook-note sprite-note" key={b.id} translate="no"><Sprite name={b.machine} size={22}/><span>{b.quantity}× {b.product} ready · {machineReadyAt(b.started,b.startedTime,b.processingMinutes).time}</span></p>)}{!calendar.length&&!upcoming.length&&!harvests.length&&!machines.length&&<p className="small muted">No scheduled items.</p>}</div>})}</section>}
 
 </div>{run.plannerMode==='full'&&<aside><section className="notice"><div className="section-heading" style={{marginBottom:0}}><h2>Don’t miss</h2><span className="eyebrow">This season</span></div>{misses.length?misses.slice(0,3).map((m,i)=><div className="deadline-row" key={i}><Sprite name={m.entity} size={36}/><div><strong>{m.name}</strong><p className={m.urgent?'urgent':''}><RichText text={m.detail}/></p></div></div>):<p className="small gap-top">No tracked deadlines this season.</p>}</section><FarmCalendar run={run} view={calendarView} selected={run.date} onView={setCalendarView} onSelect={selectDate}/><section className="gap-top community-center-card"><div className="community-center-head"><div className="community-center-title"><Sprite name="Bundle Green" size={34}/><div><h3>Community Center</h3><p>{complete===30?'All standard bundles complete':`${30-complete} bundle${30-complete===1?'':'s'} left`}</p></div></div><strong>{complete}<span>/30</span></strong></div><div className="community-room-strip" aria-label="Community Center rooms">{communityRoomImages.map(room=>{const done=bundles.filter(b=>b.room===room.name).every(b=>bundleDone(run,b));return <span className="community-room-image" key={room.name} role="img" aria-label={`${room.name}: ${done?'Complete':'In progress'}`} title={`${room.name}${done?' · ✓ Complete':''}`}><img src={room.src} alt="" loading="lazy" referrerPolicy="no-referrer"/>{done&&<span className="room-complete-check" aria-hidden="true">✓</span>}</span>})}</div><Progress value={complete/30*100} className="progress community-progress" aria-label={`${complete} of 30 standard bundles completed`}/><button className="btn compact community-center-open" onClick={()=>setTab('Collection')}><Sprite name="Bundle Green" size={20}/>Open bundles</button></section></aside>}</div>
 {run.plannerMode==='full'&&run.history.length>0&&<details className="gap-top small"><summary>{Math.min(3,run.history.length)} recent plan changes</summary><ul>{run.history.slice(0,3).map((x,i)=><li key={i}>{x}</li>)}</ul></details>}
 </TabsContent>
 <TabsContent value="Plan"><PlanView run={run} update={update} selected={selected} setSelected={setSelected} view={calendarView} setView={setCalendarView} section={planSection} setSection={setPlanSection}/></TabsContent>
 <TabsContent value="Collection"><CollectionView run={run} update={update}/></TabsContent>
 <TabsContent value="Encyclopedia"><EncyclopediaView/></TabsContent>
 <TabsContent value="More"><MoreView run={run} update={update} onOpenScrapbook={()=>{const last=run.activity.days.filter(d=>d.closed).at(-1);setRecapPeriod({date:last?.date??run.date,year:false})}} onRestore={()=>{setImportMode('journal');setImportOpen(true)}} onImport={()=>{setImportMode('game');setImportOpen(true)}} onExport={exportFarm} onMessage={setMessage} onError={setError} onReload={loadFarm} onSetup={openSetup}/></TabsContent>
 </>}
 </Tabs></main></div><footer className="footer"><span>Unofficial fan companion · Stardew Valley © ConcernedApe</span><span>Created by <a href="https://github.com/edyl-weiss" target="_blank" rel="noreferrer">Joe H</a></span><span>Game data & sprites: <a href="https://stardewvalleywiki.com/" target="_blank" rel="noreferrer">Stardew Valley Wiki</a> · 1.6 planning · <button onClick={()=>setTab('More')} style={{textDecoration:'underline'}}>Sources & scope</button></span></footer>
 {importOpen&&<SaveImportDialog mode={importMode} base={run} onClose={()=>{setImportOpen(false);if(setupFirstRun)setSetupOpen(true)}} onApply={imported=>{const importedRun=importMode==='game'?{...imported.run,plannerMode:runRef.current.plannerMode,simpleFarmSize:runRef.current.simpleFarmSize}:imported.run;setImportCheck(importedRun);setRecapPeriod(null);setDailySummary(null);setRecords([]);setGoodCatch(null);update(importedRun);if(imported.preferences){setLocale(imported.preferences.locale);setEffects(imported.preferences.effects);setLimit(imported.preferences.taskLimit);}setSelected(importedRun.date);setCalendarView(importedRun.date);setMessage(imported.summary);setTab('Play');markSetupSeen();setSetupOpen(false);setSetupFirstRun(false);setImportOpen(false)}}/>}
 {modeChoiceOpen&&<ModeChoiceDialog open={modeChoiceOpen} onChoose={choosePlannerMode}/>}
 {setupOpen&&<OnboardingDialog open={setupOpen} firstRun={setupFirstRun} base={run} onComplete={completeSetup} onSkip={skipSetup} onImport={()=>{setImportMode('game');setSetupOpen(false);setImportOpen(true)}}/>}
 <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="farm-dialog"><DialogTitle translate={detail?.category==='Personal'?'no':undefined}>{detail?.name}</DialogTitle><DialogDescription>{detail&&<RichText text={detail.detail}/>}</DialogDescription>{detail&&<><div className="description"><Sprite name={detail.entity} size={64}/><h3>Why it could be a good fit</h3><p><RichText text={detail.why}/></p><h3>If today gets busy</h3><p><RichText text={detail.skip}/></p><ObtainBlock name={detail.entity} year={run.date.year}/><p className="small muted">Checking this off saves it to your planner.</p></div><div className="button-group"><button className="btn primary" onClick={()=>{toggleTask(detail);setDetail(null)}}><CheckIcon size={16}/>{run.done.includes(detail.id)?'Mark incomplete':'Mark complete'}</button><a className="btn" href={wiki(detail.entity==='Calendar'?'Festivals':detail.entity)} target="_blank" rel="noreferrer">Wiki details</a></div></>}</DialogContent></Dialog>
 {recapPeriod&&<Scrapbook run={run} period={recapPeriod} onClose={()=>setRecapPeriod(null)} onPeriod={setRecapPeriod}/>}
 {records.length>0&&!recapPeriod&&!dayStartOpen&&<RecordToast records={records} onClose={()=>setRecords([])}/>}
 {dayStartOpen&&<DayStartDialog run={run} onCancel={()=>setDayStartOpen(false)} onStart={advance}/>}
 <Dialog open={checkin} onOpenChange={setCheckin}><DialogContent className="farm-dialog"><DialogTitle>{run.plannerMode==='simple'?'Quick farm update':'How’s the farm feeling today?'}</DialogTitle><DialogDescription>{run.plannerMode==='simple'?'Gold is optional. Keeping it current improves crop suggestions.':'Update today’s farm details.'}</DialogDescription>{run.plannerMode==='simple'?<div className="simple-checkin"><NumberField label="Current gold" value={run.gold} onChange={gold=>update({...run,gold})}/><p className="label-note">No weather, luck, or mine-floor update needed.</p></div>:<div className="form-grid"><NumberField label="Gold" value={run.gold} onChange={gold=>update({...run,gold})}/><NumberField label="Deepest mine floor" value={run.mineFloor} max={120} onChange={mineFloor=>update({...run,mineFloor})}/><Choice label="Weather today" value={run.weather} options={WEATHER.filter(w=>w!=='Green Rain'||greenRainPossible(run.date))} onChange={weather=>update({...run,weather:weather as RunState['weather']},`Weather updated to ${weather}. Plan recalculated.`)}/><Choice label="Daily luck" value={run.luck} options={DAILY_LUCK} onChange={luck=>update({...run,luck:luck as RunState['luck']})}/><Choice label="TV forecast: tomorrow" value={run.tomorrow} options={WEATHER.filter(w=>w!=='Green Rain'||greenRainPossible(nextDate(run.date)))} onChange={tomorrow=>update({...run,tomorrow:tomorrow as RunState['tomorrow']},`Tomorrow’s forecast: ${tomorrow}.`)}/></div>}<button className="btn primary" onClick={()=>setCheckin(false)}>Back to today</button></DialogContent></Dialog>
 </div>);
}
