'use client';
import {useLocale,LanguageSwitch} from './locale-provider';
import {useEffect,useRef,useState,useCallback} from 'react';
import {CloudRain,Sun,Cloud,BookOpen,CalendarDays,Archive,Settings,Check as CheckIcon} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {newRun,runSchema,type RunState,type GameDate} from '@/lib/game/state';
import {makePlan,deadlines,dateLabel,nextDate,gold,bundleDone,available,type Task} from '@/lib/game/planner';
import {bundles,LEVELS,wiki} from '@/lib/game/data';
import {Sprite,Choice,NumberField} from './farm-ui';
import FarmCalendar from './farm-calendar';
import PlanView from './plan-view';
import CollectionView from './collection-view';
import MoreView from './more-view';
import OnboardingDialog from './onboarding-dialog';
import {InfoTip} from './item-tooltip';
import SaveImportDialog from './save-import-dialog';
export type UpdateRun=(next:RunState|((previous:RunState)=>RunState),reason?:string)=>void;
const WeatherIcon=({weather}:{weather:string})=>weather==='Rain'||weather==='Storm'?<CloudRain size={26}/>:weather==='Sunny'?<Sun size={26}/>:<Cloud size={26}/>;
export default function FarmJournal(){
 const {render,t}=useLocale();
 const[importOpen,setImportOpen]=useState(false);
 const[run,setRun]=useState<RunState>(newRun);const[tab,setTab]=useState('Play');const[loaded,setLoaded]=useState(false);const[setupOpen,setSetupOpen]=useState(false);const[setupFirstRun,setSetupFirstRun]=useState(false);const[status,setStatus]=useState('Loading farm…');const[error,setError]=useState('');const[message,setMessage]=useState('');const[dirty,setDirty]=useState(false);const[saving,setSaving]=useState(false);const[limit,setLimit]=useState(5);const[detail,setDetail]=useState<Task|null>(null);const[checkin,setCheckin]=useState(false);const[selected,setSelected]=useState<GameDate>(newRun().date);const[calendarView,setCalendarView]=useState<GameDate>(newRun().date);const revision=useRef(0);const runRef=useRef(run);const generation=useRef(0);
 const loadFarm=useCallback(async()=>{try{const response=await fetch('/api/run');const data=await response.json() as {error?:string;state?:unknown;revision:number;notice?:string};if(!response.ok)throw new Error(data.error);if(!Number.isSafeInteger(data.revision)||data.revision<0)throw new Error('Invalid saved-farm response.');if(data.notice)setMessage(data.notice);if(data.state){const saved=runSchema.parse(data.state);setRun(saved);runRef.current=saved;setSelected(saved.date);setCalendarView(saved.date);revision.current=data.revision;setStatus('Farm saved');setSetupOpen(false);}else{setStatus('New farm · not saved');revision.current=0;let seen=false;try{seen=localStorage.getItem('farm-journal-onboarding-seen')==='yes';}catch{}if(!seen){setSetupFirstRun(true);setSetupOpen(true);}}setLoaded(true);setDirty(false);}catch(e){setError(e instanceof Error?e.message:'Could not load your farm.');setStatus('Draft only');setLoaded(true);}},[]);
 // Loading persisted external state on mount is intentional; edits are handled explicitly.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void loadFarm();},[loadFarm]);
 const update:UpdateRun=useCallback((next,reason)=>{const changed=typeof next==='function'?next(runRef.current):next;const result=runSchema.safeParse(changed);if(!result.success){setError('Check your date and quantities. The last valid farm is preserved.');return;}const state=reason?{...result.data,history:[reason,...result.data.history].slice(0,20)}:result.data;runRef.current=state;setRun(state);generation.current++;setDirty(true);setStatus('Unsaved changes');},[]);
 const save=async(state:RunState=runRef.current,submitted:number=generation.current)=>{if(saving)return;setSaving(true);setError('');try{const response=await fetch('/api/run',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state,revision:revision.current})});const data=await response.json() as {error?:string;state?:unknown;revision:number;notice?:string};if(!response.ok)throw new Error(data.error);if(!Number.isSafeInteger(data.revision)||data.revision<1)throw new Error('Could not verify saved revision. Reload before saving again.');revision.current=data.revision;if(submitted===generation.current){setDirty(false);setStatus('Farm saved');}else setStatus('Unsaved changes');}catch(e){setError(e instanceof Error?e.message:'Could not save. Export your draft and retry.');setStatus('Save needs attention');}finally{setSaving(false)}};
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'read_farm_plan',title:t('Read today’s farm plan'),description:t('Read the current farm date, priorities and deadlines without changing the farm.'),inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(typeof input!=='object'||input===null||Array.isArray(input)||Object.keys(input).length)throw new Error('No inputs expected.');return {date:runRef.current.date,tasks:makePlan(runRef.current),deadlines:deadlines(runRef.current)}}},{signal:controller.signal})).catch(()=>{setMessage('Browser assistant tools are unavailable. The journal controls still work.');});return()=>controller.abort()},[t]);
 const markSetupSeen=()=>{try{localStorage.setItem('farm-journal-onboarding-seen','yes')}catch{}};
 const skipSetup=()=>{markSetupSeen();setSetupOpen(false);setSetupFirstRun(false);setMessage('You can run the setup guide anytime from More.');};
 const completeSetup=(configured:RunState)=>{const valid=runSchema.parse(configured);runRef.current=valid;setRun(valid);setSelected(valid.date);setCalendarView(valid.date);generation.current++;const submitted=generation.current;setDirty(true);setStatus('Unsaved changes');markSetupSeen();setSetupOpen(false);setSetupFirstRun(false);setMessage('Setup complete. Your calendar is ready.');void save(valid,submitted);};
 const openSetup=()=>{setSetupFirstRun(false);setSetupOpen(true);};
 const exportFarm=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(runRef.current,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='stardew-farm-journal.json';a.click();URL.revokeObjectURL(url);setMessage('Farm exported. Keep the file as a backup.');};

 const allTasks=makePlan(run);const tasks=allTasks.slice(0,limit===99?99:Math.min(limit,run.level===1?3:run.level===2?5:99));const misses=deadlines(run);const complete=bundles.filter(b=>bundleDone(run,b)).length;
 const toggleTask=(task:Task)=>update(r=>({...r,done:r.done.includes(task.id)?r.done.filter(id=>id!==task.id):[...r.done,task.id],notes:r.notes.map(n=>task.id.endsWith(':note-'+n.id)?{...n,done:!r.done.includes(task.id)}:n)}));
 const selectDate=(d:GameDate)=>{setSelected(d);setCalendarView(d);setTab('Plan')};
 const advance=()=>{const date=nextDate(run.date);update({...run,date,weather:run.tomorrow,tomorrow:'Unknown'},`Moved to ${dateLabel(date)}. Plan recalculated.`);setSelected(date);setCalendarView(date)};
 return render(<div className="farm-app" data-season={run.date.season}><a className="skip-link" href="#main">Skip to today’s plan</a><header className="site-header"><div className="header-inner"><div className="brand"><Sprite name="Parsnip" size={44}/><div><div className="brand-name pixel">Stardew Farm Journal</div><p>A LITTLE PLAN. A GOOD DAY.</p></div></div><div className="header-right"><LanguageSwitch/><span className="save-status" role="status">{saving?'Saving farm…':status}</span><button className="btn" disabled={!loaded||saving||(!dirty&&status==='Farm saved')} onClick={()=>void save()}>{saving?'Saving…':'Save farm'}</button></div></div></header>
 <main className="journal" id="main"><Tabs value={tab} onValueChange={setTab}><div className="nav-strip"><TabsList className="farm-tabs" aria-label="Farm journal navigation">{[['Play',BookOpen],['Plan',CalendarDays],['Collection',Archive],['More',Settings]].map(([name,Icon])=>{const I=Icon as typeof BookOpen;return <TabsTrigger value={name as string} key={name as string}><I size={17}/>{name as string}</TabsTrigger>})}</TabsList><div className="nav-caption"><span translate="no">{run.name}</span> · {LEVELS[run.level-1]} · {run.goal}</div></div>
 {error&&<div className="error-note" role="alert">{error} <button className="btn quiet compact" onClick={exportFarm}>Export draft</button><button className="btn quiet compact" onClick={()=>setError('')}>Dismiss</button></div>}
 {message&&<div className="preview-note" role="status">{message} <button className="btn quiet compact" onClick={()=>setMessage('')}>Dismiss</button></div>}
 {!loaded?<div className="loading-screen"><Sprite name="Parsnip"/><h1>Opening your farm journal…</h1></div>:<>
 <TabsContent value="Play"><div className="topline"><div className="date-display"><span className="date-number">{run.date.day}</span><div><p className="eyebrow"><span translate="no">{run.name}</span> · Year {run.date.year}</p><h1 className="season-title">{run.date.season}, {['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][(run.date.day-1)%7]}</h1></div></div><button className="btn quiet weather-strip" onClick={()=>setCheckin(true)} aria-label="Update today’s weather"><WeatherIcon weather={run.weather}/><span>{run.weather}</span><span className="muted small">Update</span></button></div>
 <div className="play-layout"><div><section className="paper"><div className="section-heading ruled"><h2>Today’s plan</h2><span className="small muted">{tasks.filter(t=>!run.done.includes(t.id)).length<=3?'Light day':'A full day'}</span></div>
 {misses[0]&&<div className="mobile-only small danger-text" style={{marginBottom:12}}>Don’t miss: {misses[0].name} · {misses[0].detail}</div>}
 {[0,1,2].map(group=>{const grouped=tasks.filter(t=>t.group===group);return grouped.length?<div key={group}><h3 className="task-group-title">{['Do first','Next','If you have time'][group]}</h3><div className="task-list">{grouped.map((task,i)=><div className={`task-row ${group===0&&i===0?'first ':''}${run.done.includes(task.id)?'completed':''}`} key={task.id}><Sprite name={task.entity}/><div><button className="task-title" translate={task.category==='Personal'?'no':undefined} onClick={()=>setDetail(task)}>{task.name}</button><InfoTip label="Why this task?" text={`${task.category} · ${task.confidence}. ${task.why}`} chinese={`${t(task.category)} · ${t(task.confidence)}。${t(task.why)}`}/><p className="task-meta">{task.detail}</p></div><Checkbox className="farm-check" checked={run.done.includes(task.id)} onCheckedChange={()=>toggleTask(task)} aria-label={`Mark ${task.name} ${run.done.includes(task.id)?'incomplete':'complete'}`}/></div>)}</div></div>:null})}
 {!tasks.length&&<p className="empty-note">A quiet day. Check your fields, or pin a task in Plan.</p>}
 <div className="essentials"><span className="small muted">Keep it manageable</span><div className="button-group">{[[3,'3 tasks'],[5,'5 tasks'],[99,'Full plan']].map(([n,label])=><button className={'btn compact '+(limit===n?'selected':'')} key={n} onClick={()=>setLimit(n as number)}>{label}</button>)}</div></div></section>
 <section className="outlook" aria-label="Three-day outlook">{[0,1,2].map(offset=>{const d=nextDate(run.date,offset);const weather=offset===0?run.weather:offset===1?run.tomorrow:'Unknown';const forecast=makePlan({...run,date:d,weather});return <div className="outlook-day" key={offset}><h3>{['Today','Tomorrow','Day after'][offset]}</h3><p className="muted">{d.season} {d.day} · {weather}</p><p translate={forecast[0]?.category==='Personal'?'no':undefined}>{forecast[0]?.name??'Room to explore'}</p></div>})}</section>
 <section className="checkin"><div className="section-heading"><h2>Quick check-in</h2><button className="btn compact" onClick={()=>setCheckin(true)}>Update farm</button></div><div className="balance-strip"><div><span className="small muted">In your wallet</span><strong>{gold(run.gold)}</strong></div><div><span className="small muted">Available to spend <InfoTip label="Available gold" text="Your wallet minus your minimum gold reserve and any gold reserved for purchases. Future harvest income is not included." chinese="当前金币减去最低预留金币及为购买项目预留的金币。不包含未来收获收入。"/></span><strong>{gold(available(run,'Gold'))}</strong></div><div><span className="small muted">Mine progress</span><strong>Floor {run.mineFloor} / 120</strong></div></div><button className="btn primary" onClick={advance}>Start next day</button></section>
 </div><aside><section className="notice"><div className="section-heading" style={{marginBottom:0}}><h2>Don’t miss</h2><span className="eyebrow">This season</span></div>{misses.length?misses.slice(0,3).map((m,i)=><div className="deadline-row" key={i}><Sprite name={m.entity} size={36}/><div><strong>{m.name}</strong><p className={m.urgent?'urgent':''}>{m.detail}</p></div></div>):<p className="small gap-top">No tracked deadlines coming up. Enjoy the breathing room.</p>}</section><FarmCalendar run={run} view={calendarView} selected={run.date} onView={setCalendarView} onSelect={selectDate}/><section className="gap-top"><div className="section-heading"><h3>Community Center</h3><span className="small">{complete} / 30 bundles</span></div><Progress value={complete/30*100} className="progress" aria-label={`${complete} of 30 standard bundles completed`}/><button className="btn quiet compact gap-top" onClick={()=>setTab('Collection')}>Open collection</button></section></aside></div>
 {run.history.length>0&&<details className="gap-top small"><summary>{Math.min(3,run.history.length)} recent plan changes</summary><ul>{run.history.slice(0,3).map((x,i)=><li key={i}>{x}</li>)}</ul></details>}
 </TabsContent>
 <TabsContent value="Plan"><PlanView run={run} update={update} selected={selected} setSelected={setSelected} view={calendarView} setView={setCalendarView}/></TabsContent>
 <TabsContent value="Collection"><CollectionView run={run} update={update}/></TabsContent>
 <TabsContent value="More"><MoreView run={run} update={update} onImport={()=>setImportOpen(true)} onExport={exportFarm} onMessage={setMessage} onError={setError} onReload={loadFarm} onSetup={openSetup}/></TabsContent>
 </>}
 </Tabs></main><footer className="footer"><span>Unofficial fan companion · Stardew Valley © ConcernedApe</span><span>Game data & sprites: <a href="https://stardewvalleywiki.com/" target="_blank" rel="noreferrer">Stardew Valley Wiki</a> · 1.6 planning · <button onClick={()=>setTab('More')} style={{textDecoration:'underline'}}>Sources & scope</button></span></footer>
 {importOpen&&<SaveImportDialog base={run} onClose={()=>{setImportOpen(false);if(setupFirstRun)setSetupOpen(true)}} onApply={imported=>{update(imported.run);setSelected(imported.run.date);setCalendarView(imported.run.date);setMessage(imported.summary);setTab('Play');markSetupSeen();setSetupOpen(false);setSetupFirstRun(false);setImportOpen(false)}}/>}
 {setupOpen&&<OnboardingDialog open={setupOpen} firstRun={setupFirstRun} base={run} onComplete={completeSetup} onSkip={skipSetup} onImport={()=>{setSetupOpen(false);setImportOpen(true)}}/>}
 <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="farm-dialog"><DialogTitle translate={detail?.category==='Personal'?'no':undefined}>{detail?.name}</DialogTitle><DialogDescription>{detail?.detail}</DialogDescription>{detail&&<><div className="description"><Sprite name={detail.entity} size={64}/><h3>Why today?</h3><p>{detail.why}</p><h3>If you skip it</h3><p>{detail.skip}</p><p className="small muted">Checking a task records completion. Update actual gold, inventory and harvests separately.</p></div><div className="button-group"><button className="btn primary" onClick={()=>{toggleTask(detail);setDetail(null)}}><CheckIcon size={16}/>{run.done.includes(detail.id)?'Mark incomplete':'Mark complete'}</button><a className="btn" href={wiki(detail.entity==='Calendar'?'Festivals':detail.entity)} target="_blank" rel="noreferrer">Wiki details</a></div></>}</DialogContent></Dialog>
 <Dialog open={checkin} onOpenChange={setCheckin}><DialogContent className="farm-dialog"><DialogTitle>How’s the farm doing?</DialogTitle><DialogDescription>Update what changed in your game. Your plan adjusts immediately.</DialogDescription><div className="form-grid"><NumberField label="Gold" value={run.gold} onChange={gold=>update({...run,gold})}/><NumberField label="Deepest mine floor" value={run.mineFloor} max={120} onChange={mineFloor=>update({...run,mineFloor})}/><Choice label="Weather today" value={run.weather} options={['Unknown','Sunny','Rain','Storm','Snow']} onChange={weather=>update({...run,weather:weather as RunState['weather']},`Weather updated to ${weather}. Plan recalculated.`)}/><Choice label="TV forecast: tomorrow" value={run.tomorrow} options={['Unknown','Sunny','Rain','Storm','Snow']} onChange={tomorrow=>update({...run,tomorrow:tomorrow as RunState['tomorrow']},`Tomorrow’s forecast: ${tomorrow}.`)}/></div><button className="btn primary" onClick={()=>setCheckin(false)}>Back to today</button></DialogContent></Dialog>
 </div>);
}
