'use client';
/* eslint-disable @next/next/no-img-element -- Local pixel sprites must retain their original nearest-neighbor rendering. */
import {useLocale} from './locale-provider';
import {useId,useState} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import assets from '@/lib/game/assets-source.json';
import {MaterialSymbol,QualitySymbol,symbolizeText} from './item-symbols';
const registry=assets as Record<string,{local_path:string}>;
const plannerRemoteSprites:Record<string,string>={Coffee:'coffee','Green Tea':'green-tea',Mead:'mead',Vinegar:'vinegar',Beer:'beer','Pale Ale':'pale-ale',Juice:'juice',Mayonnaise:'mayonnaise','Smoked Fish':'smoked-fish','Dried Fruit':'dried-fruit','Dried Mushrooms':'dried-mushrooms',Raisins:'raisins',Oil:'oil',Pickles:'pickles','Aged Roe':'aged-roe'};
export function Sprite({name,size=48}:{name:string;size?:number}){const[failed,setFailed]=useState(false);const exact=registry[name+' Icon']??registry[name];const fallback=registry['Bundle Green'];const remote=plannerRemoteSprites[name];const src=exact?.local_path??(remote?'/api/planner-sprite/'+remote:fallback?.local_path??'');return src&&!failed?<img className="sprite" src={src} alt="" width={size} height={size} loading="lazy" onError={()=>setFailed(true)}/>:<span className="sprite-fallback" aria-hidden="true" style={{width:size,height:size}}>?</span>}

export function GoldAmount({value,className=''}:{value:number;className?:string}){const {locale}=useLocale();return <span className={`gold-amount ${className}`.trim()}><span>{Math.round(value).toLocaleString('en-US')}</span><MaterialSymbol name="Gold" locale={locale}/></span>}
export function RichText({text}:{text:string}){const {locale,t}=useLocale();const normalized=text.replace(/\bper seed\b/gi,'/seed');const parts=normalized.split(/(\d[\d,]*g\b)/g);return <>{parts.map((part,i)=>{const match=part.match(/^(\d[\d,]*)g$/);return match?<GoldAmount key={i} value={Number(match[1].replaceAll(',',''))}/>:<span key={i}>{symbolizeText(t(part),locale)}</span>})}</>}
export function Choice({label,value,options,onChange,spriteForOption}:{label:string;value:string;options:readonly string[];onChange:(value:string)=>void;spriteForOption?:(option:string)=>string|undefined}){const id=useId();const {render,locale}=useLocale();const selectedSprite=spriteForOption?.(value);return render( <div className="field"><label htmlFor={id}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger id={id} className="choice">{selectedSprite&&<Sprite name={selectedSprite} size={24}/>}<SelectValue>{value}</SelectValue></SelectTrigger><SelectContent className="choice-menu">{options.map(option=>{const optionSprite=spriteForOption?.(option);return <SelectItem key={option} value={option}>{optionSprite&&<Sprite name={optionSprite} size={24}/>} {label==='Quality'&&['Normal','Silver','Gold','Iridium'].includes(option)?<QualitySymbol quality={option as 'Normal'|'Silver'|'Gold'|'Iridium'} locale={locale}/>:option}</SelectItem>})}</SelectContent></Select></div>)}
export function Check({label,checked,onChange,translateLabel=true}:{label:string;checked:boolean;translateLabel?:boolean;onChange:(checked:boolean)=>void}){const id=useId();const {render}=useLocale();return render( <label translate={translateLabel?undefined:"no"} className="check-label" htmlFor={id}><Checkbox id={id} className="farm-check" checked={checked} onCheckedChange={value=>onChange(value===true)}/>{label}</label>)}
export function NumberField({label,value,onChange,min=0,max=999999999}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number}){const {render}=useLocale();return render(<label className="field">{label}<input type="number" inputMode="numeric" min={min} max={max} value={value} onChange={e=>{const v=Number(e.target.value);if(Number.isFinite(v))onChange(Math.min(max,Math.max(min,Math.trunc(v))))}}/></label>)}
