'use client';
/* eslint-disable @next/next/no-img-element -- The interactive base map is the canonical Ginger Island map from the Stardew Valley Wiki, with an offline-styled fallback behind it. */
import {useMemo,useState} from 'react';
import type {RunState} from '@/lib/game/state';
import type {UpdateRun} from './farm-journal';
import {ISLAND_HOTSPOTS,ISLAND_REGIONS,TOTAL_GOLDEN_WALNUTS,WALNUT_ACTIVITIES,type IslandRegion} from '@/lib/game/ginger-island';
import {dateLabel} from '@/lib/game/planner';

const MAP_URL='https://stardewvalleywiki.com/mediawiki/images/4/47/Ginger_Island_Map.png';

export default function GingerIslandView({run,update}:{run:RunState;update:UpdateRun}){
 const[region,setRegion]=useState<(typeof ISLAND_REGIONS)[number]>('All');const[search,setSearch]=useState('');const[selectedHotspot,setSelectedHotspot]=useState<string|null>('farm');const[zoom,setZoom]=useState(1);const[mapFailed,setMapFailed]=useState(false);
 const progress=run.islandProgress.walnuts;const found=WALNUT_ACTIVITIES.reduce((sum,item)=>sum+Math.min(item.max,progress[item.id]??0),0);
 const activities=useMemo(()=>WALNUT_ACTIVITIES.filter(item=>(region==='All'||item.region===region)&&(!search.trim()||`${item.name} ${item.hint} ${item.region}`.toLowerCase().includes(search.toLowerCase()))&&(!run.islandProgress.hideCompleted||(progress[item.id]??0)<item.max)),[region,search,run.islandProgress.hideCompleted,progress]);
 const selected=ISLAND_HOTSPOTS.find(h=>h.id===selectedHotspot);
 const setCount=(id:string,max:number,value:number)=>update({...run,islandProgress:{...run.islandProgress,walnuts:{...progress,[id]:Math.max(0,Math.min(max,value))}}});
 const pin=(name:string)=>update({...run,notes:[...run.notes,{id:crypto.randomUUID(),label:`Ginger Island: ${name}`,date:run.date,done:false}]},`Pinned ${name} for ${dateLabel(run.date)}.`);
 const focus=(id:string,hotspotRegion:IslandRegion)=>{setSelectedHotspot(id);setRegion(hotspotRegion)};
 return <div className="island-page" translate="no">
  <div className="island-head"><div><p className="eyebrow">Late-game field guide</p><h2>Ginger Island</h2><p className="muted">Use the island itself as your checklist. Click a location, track walnuts as you find them, and pin anything you want to remember today.</p></div><div className="walnut-meter"><strong>{found}<span>/{TOTAL_GOLDEN_WALNUTS}</span></strong><div><b>Golden Walnuts</b><small>{TOTAL_GOLDEN_WALNUTS-found} left</small></div></div></div>
  {!run.unlocks.includes('Island')&&<div className="notice island-lock"><strong>Not marked unlocked yet.</strong><span>You can still browse the map, but Pelican Planner will not assume Ginger Island activities belong in your daily plan until your save marks the Island unlock.</span></div>}
  <div className="island-map-layout">
   <section className="ginger-map-shell" aria-label="Interactive Ginger Island map">
    <div className="ginger-map-toolbar"><div className="island-region-chips">{ISLAND_REGIONS.map(r=><button key={r} className={`btn compact ${region===r?'selected':''}`} onClick={()=>setRegion(r)}>{r}</button>)}</div><div className="map-zoom"><button className="btn quiet compact" onClick={()=>setZoom(z=>Math.max(1,z-.2))} aria-label="Zoom map out">−</button><span>{Math.round(zoom*100)}%</span><button className="btn quiet compact" onClick={()=>setZoom(z=>Math.min(1.8,z+.2))} aria-label="Zoom map in">+</button></div></div>
    <div className="ginger-map-viewport"><div className="ginger-map-stage" style={{width:`${zoom*100}%`,height:`${zoom*100}%`}}><div className="ginger-map-fallback" aria-hidden="true"><span className="island-mass north"/><span className="island-mass west"/><span className="island-mass east"/><span className="island-mass south"/></div>{!mapFailed&&<img className="ginger-map-image" src={MAP_URL} alt="Ginger Island map" onError={()=>setMapFailed(true)}/>} {ISLAND_HOTSPOTS.map(h=>{const tooltipId=`ginger-hotspot-${h.id}`;return <button key={h.id} className={`island-hotspot ${selectedHotspot===h.id?'active':''} ${region!=='All'&&region!==h.region?'muted-pin':''}`} style={{left:`${h.x}%`,top:`${h.y}%`}} onClick={()=>focus(h.id,h.region)} aria-label={`${h.name}: ${h.subtitle}`} aria-describedby={tooltipId}><span className="hotspot-dot"/><span id={tooltipId} role="tooltip" className="hotspot-tooltip"><strong>{h.name}</strong><small>{h.subtitle}</small></span></button>})}</div></div>
    <div className="map-location-strip">{ISLAND_HOTSPOTS.filter(h=>region==='All'||h.region===region).map(h=><button key={h.id} className={selectedHotspot===h.id?'active':''} onClick={()=>focus(h.id,h.region)}><strong>{h.name}</strong><span>{h.subtitle}</span></button>)}</div>
    {mapFailed&&<p className="label-note map-fallback-note">The wiki map image could not load. Interactive locations and walnut tracking still work from the built-in island layout.</p>}
   </section>
   <aside className="paper island-location-card">{selected?<><p className="eyebrow">{selected.region}</p><h3>{selected.name}</h3><p>{selected.subtitle}</p><p className="small muted">Showing checklist items for {selected.region}. Use the region buttons or search to narrow things further.</p><button className="btn primary compact" onClick={()=>pin(selected.name)}>Pin to today</button></>:<p>Select a point on the map.</p>}<hr/><div className="island-mini-progress"><span>Island progress</span><strong>{Math.round(found/TOTAL_GOLDEN_WALNUTS*100)}%</strong></div><div className="island-progress-track"><span style={{width:`${found/TOTAL_GOLDEN_WALNUTS*100}%`}}/></div><p className="small muted">Qi’s Walnut Room opens at 100 on the game’s walnut counter. Pelican Planner has {found} tracked here, so use the in-game counter as the final check.</p></aside>
  </div>
  <section className="paper walnut-checklist"><div className="section-heading"><div><p className="eyebrow">Walnut tracker</p><h2>{region==='All'?'All island regions':region}</h2></div><div className="island-check-controls"><label className="search-field">Search<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Volcano, fishing, puzzle…"/></label><label className="check-label"><input type="checkbox" checked={run.islandProgress.hideCompleted} onChange={e=>update({...run,islandProgress:{...run.islandProgress,hideCompleted:e.target.checked}})}/>Hide completed</label><label className="check-label"><input type="checkbox" checked={run.islandProgress.revealPuzzles} onChange={e=>update({...run,islandProgress:{...run.islandProgress,revealPuzzles:e.target.checked}})}/>Reveal puzzle hints</label></div></div>
   <div className="walnut-grid">{activities.map(item=>{const count=Math.min(item.max,progress[item.id]??0);const done=count>=item.max;return <article className={`walnut-row ${done?'is-complete':''}`} key={item.id}><div className="walnut-icon" aria-hidden="true">●</div><div className="walnut-copy"><div><strong>{item.name}</strong><span>{item.region}</span></div><p className="small muted">{item.puzzle&&!run.islandProgress.revealPuzzles?'Puzzle hint hidden. Turn on “Reveal puzzle hints” when you want it.':item.hint}</p></div><div className="walnut-actions">{item.max===1?<button className={`btn compact ${done?'selected':''}`} onClick={()=>setCount(item.id,item.max,done?0:1)}>{done?'Found ✓':'Mark found'}</button>:<div className="walnut-stepper"><button className="btn quiet compact" onClick={()=>setCount(item.id,item.max,count-1)} aria-label={`Decrease ${item.name}`}>−</button><strong>{count}/{item.max}</strong><button className="btn quiet compact" onClick={()=>setCount(item.id,item.max,count+1)} aria-label={`Increase ${item.name}`}>+</button></div>}<button className="btn quiet compact" onClick={()=>pin(item.name)}>Pin</button></div></article>})}</div>{!activities.length&&<p className="empty-note">Everything in this view is complete, or nothing matches your search.</p>}
  </section>
 </div>
}
