'use client';
import {useLocale} from './locale-provider';
import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Choice,Sprite,NumberField,Check} from './farm-ui';
import FarmCalendar from './farm-calendar';
import ExistingCropForm from './existing-crop-form';
import {InfoTip,CropTip} from './item-tooltip';
import type {UpdateRun} from './farm-journal';
import type {RunState,GameDate} from '@/lib/game/state';
import {crops,purchaseOptions,wiki} from '@/lib/game/data';
import {absoluteDay,addPlot,available,plantingOptions,plantingCapacity,dateLabel,eventsOn,fromDay,gold,makePlan,plotAlive,plotCrop,recordHarvest} from '@/lib/game/planner';
export default function PlanView({run,update,selected,setSelected,view,setView}:{run:RunState;update:UpdateRun;selected:GameDate;setSelected:(date:GameDate)=>void;view:GameDate;setView:(date:GameDate)=>void}){
 const {render,locale}=useLocale();
 const[section,setSection]=useState('Calendar');const[cropName,setCropName]=useState('Parsnip');const[quantity,setQuantity]=useState(10);const[tiles,setTiles]=useState(20);const[includeCost,setIncludeCost]=useState(false);const[feedback,setFeedback]=useState('');const[note,setNote]=useState('');const[purchaseA,setPurchaseA]=useState(purchaseOptions[0].name);const[purchaseB,setPurchaseB]=useState(purchaseOptions[3].name);
 const selectedEvents=eventsOn(run,selected);const selectedPlots=run.plots.filter(p=>p.nextHarvest===absoluteDay(selected));
 const liveCrops=crops.filter(c=>c.seasons.includes(run.date.season));
 const capacity=plantingCapacity(run,tiles);
 const options=plantingOptions(run,tiles);
 const firstHarvests=run.plots.map(p=>({p,c:plotCrop(p)})).filter(x=>x.c&&x.p.nextHarvest>=absoluteDay(run.date)&&plotAlive(x.p,fromDay(x.p.nextHarvest))).sort((a,b)=>a.p.nextHarvest-b.p.nextHarvest);
 const plant=()=>{try{const chosen=crops.find(c=>c.name===cropName);if(!chosen)throw new Error('Choose a crop.');const cost=chosen.seed*quantity;if(includeCost&&cost>available(run,'Gold'))throw new Error('This purchase would spend reserved gold. Reduce the quantity or review your reserves.');const plot=addPlot(run,cropName,quantity);update({...run,gold:run.gold-(includeCost?cost:0),plots:[...run.plots,plot]},`Recorded ${quantity} ${cropName} planted on ${dateLabel(run.date)}.`);setFeedback('Planting recorded. Adjust for any missed watering days below.');}catch(e){setFeedback(e instanceof Error?e.message:'Could not record planting.')}};
 const reservePurchase=(name:string)=>{const purchase=purchaseOptions.find(p=>p.name===name);if(!purchase)return;const resources=[['Gold',purchase.gold],...Object.entries(purchase.resources)] as [string,number][];if(run.reservations.some(r=>r.name===name)){setFeedback('This purchase already has reserved resources.');return;}if(resources.some(([r,q])=>available(run,r)<q)){setFeedback('You do not have enough unreserved resources for this purchase.');return;}update({...run,reservations:[...run.reservations,...resources.map(([resource,quantity])=>({id:crypto.randomUUID(),name,resource,quantity}))]},`Reserved resources for ${name}.`);setFeedback(`Resources reserved for ${name}. Gold has not been spent.`)};
 return render(<><div className="page-title"><p className="eyebrow">Room for the whole season</p><h1>Plan ahead</h1></div><Tabs value={section} onValueChange={setSection}><TabsList className="plan-subnav" variant="line">{['Calendar','Crops','Compare'].map(s=><TabsTrigger key={s} value={s} className="btn">{s}</TabsTrigger>)}</TabsList>
 {feedback&&<div className="preview-note" role="status">{feedback} <button className="btn quiet compact" onClick={()=>setFeedback('')}>Dismiss</button></div>}
 <TabsContent value="Calendar"><div className="section-heading"><p className="muted small">Your game date: {dateLabel(run.date)}</p><button className="btn compact" onClick={()=>{setSelected(run.date);setView(run.date)}}>Jump to today</button></div><div className="split"><FarmCalendar run={run} view={view} selected={selected} onView={setView} onSelect={setSelected} large/><section className="day-detail"><p className="eyebrow">{absoluteDay(selected)===absoluteDay(run.date)?'Today':'Looking ahead'}</p><h2>{dateLabel(selected)}</h2><ul className="detail-list">{selectedEvents.map((e,i)=><li key={i}><Sprite name={e.type==='birthday'?e.name:'Calendar'} size={38}/><div><strong>{e.name}{e.type==='birthday'?'’s birthday':''}</strong><p className="small muted">{e.requires&&!run.unlocks.includes(e.requires)?`Requires ${e.requires} unlock`:e.type==='birthday'?'Check preferred gifts before giving.':e.type==='festival'?'Check the Wiki for entry times and location.':'Check the bushes during the season.'}</p><a className="small" href={wiki(e.name)} target="_blank" rel="noreferrer">Details</a></div></li>)}{selectedPlots.map(p=><li key={p.id}><Sprite name={p.crop} size={38}/><div><strong>{p.quantity} {p.crop} ready</strong><p className="small muted">Assumes daily watering.</p></div></li>)}</ul>{!selectedEvents.length&&!selectedPlots.length&&<p className="empty-note">No scheduled events or recorded harvests.</p>}<h3>Pin a task</h3><form className="inline-form gap-top" onSubmit={e=>{e.preventDefault();if(!note.trim())return;update({...run,notes:[...run.notes,{id:crypto.randomUUID(),label:note.trim(),date:selected,done:false}]},`Pinned a task for ${dateLabel(selected)}.`);setNote('')}}><label className="field">Task<input value={note} onChange={e=>setNote(e.target.value)} maxLength={160} placeholder="Upgrade watering can" required/></label><button className="btn" type="submit">Pin</button></form>{run.notes.filter(n=>absoluteDay(n.date)===absoluteDay(selected)).map(n=><div className="ledger-row" key={n.id}><span translate="no"><Check translateLabel={false} label={n.label} checked={n.done} onChange={done=>update({...run,notes:run.notes.map(x=>x.id===n.id?{...x,done}:x)})}/></span><button className="btn quiet compact" onClick={()=>update({...run,notes:run.notes.filter(x=>x.id!==n.id)})}>Remove</button></div>)}{absoluteDay(selected)!==absoluteDay(run.date)&&<p className="label-note gap-top">Browsing dates does not advance your farm.</p>}</section></div><section className="gap-top"><h2>Next on the farm</h2><div className="outlook">{makePlan(run).filter(t=>!run.done.includes(t.id)).slice(0,3).map(t=><div className="outlook-day" key={t.id}><Sprite name={t.entity} size={38}/><h3 translate={t.category==='Personal'?'no':undefined}>{t.name}</h3><p>{t.detail}</p></div>)}</div></section></TabsContent>
 <TabsContent value="Crops"><div className="split"><section className="paper"><div className="section-heading"><h2>Your fields</h2><span className="small muted">{run.plots.reduce((a,p)=>a+p.quantity,0)} planted tiles</span></div>{run.plots.length?run.plots.map(p=>{const day=absoluteDay(run.date);const alive=plotAlive(p,run.date);const ready=alive&&day>=p.nextHarvest;const total=Math.max(1,p.nextHarvest-absoluteDay(p.planted));const progress=Math.max(0,Math.min(100,(day-absoluteDay(p.planted))/total*100));return <div className="plot-row" key={p.id}><CropTip crop={plotCrop(p)} plot={p} date={run.date} trigger={<Sprite name={p.crop}/>}/><div className="grow"><strong><span translate={p.customCrop?"no":undefined}>{p.crop}</span> ×{p.quantity}</strong><p className="small muted">{!alive?'Out of season · remove or review':ready?'Ready to harvest':`Ready ${dateLabel(fromDay(p.nextHarvest))}`}</p><Progress className="progress" value={progress} aria-label={`${p.crop} estimated growth ${Math.round(progress)} percent`}/></div><div className="button-group">{ready&&<button data-cozy-effect="harvest" className="btn primary compact" onClick={()=>{update(recordHarvest(run,p.id),`Harvested ${p.quantity} ${p.crop}.`);setFeedback('Added the minimum normal-quality harvest to inventory. Edit quantities and quality in Collection to match your game.')}}>Harvest</button>}<button className="btn compact" disabled={!alive||!!ready} onClick={()=>update({...run,plots:run.plots.map(x=>x.id===p.id?{...x,nextHarvest:x.nextHarvest+1,missedDays:x.missedDays+1}:x)},`${p.crop} harvest delayed by one missed watering day.`)}>Missed water</button><button className="btn quiet compact" onClick={()=>update({...run,plots:run.plots.filter(x=>x.id!==p.id)})}>Remove</button></div></div>}):<p className="empty-note">Record what you plant. Harvest dates will appear on your calendar.</p>}
 <ExistingCropForm run={run} onAdd={plot=>{update({...run,plots:[...run.plots,plot]});setFeedback('Existing crop added. Your calendar and forecasts are updated.')}}/><div className="split-rule"/><h3>Record today’s planting <InfoTip label="Planting assumptions" text="Standard growth only. For crops already growing or with growth bonuses, use Add an existing crop and enter the remaining days. Recording a planting only subtracts gold if you enable that option." chinese="默认使用标准生长周期。补录在种作物或加速生长的作物时，请使用“添加已种植作物”并填写剩余天数。仅在勾选扣费选项时扣除金币。"/></h3>{liveCrops.length?<><div className="form-grid gap-top"><Choice label="Crop" value={liveCrops.some(c=>c.name===cropName)?cropName:''} options={liveCrops.map(c=>c.name)} onChange={setCropName}/><NumberField label="Tiles planted" value={quantity} min={1} max={9999} onChange={setQuantity}/></div><div className="gap-top"><Check label="Subtract seed cost from my gold" checked={includeCost} onChange={setIncludeCost}/></div><button className="btn primary gap-top" onClick={plant}>Record planting</button></>:<p className="empty-note">For winter, indoor or other crops, use Add an existing crop and enter the remaining growth time.</p>}</section>
 <section className="day-detail"><h2>Harvest forecast <InfoTip label="About the harvest forecast" text="Potential sales use minimum yield and normal quality. These crops are not cash yet. Keep bundle items before selling." chinese="预计售价按最低产量和普通品质计算，尚未计入可用金币。出售前请预留收集包所需物品。"/></h2><ul className="forecast-list">{firstHarvests.map(({p,c})=><li key={p.id}><span>{fromDay(p.nextHarvest).season} {fromDay(p.nextHarvest).day}<span className="mini-label">{p.quantity} {p.crop}</span></span><strong>{gold(p.quantity*c!.yield*Math.floor(c!.sell*(run.tiller?1.1:1)))}</strong></li>)}</ul>{!firstHarvests.length&&<p className="empty-note">Plantings will appear here.</p>}</section></div>
 <section className="gap-top"><div className="section-heading"><div><h2>{run.date.season} crop ledger</h2><p className="small muted">Planting on day {run.date.day} · harvest through day 28</p></div><div style={{width:120}}><NumberField label="Total outdoor crop tiles" value={tiles} min={1} max={9999} onChange={setTiles}/></div></div><div className="capacity-strip"><span translate="no">{locale==='zh-CN'?`${capacity.occupied} 块已种植 · ${capacity.free} 块空地`:`${capacity.occupied} occupied · ${capacity.free} free tiles`}</span><InfoTip label="Available planting space" text="Set your total outdoor crop space above. Existing outdoor crops occupy tiles; greenhouse and island crops do not. Suggestions use only free tiles and current unreserved gold. Expected harvest sales are not spendable yet. Each option is an alternative, not a combined shopping list." chinese="在上方填写室外种植地块总数。现有室外作物占用地块，温室和姜岛作物不占用。推荐仅使用空地和当前未预留的金币，预计收获收入不计入可用预算。各方案是替代选项，不是合并的购物清单。"/></div><div className="crop-compare">{options.map(({crop:c,result:e,quantity:q})=><article className="crop-option" key={c.name}><h3><CropTip crop={c} trigger={<Sprite name={c.name}/>}/><span>{c.name}</span></h3><p className="profit-value">{!q?'No free tiles or seed budget':e.harvests?gold(e.profit):'Too late'}</p><p className="label-note">{e.harvests?'net by season end':'No harvest before day 28'}</p><div className="crop-quick-stats"><span>{q} {locale==='zh-CN'?'块地':'tiles'}</span><span>{e.harvests} {locale==='zh-CN'?'次收获':'harvests'}</span></div><InfoTip label="Calculation details" text={`Total seed cost: ${gold(e.cost)}. Gross sales: ${gold(e.revenue)}. Net profit: ${gold(e.profit)}. Includes seed purchases for repeat plantings. Assumes normal quality, daily watering, minimum yield and immediate replanting. Fertilizer, random yields, processing and shop availability are excluded.`} chinese={`种子总成本：${gold(e.cost)}。总销售额：${gold(e.revenue)}。净利润：${gold(e.profit)}。包含重复种植的种子费用。假设普通品质、每天浇水、最低产量且收获后立即补种。不计肥料、随机额外产量、加工和商店营业情况。`}/> <a className="small" href={wiki(c.name)} target="_blank" rel="noreferrer">Source</a></article>)}</div></section></TabsContent>
 <TabsContent value="Compare"><div className="page-title"><h2>One purchase, two possibilities</h2><p>Compare the immediate cost against your actual unreserved resources.</p></div><div className="form-grid"><Choice label="Option A" value={purchaseA} options={purchaseOptions.map(p=>p.name)} onChange={setPurchaseA}/><Choice label="Option B" value={purchaseB} options={purchaseOptions.map(p=>p.name)} onChange={setPurchaseB}/></div><div className="split gap-top">{[purchaseA,purchaseB].map((name,i)=>{const p=purchaseOptions.find(p=>p.name===name)!;const resources=[['Gold',p.gold],...Object.entries(p.resources)] as [string,number][];const enough=resources.every(([r,q])=>available(run,r)>=q);return <section className="paper" key={i}><h2>{p.name}</h2><p className="profit-value">{gold(p.gold)}</p><p className="small">{p.benefit}</p><div className="gap-top">{resources.map(([resource,count])=><div className="ledger-row" key={resource}><span>{resource}</span><strong className={available(run,resource)<count?'danger-text':''}>{available(run,resource).toLocaleString('en-US')} / {count.toLocaleString('en-US')}</strong></div>)}</div><p className="tool-note">{enough?`${gold(available(run,'Gold')-p.gold)} would remain unreserved.`:'Gather the missing resources or release a reservation first.'}</p><button className="btn primary" disabled={!enough||run.reservations.some(r=>r.name===p.name)} onClick={()=>reservePurchase(p.name)}>{run.reservations.some(r=>r.name===p.name)?'Resources reserved':'Reserve resources'}</button></section>})}</div><section className="gap-top"><h2>Resource reservations <InfoTip label="How reservations work" text="Reserving does not buy an upgrade. Confirm your current tool tier, building space and shop availability in-game. This comparison does not predict income from animals or future earnings." chinese="预留资源并不会购买升级。请在游戏中确认工具等级、建筑空间和商店营业情况。比较不预测动物收入或未来收益。"/></h2>{run.reservations.length?Array.from(new Set(run.reservations.map(r=>r.name))).map(name=><div className="ledger-row" key={name}><div><strong translate={purchaseOptions.some(p=>p.name===name)?undefined:"no"}>{name}</strong><p className="small muted">{run.reservations.filter(r=>r.name===name).map(r=>`${r.quantity.toLocaleString('en-US')} ${r.resource}`).join(' · ')}</p></div><button className="btn compact" onClick={()=>update({...run,reservations:run.reservations.filter(r=>r.name!==name)},`Released reservation for ${name}.`)}>Release</button></div>):<p className="empty-note">No purchase reservations. Your minimum gold reserve is managed in More.</p>}</section></TabsContent>
 </Tabs></>);
}
