'use client';
import {useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useLocale} from './locale-provider';
import {importSave} from '@/lib/game/import-save';
import {absoluteDay,dateLabel,bundleDone} from '@/lib/game/planner';
import {bundles} from '@/lib/game/data';
import type {RunState} from '@/lib/game/state';

type Imported=ReturnType<typeof importSave>;
export default function SaveImportDialog({base,onClose,onApply,mode='game'}:{mode?:'game'|'journal';base:RunState;onClose:()=>void;onApply:(data:Imported)=>void}){
 const {locale,t}=useLocale();const zh=locale==='zh-CN';const journal=mode==='journal';
 const say=(en:string,cn:string)=>zh?cn:en;
 const [platform,setPlatform]=useState('Windows');const [preview,setPreview]=useState<Imported|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const request=useRef(0);
 const path=platform==='Windows'?'%APPDATA%\\StardewValley\\Saves':'~/.config/StardewValley/Saves';
 async function read(file?:File){if(!file)return;const id=++request.current;setBusy(true);setPreview(null);setError('');try{if(file.size>20000000)throw new Error('Choose a save smaller than 20 MB.');const text=await file.text();if(journal&&!text.trim().startsWith('{'))throw new Error('Choose a journal JSON backup. Game saves can be imported with Import save.');const result=importSave(text,base);if(id===request.current)setPreview(result);}catch(e){if(id===request.current)setError(e instanceof Error&&e.name!=='ZodError'?e.message:'The imported farm data is invalid. Check the file and try again.');}finally{if(id===request.current)setBusy(false);}}
 return <Dialog open onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="farm-dialog setup-dialog" translate="no"><DialogTitle>{journal?say('Welcome back, farmer','欢迎回来，农夫'):say('Bring your farm into the journal','将农场存档导入日记')}</DialogTitle><DialogDescription>{journal?say('Choose the journal backup you downloaded on your other computer. Nothing changes until you restore the preview.','选择你在另一台电脑上下载的日记备份。确认预览并恢复之前，当前日记不会改变。'):say('Import the host’s PC save to fill in your date, gold, progress and supported growing crops. Review the result before applying it.','导入主机玩家的电脑存档，自动读取日期、金币、进度和支持的在种作物。确认预览后再应用。')}</DialogDescription>
 {!journal&&<details open={!preview}><summary>{say('Where is my save file?','如何找到存档？')}</summary><div className="gap-top"><label className="field">{say('Your computer','电脑系统')}<select value={platform} onChange={e=>setPlatform(e.target.value)}>{['Windows','macOS','Linux / Steam Deck'].map(x=><option key={x}>{x}</option>)}</select></label><ol className="save-instructions"><li>{say('Save your game by sleeping, then close it.','在游戏中睡觉保存进度，然后退出。')}</li><li>{platform==='Windows'?say('Press Windows + R, paste this path, and press Enter.','按 Windows + R，粘贴以下路径，按回车。'):platform==='macOS'?say('In Finder, press Command + Shift + G and paste this path.','在访达中按 Command + Shift + G，粘贴以下路径。'):say('Open your file manager (Desktop Mode on Steam Deck), press Ctrl + L, and paste this path.','打开文件管理器（Steam Deck 请进入桌面模式），按 Ctrl + L 并粘贴路径。')}<code className="save-path">{path}</code></li><li>{say('Open the folder named after your farmer, such as Joe_123456789. Select the file inside with exactly the same name and no extension.','打开以农夫名字命名的文件夹，例如 Joe_123456789。选择其中同名且无扩展名的文件。')}</li><li>{say('Choose that file below. Do not select SaveGameInfo, an _old backup, a folder or a ZIP.','在下方选择该文件。不要选择 SaveGameInfo、以 _old 结尾的备份、文件夹或 ZIP。')}</li></ol>{platform==='Linux / Steam Deck'&&<p className="small">{say('Steam Flatpak may use:','Steam Flatpak 版本可能使用：')}<code className="save-path">~/.var/app/com.valvesoftware.Steam/.config/StardewValley/Saves</code>{say('For Proton installations, check the Windows Saves folder under Steam’s steamapps/compatdata/413150/pfx/drive_c/users/steamuser/AppData/Roaming/StardewValley.','Proton 安装请在 Steam 的 steamapps/compatdata/413150/pfx/drive_c/users/steamuser/AppData/Roaming/StardewValley 下查找 Saves 文件夹。')}</p>}<p className="small"><a href="https://www.stardewvalley.net/missing-corrupt-save-file-troubleshooting-guide/" target="_blank" rel="noreferrer">{say('Official save-file guide','官方存档指南')}</a></p></div></details>}
 <label className="field gap-top">{journal?say('Choose journal backup (20 MB maximum)','选择日记备份（最大 20 MB）'):say('Choose game save or journal JSON backup (20 MB maximum)','选择游戏存档或日记 JSON 备份（最大 20 MB）')}<input type="file" accept={journal?'.json,application/json':undefined} disabled={busy} onChange={e=>{void read(e.target.files?.[0]);e.target.value=''}}/></label>
 <p className="small muted">{journal?say('Restoring replaces this tab’s journal and any preferences in the backup. Download your current journal first if you want to keep both. Choose Save farm afterward to keep it on this computer.','恢复会替换当前日记及备份中包含的偏好设置。如需保留两份日记，请先下载当前日记。恢复后，点击“保存农场”将日记保存在这台电脑上。'):say('The game file is read in your browser and never modified or uploaded. Applying replaces the current journal draft; Save farm stores the extracted journal data. Export your current draft first if you want to keep it.','游戏文件仅在浏览器中读取，不会被修改或上传。应用后将替换当前日记草稿；点击“保存农场”才会保存提取的数据。如需保留当前草稿，请先导出。')}</p>
 {busy&&<p role="status">{say('Reading your farm…','正在读取农场…')}</p>}{error&&<p role="alert" className="error-note">{t(error)}</p>}
 {preview&&<section className="import-preview"><h3>{say('Look what we found','预览农场')}</h3><p>{preview.run.name} · {t(dateLabel(preview.run.date))} · {preview.run.gold.toLocaleString()}g</p><p>{say('Farming level','耕种等级')} {preview.run.farming} · {say('Mine floor','矿井层数')} {preview.run.mineFloor}</p><p>{say('Growing crop tiles','在种作物地块')}：{preview.run.plots.reduce((n,p)=>n+p.quantity,0)}</p><p>{say('Chest stacks','箱子物品堆')} {preview.run.chestContents.length} · {say('Completed standard bundles','已完成的标准收集包')} {bundles.filter(bundle=>bundleDone(preview.run,bundle)).length}</p>{!preview.warnings&&<div className="backup-preview"><p>{say('Pinned notes','固定笔记')}: {preview.run.notes.length} · {say('Hidden suggestions','隐藏的建议')}: {preview.run.mutedSuggestions.length}</p>{preview.exportedAt&&<p>{say('Backup made','备份时间')}: {new Date(preview.exportedAt).toLocaleString(locale)}</p>}{preview.preferences?<p>{say('Preferences coming along','随备份恢复的设置')}: {preview.preferences.locale==='en'?say('English','英语'):say('Simplified Chinese','简体中文')} · {say('Effects','特效')} {preview.preferences.effects?say('on','开启'):say('off','关闭')} · {preview.preferences.taskLimit===99?say('Full plan','完整计划'):preview.preferences.taskLimit+' '+say('tasks','项任务')}</p>:<p>{say('Older backup: your language, effects and task-display preferences will stay as they are.','旧版备份：当前语言、特效和任务显示设置将保持不变。')}</p>}</div>}<ul className="save-instructions">{preview.run.plots.map(p=><li key={p.id}>{p.quantity} × {t(p.crop)} · {p.location??'Farm'} · {Math.max(0,p.nextHarvest-absoluteDay(preview.run.date))} {say('days until harvest','天后收获')}</li>)}</ul>{preview.warnings&&<><h4>{say('A few things to double-check','导入范围')}</h4><p>{say('Missing crops can be added in Plan → Crops → Add an existing crop.','遗漏作物可在“计划 → 作物 → 添加已种植作物”中补录。')}</p><p>{say('Backpack and chest items, common crops and completed bundle rooms come along. Partial bundle donations, animals, mods and chest locations still need a quick look. Growth assumes daily watering, so refresh after playing.','支持日记中 16 种作物，覆盖农场、温室和姜岛。箱子、动物、收集包捐赠和模组内容需另行核对。生长预测假设每天浇水，游玩后请重新导入。')}</p>{preview.warnings.slice(0,-2).map(w=><p key={w}>{zh?w.replace('crop tiles were not imported (unsupported crops, locations or growth data).','块作物未导入（不支持的作物、位置或生长数据）。').replace('dead crop tiles were excluded.','块枯死作物已排除。'):w}</p>)}</>}</section>}
 <div className="setup-actions"><button className="btn" onClick={onClose}>{say('Cancel','取消')}</button><button className="btn primary" disabled={!preview||busy} onClick={()=>preview&&onApply(preview)}>{journal?say('Restore this journal','恢复这份日记'):say('Use this farm','使用此农场')}</button></div>
 </DialogContent></Dialog>;
}
