'use client';
import type {RunState} from '@/lib/game/state';
import type {UpdateRun} from './farm-journal';
import {absoluteDay,dateLabel,deadlines,eventsOn,makePlan,makeSimplePlan,nextDate} from '@/lib/game/planner';
import {machineBatchesForDate,machineProductSpriteName,machineReadyAt} from '@/lib/game/machines';
import {festivalSprite} from '@/lib/game/data';
import {Sprite} from './farm-ui';

export default function WeekAhead({run,update}:{run:RunState;update:UpdateRun}){
 const days=Array.from({length:7},(_,offset)=>{const date=nextDate(run.date,offset);const forecast={...run,date,weather:offset===0?run.weather:offset===1?run.tomorrow:'Unknown',luck:offset===0?run.luck:'Unknown',tomorrow:offset===0?run.tomorrow:'Unknown'};const plan=run.plannerMode==='simple'?makeSimplePlan(forecast):makePlan(forecast);return {date,offset,events:eventsOn(run,date).filter(e=>e.type==='festival'||e.type==='birthday'),harvests:run.plots.filter(p=>p.nextHarvest===absoluteDay(date)),machines:machineBatchesForDate(run,date),notes:run.notes.filter(n=>!n.done&&absoluteDay(n.date)===absoluteDay(date)),deadlines:deadlines({...run,date}).filter(d=>d.day===date.day),lead:plan.find(t=>!run.done.includes(t.id))};});
 return <div className="week-ahead" translate="no"><div className="week-ahead-head"><div><p className="eyebrow">The next seven days</p><h2>Week Ahead</h2><p className="muted">Harvests, machine pickups, events, pinned tasks, and anything else coming up soon.</p></div><span className="week-range">{dateLabel(days[0].date)} → {dateLabel(days[6].date)}</span></div>
  <div className="week-grid">{days.map(({date,offset,events,harvests,machines,notes,deadlines:due,lead})=>{const count=events.length+harvests.length+machines.length+notes.length+due.length+(lead?1:0);return <article className={`week-card ${offset===0?'is-today':''}`} key={absoluteDay(date)}><header><div><span>{offset===0?'Today':offset===1?'Tomorrow':date.season+' '+date.day}</span><strong>{date.season} {date.day}</strong></div><span className="week-load" title={`${count} tracked items`}>{count}</span></header>
   <div className="week-card-body">{lead&&<div className="week-primary"><Sprite name={lead.entity} size={30}/><span>{lead.name}</span></div>}{events.slice(0,2).map(e=><p className="week-item" key={e.name}><Sprite name={e.type==='birthday'?e.name:festivalSprite(e.name)} size={20}/><span>{e.name}{e.type==='birthday'?"’s birthday":''}</span></p>)}{harvests.slice(0,2).map(p=><p className="week-item" key={p.id}><Sprite name={p.crop} size={20}/><span>{p.quantity} {p.crop} ready</span></p>)}{machines.slice(0,2).map(b=><p className="week-item" key={b.id}><Sprite name={machineProductSpriteName(b.product)} size={20}/><span>{b.quantity}× {b.product} · {machineReadyAt(b.started,b.startedTime,b.processingMinutes).time}</span></p>)}{notes.slice(0,2).map(n=><p className="week-item week-note" key={n.id}><span>✎</span><span>{n.label}</span></p>)}{due.slice(0,1).map(d=><p className="week-item week-deadline" key={d.name}><Sprite name={d.entity} size={20}/><span>{d.name}</span></p>)}{count===0&&<p className="small muted">Nothing planned.</p>}</div>
   {notes.length>0&&<button className="btn quiet compact week-done" onClick={()=>update({...run,notes:run.notes.map(n=>notes.some(today=>today.id===n.id)?{...n,done:true}:n)})}>Clear pinned tasks</button>}</article>})}</div>
  <p className="label-note">This view only looks ahead. It does not move your save forward.</p>
 </div>
}
