import {encyclopediaEntries,encyclopediaSpritePath} from './encyclopedia';
import assets from './assets-source.json';
import {giftSpriteName,universalGiftTastes,villagerProfiles} from './villager-profiles';
import {villagerHeartEvents} from './villager-heart-events';

export function buildOfflineEncyclopediaHtml(spriteData:Record<string,string>){
 const entries=encyclopediaEntries.map(entry=>({...entry,spritePath:encyclopediaSpritePath(entry)}));
 const safeJson=JSON.stringify(entries).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');
 const safeSprites=JSON.stringify(spriteData).replaceAll('<','\\u003c');
 const assetRegistry=assets as Record<string,{local_path:string}>;
 const available=new Set(Object.keys(assetRegistry));
 const allGiftNames=[...new Set([...Object.values(villagerProfiles).flatMap(profile=>[...profile.loves,...profile.likes,...profile.neutrals,...profile.dislikes,...profile.hates]),...Object.values(universalGiftTastes).flat()])];
 const giftSpritePaths=Object.fromEntries(allGiftNames.map(name=>{const spriteName=giftSpriteName(name,available);return [name,assetRegistry[spriteName]?.local_path??assetRegistry['Bundle Green']?.local_path??'']}));
 const safeProfiles=JSON.stringify(villagerProfiles).replaceAll('<','\\u003c');
 const safeUniversal=JSON.stringify(universalGiftTastes).replaceAll('<','\\u003c');
 const safeGiftSprites=JSON.stringify(giftSpritePaths).replaceAll('<','\\u003c');
 const safeHeartEvents=JSON.stringify(villagerHeartEvents).replaceAll('<','\\u003c');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pelican Planner Encyclopedia · Offline</title><style>
 @import url("https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=Alegreya+Sans:wght@400;500;600;700;800&display=swap");
 :root{--paper:#fff7db;--ink:#352713;--green:#326c36;--wood:#75411f;--gold:#f4cc6c;--soft:#deefab;--display:"Alegreya Sans","Trebuchet MS",sans-serif;--ui:"Alegreya Sans","Trebuchet MS",sans-serif;--reference:"Alegreya",Georgia,"Iowan Old Style",serif}*{box-sizing:border-box}body{margin:0;background:#dcebbb;color:var(--ink);font:17px/1.55 var(--ui)}button,input{font:inherit}button{cursor:pointer}a{color:#1c6552}.wrap{max-width:1050px;margin:auto;padding:28px 18px 60px}.hero,.panel{background:var(--paper);border:3px solid #b9762f;box-shadow:inset 0 0 0 4px #f3d89b;padding:22px}.hero{margin-bottom:18px}.top{display:flex;justify-content:space-between;gap:18px;align-items:start}.badge{display:inline-flex;align-items:center;gap:6px;background:#e2efc3;border:2px solid #6f8c51;padding:5px 9px;font-size:.9rem}.search{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:18px}.search input{min-width:0;padding:11px 12px;border:3px solid #8d6738;background:#fffdf0}.btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:42px;padding:8px 14px;border:2px solid #965b22;background:var(--gold);color:#422b13;text-decoration:none}.btn:hover{background:#ffe293}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.card{display:grid;grid-template-columns:48px minmax(0,1fr);gap:10px;align-items:center;text-align:left;background:#fff4ca;border:2px solid #b78038;padding:10px;color:inherit}.card:hover{background:#fff0ae}.card img,.heroSprite img,.inline img{image-rendering:pixelated;object-fit:contain}.card strong,.card small,.card em{display:block}.card small{color:#6e5e44}.card em{font-style:normal;color:#6a5738;font-size:.92rem;margin-top:2px}.article h1{font-family:var(--display);font-size:2.5rem;line-height:1.12;letter-spacing:-.02em;margin:.15em 0}.article p,.facts li{font-family:var(--reference)}.title{display:flex;align-items:center;gap:14px}.heroSprite{border:0;background:transparent;padding:0}.facts li{margin:8px 0}.related{display:flex;flex-wrap:wrap;gap:7px}.related .btn{background:#f9e5a5}.inline{display:inline-flex;align-items:center;gap:3px}.inline button{border:0;background:transparent;padding:0 1px;vertical-align:middle}.inline img{width:20px;height:20px}.muted{color:#6a583a}.eyebrow{text-transform:uppercase;letter-spacing:.06em;font-size:.82rem;font-weight:700;color:#63502c}.sourceRow{display:flex;flex-wrap:wrap;gap:7px}.empty{text-align:center;padding:30px}.back{margin-bottom:14px}/* Compact offline-reader guardrails */
.wrap,.hero,.panel,.top>*,.title>*{min-width:0}.hero,.panel{overflow-wrap:anywhere}.card{min-width:0;overflow:hidden}.card>span,.card strong,.card small,.card em{min-width:0;overflow-wrap:anywhere}.article{min-width:0;overflow:hidden}.article p,.facts li{overflow-wrap:anywhere}.article h1{max-width:100%;overflow-wrap:anywhere}.sourceRow .btn,.related .btn{max-width:100%;white-space:normal;overflow-wrap:anywhere;text-align:center}
@media(max-width:720px){.wrap{padding:16px 12px 42px}.hero,.panel{padding:16px}.hero{margin-bottom:12px}.top{display:block}.badge{margin-top:9px}.grid{grid-template-columns:1fr}.search{grid-template-columns:1fr;margin-top:14px}.search .btn{width:100%}.card{grid-template-columns:42px minmax(0,1fr);padding:9px}.article h1{font-size:2.05rem}.title{gap:10px}.facts ul{padding-left:21px}.sourceRow .btn{flex:1 1 180px}}
@media(max-width:420px){.wrap{padding:10px 8px 34px}.hero,.panel{padding:12px}.card{grid-template-columns:36px minmax(0,1fr);gap:8px;padding:8px}.card strong{font-size:1rem}.card small,.card em{font-size:.86rem}.article h1{font-size:1.8rem}.title{align-items:flex-start}.btn{padding:7px 10px}.empty{padding:20px 8px}}
.villagerProfile{margin-top:18px;padding-top:15px;border-top:2px dotted #cbb783}.villagerHead{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.villagerHead h2{margin:0}.quickGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:10px}.quickCard{padding:9px 10px;border:2px solid #b9a277;background:#fff5d6}.quickCard span{display:block;text-transform:uppercase;font-size:.72rem;font-weight:800;color:#765f3d}.quickCard strong,.quickCard small{display:block;overflow-wrap:anywhere}.quickCard small{margin-top:3px;color:#6c593e}.friendTip{margin-top:8px;padding:8px 10px;border-left:4px solid #7b965d;background:#e9f1d3;font-size:.9rem}.taste{margin-top:8px;padding:8px;border:2px solid #c2ad83;background:#fffaf0}.taste h4{margin:0}.tasteMeta{display:flex;justify-content:space-between;gap:8px;align-items:start;margin-bottom:6px}.tasteMeta small{display:block;color:#746148}.giftGrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:5px}.gift{min-width:0;display:grid;grid-template-columns:30px minmax(0,1fr);align-items:center;gap:6px;padding:5px 6px;border:2px solid #d1bf99;background:#fffdf5;line-height:1.15;font-size:.86rem}.gift img{image-rendering:pixelated;object-fit:contain}.gift span{min-width:0;overflow-wrap:anywhere}.universals{margin-top:10px;border:2px solid #b49b6e;background:#f7eed4}.universals summary{cursor:pointer;padding:8px 10px;font-weight:800}.universals>p,.universals>.taste{margin-left:8px;margin-right:8px}.universals>.taste:last-child{margin-bottom:8px}@media(max-width:720px){.quickGrid{grid-template-columns:1fr 1fr}.quickCard:last-child{grid-column:1/-1}}@media(max-width:480px){.quickGrid{grid-template-columns:1fr}.quickCard:last-child{grid-column:auto}.giftGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.gift{font-size:.8rem}}@media(max-width:340px){.giftGrid{grid-template-columns:1fr}}
.heartGuide{margin-top:12px;padding-top:10px;border-top:3px double #b49b6e}.heartHead{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.heartHead h3,.heartHead p{margin:0}.heartHead p{margin-top:3px}.heartHead>strong{flex:0 0 auto;display:grid;place-items:center;min-width:28px;height:25px;padding:0 6px;border:2px solid #b29a6d;background:#f6e7bd;font-size:.82rem}.heartGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(205px,1fr));gap:7px;margin-top:8px}.heartCard{min-width:0;display:grid;grid-template-columns:56px minmax(0,1fr);gap:8px;padding:8px 9px;border:2px solid #c5aa79;background:#fff7df}.heartCard>span{display:inline-flex;align-items:center;justify-content:center;min-height:28px;padding:3px 6px;border:2px solid #b67c70;background:#f7ddd6;font-weight:800;font-size:.82rem;white-space:nowrap}.heartCard p{min-width:0;margin:2px 0 0;line-height:1.25;overflow-wrap:anywhere}@media(max-width:480px){.heartGrid{grid-template-columns:1fr}.heartCard{grid-template-columns:52px minmax(0,1fr)}}
 </style></head><body><div class="wrap"><section class="hero"><div class="top"><div><div class="eyebrow">Pelican Planner reference</div><h1 style="margin:.1em 0">Encyclopedia</h1><p style="margin:0">Offline copy. Search and open the bundled entries without a network connection.</p></div><span class="badge">● Offline-ready</span></div><form class="search" id="searchForm"><input id="q" autocomplete="off" placeholder="Try Cabbage, sword, Wood, Abigail…"><button class="btn">Search</button></form></section><main class="panel" id="app"></main></div><script>
 const entries=${safeJson};const sprites=${safeSprites};const profiles=${safeProfiles};const universals=${safeUniversal};const giftSprites=${safeGiftSprites};const heartEvents=${safeHeartEvents};const app=document.getElementById('app'),q=document.getElementById('q');
 const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\\s-]+/g,' ').replace(/\\s+/g,' ').trim();const byTitle=new Map(entries.map(e=>[e.title.toLowerCase(),e]));
 const linkable=entries.filter(e=>e.spritePath&&e.title.length>2).sort((a,b)=>b.title.length-a.title.length);const terms=new Map();for(const e of linkable)for(const t of [e.title,...e.aliases])if(t.length>2&&!terms.has(t.toLowerCase()))terms.set(t.toLowerCase(),e);const esc=s=>s.replace(/[-/\\^$*+?.()|[\\]{}]/g,'\\\\$&');const pat=new RegExp('('+[...terms.keys()].sort((a,b)=>b.length-a.length).map(esc).join('|')+')','gi');
 function sprite(e,size=42){const src=sprites[e.spritePath];return src?'<img src="'+src+'" width="'+size+'" height="'+size+'" alt="">':'<span></span>'}function safe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 const wordChar=c=>!!c&&/[A-Za-z0-9]/.test(c);const whole=(text,term)=>{let i=String(text).indexOf(term);while(i!==-1){const end=i+term.length;if(!wordChar(text[i-1])&&!wordChar(text[end]))return true;i=String(text).indexOf(term,i+1)}return false};
 function rich(text,current){text=String(text);let out='',cursor=0;pat.lastIndex=0;let m;while((m=pat.exec(text))){const start=m.index,end=start+m[0].length;if(wordChar(text[start-1])||wordChar(text[end]))continue;const e=terms.get(m[0].toLowerCase());out+=safe(text.slice(cursor,start));out+=!e||e.id===current?safe(m[0]):'<span class="inline"><span>'+safe(m[0])+'</span><button data-open="'+e.id+'" title="Open '+safe(e.title)+'">'+sprite(e,20)+'</button></span>';cursor=end}return out+safe(text.slice(cursor))}
 function giftChip(name){const path=giftSprites[name],src=path&&sprites[path];const img=src?'<img src="'+src+'" width="30" height="30" alt="">':'<span></span>';const target=byTitle.get(String(name).toLowerCase());return target?'<button class="gift" data-open="'+target.id+'" title="Open '+safe(target.title)+'">'+img+'<span>'+safe(name)+'</span></button>':'<span class="gift">'+img+'<span>'+safe(name)+'</span></span>'}
 function tasteBlock(key,items,labelPrefix){const labels={loves:['Loved','+80'],likes:['Liked','+45'],neutrals:['Neutral','+20'],dislikes:['Disliked','-20'],hates:['Hated','-40']};const m=labels[key];return '<section class="taste"><div class="tasteMeta"><div><h4>'+safe((labelPrefix||'')+m[0])+'</h4><small>'+m[1]+' friendship'+(labelPrefix?' · unless overridden':'')+'</small></div><strong>'+items.length+'</strong></div>'+(items.length?'<div class="giftGrid">'+items.map(giftChip).join('')+'</div>':'<p class="muted">No personal overrides in this tier. Universal rules still apply.</p>')+'</section>'}
 function heartGuide(name){const events=heartEvents[name]||[];if(!events.length)return '';return '<section class="heartGuide"><div class="heartHead"><div><h3>Heart events</h3><p class="muted">Compact friendship milestones. Exact triggers can depend on place, time, weather, or progression.</p></div><strong>'+events.length+'</strong></div><div class="heartGrid">'+events.map(ev=>'<div class="heartCard"><span>'+(ev.heart===0?'Early':safe(ev.heart+' ♥'))+'</span><p>'+safe(ev.description)+'</p></div>').join('')+'</div></section>'}
 function villagerProfile(e){const p=profiles[e.title];if(!p)return '';const rel=p.roommate?'Can become your roommate':p.marriageable?'Marriage candidate':'Friendship character';const keys=['loves','likes','neutrals','dislikes','hates'];return '<section class="villagerProfile"><div class="villagerHead"><div><div class="eyebrow">Local friendship guide</div><h2>Gifts & key details</h2></div><span class="badge">● Offline-ready</span></div><div class="quickGrid"><div class="quickCard"><span>Birthday</span><strong>'+safe(p.birthday.season+' '+p.birthday.day)+'</strong><small>Birthday gifts are ×8 friendship, and can be given even after the normal two gifts that week.</small></div><div class="quickCard"><span>Home</span><strong>'+safe(p.address)+'</strong><small>'+safe(p.occupation)+'</small></div><div class="quickCard"><span>Relationship</span><strong>'+safe(rel)+'</strong><small>'+safe(p.availability||'Available through normal Valley progression.')+'</small></div></div><div class="friendTip"><strong>Gift timing:</strong> Loved +80 · Liked +45 · Neutral +20 · Disliked -20 · Hated -40. Birthday gifts are ×8; a Feast of the Winter Star secret-friend gift is ×5. Normally you can give two gifts per villager each week, with a birthday gift allowed on top. Personal tastes take priority over universal rules.</div><h3>'+safe(e.title)+' personal tastes</h3>'+keys.map(k=>tasteBlock(k,p[k],'')).join('')+'<details class="universals"><summary>Show universal gift defaults</summary><p class="muted">These apply unless this villager has a personal exception above.</p>'+keys.map(k=>tasteBlock(k,universals[k],'Universal ')).join('')+'</details>'+heartGuide(e.title)+'</section>'}
 function search(query){const s=norm(query),words=s.split(' ').filter(Boolean);if(!s)return entries.slice(0,24);const scored=entries.map(e=>{const title=norm(e.title),aliases=e.aliases.map(norm),keys=e.keywords.map(norm),body=norm([e.summary,...e.facts,...e.related].join(' '));let score=0,contextual=false;if(title===s)score=120;else if(aliases.includes(s))score=112;else if(title.startsWith(s))score=96;else if(aliases.some(x=>x.startsWith(s)))score=90;else if(title.includes(s))score=82;else if(aliases.some(x=>x.includes(s)))score=76;else if(keys.some(x=>x===s))score=72;else if(keys.some(x=>whole(x,s)))score=64;else if(words.length&&words.every(w=>title.includes(w)||aliases.some(x=>x.includes(w))||keys.some(x=>whole(x,w))||whole(body,w))){score=48;contextual=true}else if(whole(body,s)){score=32;contextual=true}return {e,score,contextual}}).filter(x=>x.score).sort((a,b)=>b.score-a.score||a.e.title.localeCompare(b.e.title));const direct=scored.filter(x=>!x.contextual),contextual=scored.filter(x=>x.contextual);return (direct.length>=12?direct:[...direct,...contextual.slice(0,Math.max(0,36-direct.length))]).map(x=>x.e)}
 function exact(query){const s=norm(query);return entries.find(e=>norm(e.title)===s||e.aliases.some(a=>norm(a)===s))}function card(e){return '<button class="card" data-open="'+e.id+'">'+sprite(e)+'<span><strong>'+safe(e.title)+'</strong><small>'+safe(e.category)+'</small><em>'+safe(e.summary)+'</em></span></button>'}
 function bind(){document.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>openEntry(el.dataset.open))}function list(query){const r=search(query),x=exact(query);if(!norm(query)){app.innerHTML='<h2>Browse the Valley</h2><p class="muted">'+entries.length+' built-in entries</p><div class="grid">'+['Crops','Fish','Villagers','Festivals','Bundles','Sword','Community Center','Crafting'].map(t=>byTitle.get(t.toLowerCase())).filter(Boolean).map(card).join('')+'</div>';bind();return}if(!r.length){app.innerHTML='<div class="empty"><h2>No built-in match yet</h2><p>Try a shorter or more specific Stardew term.</p></div>';return}let html='<h2>'+(r.length===1?'Found it':r.length+' matches')+'</h2>';if(x&&r.length>1)html+='<div class="eyebrow">General article</div>'+card(x)+'<h3>Or choose something more specific</h3>';html+='<div class="grid">'+(x&&r.length>1?r.filter(e=>e.id!==x.id):r).slice(0,60).map(card).join('')+'</div>';app.innerHTML=html;bind()}
 function openEntry(id){const e=entries.find(x=>x.id===id);if(!e)return;const related=e.related.map(n=>byTitle.get(n.toLowerCase())).filter(Boolean).slice(0,12);app.innerHTML='<button class="btn back" id="back">← Results</button><article class="article"><div class="title"><button class="heroSprite">'+sprite(e,64)+'</button><div><div class="eyebrow">'+safe(e.category)+'</div><h1>'+safe(e.title)+'</h1></div></div><p>'+rich(e.summary,e.id)+'</p><div class="facts"><h2>Good to know</h2><ul>'+e.facts.map(f=>'<li>'+rich(f,e.id)+'</li>').join('')+'</ul></div>'+villagerProfile(e)+(related.length?'<h2>Related</h2><div class="related">'+related.map(x=>'<button class="btn" data-open="'+x.id+'">'+sprite(x,24)+safe(x.title)+'</button>').join('')+'</div>':'')+'<h2>Sources</h2><p class="muted">These links need a connection; the summary above does not.</p><div class="sourceRow">'+e.sources.map(s=>'<a class="btn" href="'+safe(s.url)+'" target="_blank" rel="noreferrer">'+safe(s.label)+' ↗</a>').join('')+'</div></article>';document.getElementById('back').onclick=()=>list(q.value);bind();window.scrollTo({top:0,behavior:'smooth'})}
 document.getElementById('searchForm').onsubmit=e=>{e.preventDefault();list(q.value)};q.oninput=()=>list(q.value);list('');
 </script></body></html>`;
}
