import {encyclopediaEntries,encyclopediaSpritePath} from './encyclopedia';

export function buildOfflineEncyclopediaHtml(spriteData:Record<string,string>){
 const entries=encyclopediaEntries.map(entry=>({...entry,spritePath:encyclopediaSpritePath(entry)}));
 const safeJson=JSON.stringify(entries).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');
 const safeSprites=JSON.stringify(spriteData).replaceAll('<','\\u003c');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pelican Planner Encyclopedia · Offline</title><style>
 :root{--paper:#fff7db;--ink:#352713;--green:#326c36;--wood:#75411f;--gold:#f4cc6c;--soft:#deefab}*{box-sizing:border-box}body{margin:0;background:#dcebbb;color:var(--ink);font:18px/1.45 ui-rounded,"Comic Sans MS",cursive}button,input{font:inherit}button{cursor:pointer}a{color:#1c6552}.wrap{max-width:1050px;margin:auto;padding:28px 18px 60px}.hero,.panel{background:var(--paper);border:3px solid #b9762f;box-shadow:inset 0 0 0 4px #f3d89b;padding:22px}.hero{margin-bottom:18px}.top{display:flex;justify-content:space-between;gap:18px;align-items:start}.badge{display:inline-flex;align-items:center;gap:6px;background:#e2efc3;border:2px solid #6f8c51;padding:5px 9px;font-size:.9rem}.search{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:18px}.search input{min-width:0;padding:11px 12px;border:3px solid #8d6738;background:#fffdf0}.btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:42px;padding:8px 14px;border:2px solid #965b22;background:var(--gold);color:#422b13;text-decoration:none}.btn:hover{background:#ffe293}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.card{display:grid;grid-template-columns:48px minmax(0,1fr);gap:10px;align-items:center;text-align:left;background:#fff4ca;border:2px solid #b78038;padding:10px;color:inherit}.card:hover{background:#fff0ae}.card img,.heroSprite img,.inline img{image-rendering:pixelated;object-fit:contain}.card strong,.card small,.card em{display:block}.card small{color:#6e5e44}.card em{font-style:normal;color:#6a5738;font-size:.92rem;margin-top:2px}.article h1{font-size:2.5rem;margin:.15em 0}.title{display:flex;align-items:center;gap:14px}.heroSprite{border:0;background:transparent;padding:0}.facts li{margin:8px 0}.related{display:flex;flex-wrap:wrap;gap:7px}.related .btn{background:#f9e5a5}.inline{display:inline-flex;align-items:center;gap:3px}.inline button{border:0;background:transparent;padding:0 1px;vertical-align:middle}.inline img{width:20px;height:20px}.muted{color:#6a583a}.eyebrow{text-transform:uppercase;letter-spacing:.06em;font-size:.82rem;font-weight:700;color:#63502c}.sourceRow{display:flex;flex-wrap:wrap;gap:7px}.empty{text-align:center;padding:30px}.back{margin-bottom:14px}/* Compact offline-reader guardrails */
.wrap,.hero,.panel,.top>*,.title>*{min-width:0}.hero,.panel{overflow-wrap:anywhere}.card{min-width:0;overflow:hidden}.card>span,.card strong,.card small,.card em{min-width:0;overflow-wrap:anywhere}.article{min-width:0;overflow:hidden}.article p,.facts li{overflow-wrap:anywhere}.article h1{max-width:100%;overflow-wrap:anywhere}.sourceRow .btn,.related .btn{max-width:100%;white-space:normal;overflow-wrap:anywhere;text-align:center}
@media(max-width:720px){.wrap{padding:16px 12px 42px}.hero,.panel{padding:16px}.hero{margin-bottom:12px}.top{display:block}.badge{margin-top:9px}.grid{grid-template-columns:1fr}.search{grid-template-columns:1fr;margin-top:14px}.search .btn{width:100%}.card{grid-template-columns:42px minmax(0,1fr);padding:9px}.article h1{font-size:2.05rem}.title{gap:10px}.facts ul{padding-left:21px}.sourceRow .btn{flex:1 1 180px}}
@media(max-width:420px){.wrap{padding:10px 8px 34px}.hero,.panel{padding:12px}.card{grid-template-columns:36px minmax(0,1fr);gap:8px;padding:8px}.card strong{font-size:1rem}.card small,.card em{font-size:.86rem}.article h1{font-size:1.8rem}.title{align-items:flex-start}.btn{padding:7px 10px}.empty{padding:20px 8px}}
 </style></head><body><div class="wrap"><section class="hero"><div class="top"><div><div class="eyebrow">Pelican Planner reference</div><h1 style="margin:.1em 0">Encyclopedia</h1><p style="margin:0">Offline copy. Search and open the bundled entries without a network connection.</p></div><span class="badge">● Offline-ready</span></div><form class="search" id="searchForm"><input id="q" autocomplete="off" placeholder="Try Cabbage, sword, Wood, Abigail…"><button class="btn">Search</button></form></section><main class="panel" id="app"></main></div><script>
 const entries=${safeJson};const sprites=${safeSprites};const app=document.getElementById('app'),q=document.getElementById('q');
 const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\\s-]+/g,' ').replace(/\\s+/g,' ').trim();const byTitle=new Map(entries.map(e=>[e.title.toLowerCase(),e]));
 const linkable=entries.filter(e=>e.spritePath&&e.title.length>2).sort((a,b)=>b.title.length-a.title.length);const terms=new Map();for(const e of linkable)for(const t of [e.title,...e.aliases])if(t.length>2&&!terms.has(t.toLowerCase()))terms.set(t.toLowerCase(),e);const esc=s=>s.replace(/[-/\\^$*+?.()|[\\]{}]/g,'\\\\$&');const pat=new RegExp('('+[...terms.keys()].sort((a,b)=>b.length-a.length).map(esc).join('|')+')','gi');
 function sprite(e,size=42){const src=sprites[e.spritePath];return src?'<img src="'+src+'" width="'+size+'" height="'+size+'" alt="">':'<span></span>'}function safe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function rich(text,current){const parts=String(text).split(pat);return parts.map(part=>{const e=terms.get(part.toLowerCase());if(!e||e.id===current)return safe(part);return '<span class="inline"><span>'+safe(part)+'</span><button data-open="'+e.id+'" title="Open '+safe(e.title)+'">'+sprite(e,20)+'</button></span>'}).join('')}
 function search(query){const s=norm(query),words=s.split(' ').filter(Boolean);if(!s)return entries.slice(0,24);const scored=entries.map(e=>{const title=norm(e.title),aliases=e.aliases.map(norm),keys=e.keywords.map(norm),body=norm([e.summary,...e.facts,...e.related].join(' '));let score=0,contextual=false;if(title===s)score=120;else if(aliases.includes(s))score=112;else if(title.startsWith(s))score=96;else if(aliases.some(x=>x.startsWith(s)))score=90;else if(title.includes(s))score=82;else if(aliases.some(x=>x.includes(s)))score=76;else if(keys.some(x=>x===s))score=72;else if(keys.some(x=>x.includes(s)))score=64;else if(words.length&&words.every(w=>title.includes(w)||aliases.some(x=>x.includes(w))||keys.some(x=>x.includes(w))||body.includes(w))){score=48;contextual=true}else if(body.includes(s)){score=32;contextual=true}return {e,score,contextual}}).filter(x=>x.score).sort((a,b)=>b.score-a.score||a.e.title.localeCompare(b.e.title));const direct=scored.filter(x=>!x.contextual),contextual=scored.filter(x=>x.contextual);return (direct.length>=12?direct:[...direct,...contextual.slice(0,Math.max(0,36-direct.length))]).map(x=>x.e)}
 function exact(query){const s=norm(query);return entries.find(e=>norm(e.title)===s||e.aliases.some(a=>norm(a)===s))}function card(e){return '<button class="card" data-open="'+e.id+'">'+sprite(e)+'<span><strong>'+safe(e.title)+'</strong><small>'+safe(e.category)+'</small><em>'+safe(e.summary)+'</em></span></button>'}
 function bind(){document.querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>openEntry(el.dataset.open))}function list(query){const r=search(query),x=exact(query);if(!norm(query)){app.innerHTML='<h2>Browse the Valley</h2><p class="muted">'+entries.length+' built-in entries</p><div class="grid">'+['Crops','Fish','Villagers','Festivals','Bundles','Sword','Community Center','Crafting'].map(t=>byTitle.get(t.toLowerCase())).filter(Boolean).map(card).join('')+'</div>';bind();return}if(!r.length){app.innerHTML='<div class="empty"><h2>No built-in match yet</h2><p>Try a shorter or more specific Stardew term.</p></div>';return}let html='<h2>'+(r.length===1?'Found it':r.length+' matches')+'</h2>';if(x&&r.length>1)html+='<div class="eyebrow">General article</div>'+card(x)+'<h3>Or choose something more specific</h3>';html+='<div class="grid">'+(x&&r.length>1?r.filter(e=>e.id!==x.id):r).slice(0,60).map(card).join('')+'</div>';app.innerHTML=html;bind()}
 function openEntry(id){const e=entries.find(x=>x.id===id);if(!e)return;const related=e.related.map(n=>byTitle.get(n.toLowerCase())).filter(Boolean).slice(0,12);app.innerHTML='<button class="btn back" id="back">← Results</button><article class="article"><div class="title"><button class="heroSprite">'+sprite(e,64)+'</button><div><div class="eyebrow">'+safe(e.category)+'</div><h1>'+safe(e.title)+'</h1></div></div><p>'+rich(e.summary,e.id)+'</p><div class="facts"><h2>Good to know</h2><ul>'+e.facts.map(f=>'<li>'+rich(f,e.id)+'</li>').join('')+'</ul></div>'+(related.length?'<h2>Related</h2><div class="related">'+related.map(x=>'<button class="btn" data-open="'+x.id+'">'+sprite(x,24)+safe(x.title)+'</button>').join('')+'</div>':'')+'<h2>Sources</h2><p class="muted">These links need a connection; the summary above does not.</p><div class="sourceRow">'+e.sources.map(s=>'<a class="btn" href="'+safe(s.url)+'" target="_blank" rel="noreferrer">'+safe(s.label)+' ↗</a>').join('')+'</div></article>';document.getElementById('back').onclick=()=>list(q.value);bind();window.scrollTo({top:0,behavior:'smooth'})}
 document.getElementById('searchForm').onsubmit=e=>{e.preventDefault();list(q.value)};q.oninput=()=>list(q.value);list('');
 </script></body></html>`;
}
