export const ISLAND_REGIONS=['All','General','East','West','North','South'] as const;
export type IslandRegion=Exclude<(typeof ISLAND_REGIONS)[number],'All'>;
export type WalnutActivity={id:string;region:IslandRegion;name:string;max:number;hint:string;puzzle?:boolean};

export const WALNUT_ACTIVITIES:WalnutActivity[]=[
 // General · 6
 {id:'general-golden-coconut',region:'General',name:'First Golden Coconut',max:1,hint:'Crack your first Golden Coconut at Clint’s.'},
 {id:'general-fishing',region:'General',name:'Island fishing',max:5,hint:'Catch Golden Walnuts while fishing anywhere around Ginger Island.'},
 // East · 11
 {id:'east-jungle-bush',region:'East',name:'Jungle path bush',max:1,hint:'Check the walnut bush on the jungle path toward Leo’s hut.'},
 {id:'east-banana-shrine',region:'East',name:'Banana Shrine',max:3,hint:'Offer a Banana at the altar beside the stairs to Leo’s hut.',puzzle:true},
 {id:'east-leo-tree',region:'East',name:'Tree inside Leo’s hut',max:1,hint:'Hit the tree inside Leo’s hut with an axe.'},
 {id:'east-shrine-bush',region:'East',name:'Gem Birds shrine bush',max:1,hint:'Follow the hidden passage east from Leo’s stairs and check the bush south of the Gem Birds shrine.'},
 {id:'east-gem-birds',region:'East',name:'Gem Birds shrine',max:5,hint:'Match the four island gems to the rainy-day Gem Birds puzzle.',puzzle:true},
 // West · 52
 {id:'west-crops',region:'West',name:'Harvest island crops',max:5,hint:'Harvest non-regrowing crops on the Island Farm for walnut chances.'},
 {id:'west-gourmand',region:'West',name:'Gourmand Frog requests',max:15,hint:'Show the Gourmand Frog a mature Melon, Wheat, then Garlic without harvesting them first.',puzzle:true},
 {id:'west-scrap-6',region:'West',name:'Journal Scrap #6',max:1,hint:'Read Journal Scrap #6, then dig at its marked spot southeast of the farm.',puzzle:true},
 {id:'west-mussel-nodes',region:'West',name:'Mussel Nodes',max:5,hint:'Break Mussel Nodes on the beach for walnut chances.'},
 {id:'west-shipwreck',region:'West',name:'Shipwreck bush',max:1,hint:'Enter the shipwreck through its hidden west-side path and check the plant inside.'},
 {id:'west-mole',region:'West',name:'Whack-a-Mole',max:1,hint:'Block the other holes, then hit the beach mole with a tool.',puzzle:true},
 {id:'west-blue-starfish',region:'West',name:'Blue starfish triangle',max:1,hint:'Dig in the center of the blue-starfish triangle south of the farm.'},
 {id:'west-starfish-diamond',region:'West',name:'Starfish diamond',max:1,hint:'Dig in the center of the starfish diamond near the tide pools.'},
 {id:'west-sand-x',region:'West',name:'Sand X',max:1,hint:'Dig the X marked in the tide-pool sand.'},
 {id:'west-indents',region:'West',name:'Four sand indents',max:1,hint:'Dig the center of the four indents near the ocean.'},
 {id:'west-pond-tree',region:'West',name:'Tree by the pond',max:1,hint:'Check behind the coconut tree by the pond west of the farm.'},
 {id:'west-pirate-wife',region:'West',name:'The Pirate’s Wife',max:5,hint:'Finish Birdie’s keepsake trading quest.'},
 {id:'west-scrap-4',region:'West',name:'Journal Scrap #4',max:1,hint:'Read Journal Scrap #4, then dig in the sand north of Birdie’s hut.',puzzle:true},
 {id:'west-qi-bush',region:'West',name:'Bush near Qi’s Walnut Room',max:1,hint:'Walk up the western coast toward Qi’s Walnut Room and check the bush near the cliff.'},
 {id:'west-ocean-path',region:'West',name:'Hidden ocean path',max:1,hint:'Walk north past Qi’s Walnut Room through the ocean water to the hidden bush.'},
 {id:'west-tiger-slime',region:'West',name:'Tiger Slimes',max:1,hint:'Defeat Tiger Slimes in the grove until the walnut drops.'},
 {id:'west-grove-tree',region:'West',name:'Tiger Grove tree bush',max:1,hint:'Check behind a mahogany tree in the Tiger Slime Grove.'},
 {id:'west-grass-circle',region:'West',name:'Tiger Grove grass circle',max:1,hint:'Dig the center of the grass circle in the Tiger Slime Grove.'},
 {id:'west-bridge-bush',region:'West',name:'West bridge bush',max:1,hint:'From the farm’s Parrot Express station, cross the bridge west and check the partly hidden bush.'},
 {id:'west-simon',region:'West',name:'Simon Says cave',max:3,hint:'Complete the crystal sequence puzzle north of the Tiger Slime Grove.',puzzle:true},
 {id:'west-cliff-bush',region:'West',name:'East cliff bush',max:1,hint:'Go east from the Tiger Slime Grove and follow the cliff edge to the walnut bush.'},
 {id:'west-pebble-diamond',region:'West',name:'Pebble diamond',max:1,hint:'Dig in the center of the pebble diamond east of the farm’s Parrot Express station.'},
 {id:'west-hidden-path',region:'West',name:'Hidden east path bush',max:1,hint:'Follow the hidden path east and north of the farm’s Parrot Express station.'},
 {id:'west-farm-overlook',region:'West',name:'Farmhouse overlook bush',max:1,hint:'Follow the cliff south of the farm’s Parrot Express station, then bend east above the farmhouse.'},
 // North · 49
 {id:'north-entry-stones',region:'North',name:'Entrance stone circle',max:1,hint:'At the top of the Island North stairs, turn west and dig in the center of the stone circle.'},
 {id:'north-entry-grove',region:'North',name:'Entrance hidden grove',max:1,hint:'From the Island North entrance, take the hidden passage west to the walnut bush.'},
 {id:'north-flower-circle',region:'North',name:'Flower circle',max:1,hint:'Northeast of the entrance, dig in the center of the flower circle.'},
 {id:'north-east-stones',region:'North',name:'Eastern stone circle',max:1,hint:'Continue east from the flower circle and dig in the center of the next stone circle.'},
 {id:'north-office-sand',region:'North',name:'Field Office sand patch',max:1,hint:'Southeast of the Field Office, dig the patch of sand with an unusual texture.'},
 {id:'north-dig-site-circle',region:'North',name:'Dig Site stone circle',max:1,hint:'Climb the north steps of the Dig Site and dig in the center of the stone circle.'},
 {id:'north-dig-site-west-bush',region:'North',name:'Dig Site west bush',max:1,hint:'From the upper Dig Site, cross the bridge west to the walnut plant.'},
 {id:'north-dig-site-east-pair',region:'North',name:'Dig Site hidden eastern path',max:2,hint:'Take the hidden cliff passage east of the upper Dig Site and cross the bridge to two walnut plants.'},
 {id:'north-large-animal',region:'North',name:'Large Animal collection',max:6,hint:'Complete the Large Animal collection at the Island Field Office.'},
 {id:'north-snake',region:'North',name:'Snake collection',max:3,hint:'Complete the Snake collection at the Island Field Office.'},
 {id:'north-mummified-frog',region:'North',name:'Mummified Frog donation',max:1,hint:'Donate a Mummified Frog to Professor Snail.'},
 {id:'north-mummified-bat',region:'North',name:'Mummified Bat donation',max:1,hint:'Donate a Mummified Bat to Professor Snail.'},
 {id:'north-purple-flowers',region:'North',name:'Purple Flowers survey',max:1,hint:'Answer the Field Office survey: 22 purple flowers.',puzzle:true},
 {id:'north-purple-starfish',region:'North',name:'Purple Starfish survey',max:1,hint:'Answer the Field Office survey: 18 purple starfish.',puzzle:true},
 {id:'north-volcano-tree-bush',region:'North',name:'Southeast Volcano bush',max:1,hint:'Southeast of the Volcano entrance, check the walnut plant hidden by a tree.'},
 {id:'north-volcano-sand-arc',region:'North',name:'Volcano sand arc',max:1,hint:'East of the Volcano entrance, dig in the sand circled by two bushes and an arc of stones.'},
 {id:'north-volcano-slingshot',region:'North',name:'Curved Volcano tree',max:1,hint:'Northeast of the entrance, knock the walnut from the curved tree with a Slingshot.'},
 {id:'north-scrap-10',region:'North',name:'Journal Scrap #10',max:1,hint:'Read Journal Scrap #10, then dig inside the loop of the curved palm southwest of the Volcano.',puzzle:true},
 {id:'north-northwest-stones',region:'North',name:'Northwest stone circle',max:1,hint:'At the extreme northwest of the island, dig in the center of the stone circle.'},
 {id:'north-northwest-passage',region:'North',name:'Northwest hidden passage',max:1,hint:'Follow the wall west of the Volcano into the hidden passage to a secluded walnut bush.'},
 {id:'north-fire-river',region:'North',name:'Fire-river west exit',max:2,hint:'At the Volcano lava river, water a path west then south and exit to the outdoor area with two walnut bushes.',puzzle:true},
 {id:'north-volcano-dungeon',region:'North',name:'Volcano Dungeon',max:17,hint:'Up to 5 from rocks, 5 from enemies, 5 from metal crates, and 1 each from common and rare chests.'},
 {id:'north-forge',region:'North',name:'Forge area',max:2,hint:'Reach the Forge and collect the walnut plants at its entrance and exit.'},
 // South · 12
 {id:'south-upper-cliff',region:'South',name:'Upper cliff bush',max:1,hint:'From the stairs to Island North, turn east and follow the hidden route south behind the tree to the upper-cliff bush.'},
 {id:'south-tidepool-fishing',region:'South',name:'Star-shaped tide pool catch',max:1,hint:'After the resort opens Island Southeast, the first catch from the star-shaped tide pool gives a walnut.'},
 {id:'south-yellow-starfish',region:'South',name:'Yellow starfish diamond',max:1,hint:'In Island Southeast, dig in the center of the diamond of yellow starfish.'},
 {id:'south-mermaid',region:'South',name:'Mermaid flute-block puzzle',max:5,hint:'On a rainy day after the resort opens, tune five Flute Blocks using the stone groups and run past them left to right.',puzzle:true},
 {id:'south-darts',region:'South',name:'Pirate Cove darts',max:3,hint:'On a non-rainy even-numbered day after 8 PM, win three rounds of darts in Pirate Cove.',puzzle:true},
 {id:'south-pirate-sand',region:'South',name:'Pirate Cove barrel dig spot',max:1,hint:'In Pirate Cove, dig the exposed patch of sand among the barrels east of the water.'},
];

export const TOTAL_GOLDEN_WALNUTS=WALNUT_ACTIVITIES.reduce((sum,item)=>sum+item.max,0);

export const ISLAND_HOTSPOTS=[
 {id:'volcano',name:'Volcano Dungeon',region:'North' as IslandRegion,x:51,y:13,subtitle:'Forge · dungeon · walnuts'},
 {id:'dig-site',name:'Dig Site',region:'North' as IslandRegion,x:33,y:35,subtitle:'Fossils · Field Office'},
 {id:'field-office',name:'Field Office',region:'North' as IslandRegion,x:53,y:40,subtitle:'Professor Snail · surveys'},
 {id:'island-trader',name:'Island Trader',region:'North' as IslandRegion,x:67,y:38,subtitle:'Trading hub'},
 {id:'farm',name:'Island Farm',region:'West' as IslandRegion,x:29,y:61,subtitle:'Crops · Gourmand Frog'},
 {id:'qi-room',name:'Qi’s Walnut Room',region:'West' as IslandRegion,x:10,y:63,subtitle:'Late-game walnut milestone'},
 {id:'tiger-grove',name:'Tiger Slime Grove',region:'West' as IslandRegion,x:18,y:51,subtitle:'Slimes · hidden paths'},
 {id:'simon-cave',name:'Crystal Cave',region:'West' as IslandRegion,x:22,y:70,subtitle:'Simon Says puzzle'},
 {id:'leo',name:'Leo’s Hut',region:'East' as IslandRegion,x:79,y:53,subtitle:'Jungle · Banana Shrine'},
 {id:'gem-birds',name:'Gem Birds Shrine',region:'East' as IslandRegion,x:87,y:62,subtitle:'Rainy-day puzzle'},
 {id:'docks',name:'Island Docks',region:'South' as IslandRegion,x:49,y:87,subtitle:'Arrival · south beach'},
 {id:'resort',name:'Island Resort',region:'South' as IslandRegion,x:67,y:84,subtitle:'Resort beach'},
 {id:'pirate-cove',name:'Pirate Cove',region:'South' as IslandRegion,x:83,y:80,subtitle:'Pirates · darts'},
 {id:'mermaid',name:'Mermaid Beach',region:'South' as IslandRegion,x:70,y:93,subtitle:'Rainy-day puzzle'},
];
