export type GiftTaste='loves'|'likes'|'neutrals'|'dislikes'|'hates';
export interface VillagerProfile{
 birthday:{season:'Spring'|'Summer'|'Fall'|'Winter';day:number};
 address:string;
 occupation:string;
 marriageable?:boolean;
 roommate?:boolean;
 availability?:string;
 loves:string[];
 likes:string[];
 neutrals:string[];
 dislikes:string[];
 hates:string[];
}

export const universalGiftTastes:Record<GiftTaste,string[]>={
 loves:['Golden Pumpkin','Magic Rock Candy','Pearl','Prismatic Shard','Rabbit\'s Foot','Stardrop Tea'],
 likes:['All Artisan Goods (except Oil & Void Mayonnaise)','All Cooking (except Bread, Fried Egg, Seafoam Pudding & Strange Bun)','All Flowers (except Poppy)','All Foraged Minerals (except Quartz)','All Fruit Tree Fruit','All Gems','All Vegetables (except Hops, Tea Leaves, Unmilled Rice & Wheat)','Life Elixir','Maple Syrup','Piña Colada','Rainbow Shell','Treasure Chest'],
 neutrals:['All Books (except Price Catalogue)','Bread','Coral','Duck Feather','Fried Egg','Hops','Mystic Syrup','Nautilus Shell','Roe','Squid Ink','Sweet Gem Berry','Tea Leaves','Truffle','Wheat','Wool'],
 dislikes:['All Building Materials','All Artifacts','All Bombs','All Crafted Floors & Paths','All Fences','All Fertilizer','All Fish (except Carp & Snail)','All Geode Minerals','All Geodes','All Seeds','All Sprinklers','All Tackle','All Trinkets','Fireworks','Misc. Mined/Metal Goods','Cave Carrot','Driftwood','Field Snack','Jack-O-Lantern','Oak Resin','Oil','Pine Tar','Price Catalogue','Qi Fruit','Rice','Solar Essence','Spring Onion','Tea Set','Unmilled Rice','Vinegar','Void Egg','Void Essence','Wheat Flour'],
 hates:['All Bait','All Fossils','All Monster Loot (except Solar Essence & Void Essence)','All Trash (except Driftwood)','Artifact Trove','Blue Grass Starter','Bug Steak','Butterfly Powder','Carp','Cookout Kit','Copper Ore','Crab Pot','Dragon Tooth','Drum Block','Energy Tonic','Explosive Ammo','Fairy Dust','Flute Block','Golden Bobber','Golden Coconut','Golden Mystery Box','Golden Tag','Grass Starter','Green Algae','Hay','Iron Ore','Journal Scrap','Monster Musk','Muscle Remedy','Mystery Box','Oil of Garlic','Poppy','Qi Seasoning','Radioactive Bar','Radioactive Ore','Rain Totem','Red Mushroom','Sap','Sea Urchin','Seafoam Pudding','Seaweed','Secret Note','Slime Egg','Snail','Strange Bun','Sugar','Tent Kit','Torch','Void Mayonnaise','Warp Totems','White Algae']
};

export const villagerProfiles:Record<string,VillagerProfile>={
 Abigail:{birthday:{season:'Fall',day:13},address:"Pierre's General Store",occupation:'Adventurer',marriageable:true,loves:['Amethyst','Banana Pudding','Blackberry Cobbler','Chocolate Cake','Monster Compendium','Pufferfish','Pumpkin','Spicy Eel'],likes:['Ancient Sword','Basilisk Paw','Bone Flute','Combat Quarterly','Quartz'],neutrals:['All Milk','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Leek','Magma Cap','Morel','Purple Mushroom','Snow Yam','Winter Root'],dislikes:['All Eggs','All Fruit (except Fruit Tree Fruit)','All Vegetables (except Hops, Pumpkin, Tea Leaves & Wheat)','Sugar','Wild Horseradish'],hates:['Clay','Holly']},
 Alex:{birthday:{season:'Summer',day:13},address:'1 River Road',occupation:'Aspiring gridball player',marriageable:true,loves:['Complete Breakfast','Jack Be Nimble, Jack Be Thick','Salmon Dinner'],likes:['Dinosaur Egg','Field Snack','Parrot Egg'],neutrals:['All Fruit (except Fruit Tree Fruit & Salmonberry)','All Milk','Chanterelle','Common Mushroom','Daffodil','Dandelion','Frog Egg','Ginger','Hazelnut','Leek','Magma Cap','Morel','Purple Mushroom','Snow Yam','Winter Root'],dislikes:['All Books (except Jack Be Nimble, Jack Be Thick)','Salmonberry','Void Egg','Wild Horseradish'],hates:['Holly','Quartz']},
 Caroline:{birthday:{season:'Winter',day:7},address:"Pierre's General Store",occupation:'Homemaker',loves:['Fish Taco','Green Tea','Summer Spangle','Tropical Curry'],likes:['Daffodil','Tea Leaves','Wild Horseradish'],neutrals:['All Eggs (except Void Egg)','All Fruit (except Fruit Tree Fruit & Salmonberry)','All Milk'],dislikes:['Amaranth','Chanterelle','Common Mushroom','Dandelion','Duck Mayonnaise','Ginger','Hazelnut','Holly','Leek','Magma Cap','Mayonnaise','Morel','Purple Mushroom','Snow Yam','Winter Root'],hates:['Quartz','Salmonberry']},
 Clint:{birthday:{season:'Winter',day:26},address:'Blacksmith',occupation:'Blacksmith',loves:['Amethyst','Aquamarine','Artichoke Dip','Emerald','Fiddlehead Risotto','Gold Bar','Iridium Bar','Jade','Omni Geode','Ruby','Topaz'],likes:['Copper Bar','Iron Bar','Mining Monthly'],neutrals:['All Eggs (except Void Egg)','All Fruit (except Fruit Tree Fruit & Salmonberry)','All Milk','Chanterelle','Coal','Common Mushroom','Daffodil','Dandelion','Ginger','Gold Ore','Hazelnut','Iridium Ore','Leek','Magma Cap','Morel','Purple Mushroom','Refined Quartz','Snow Yam','Winter Root'],dislikes:['All Flowers (except Poppy)','Quartz','Salmonberry','Wild Horseradish'],hates:['Holly']},
 Demetrius:{birthday:{season:'Summer',day:19},address:'24 Mountain Road',occupation:'Scientist',loves:['Bean Hotpot','Ice Cream','Rice Pudding','Strawberry'],likes:['Dinosaur Egg','Purple Mushroom'],neutrals:['All Fish (except Carp & Snail)','All Milk','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Leek','Magma Cap','Morel','Snow Yam','Wild Horseradish','Winter Root'],dislikes:['Quartz'],hates:['Holly']},
 Dwarf:{birthday:{season:'Summer',day:22},address:'The Mines',occupation:'Merchant',availability:'Reach the eastern Mines passage and learn Dwarvish to shop normally.',loves:['Amethyst','Aquamarine','Emerald','Jade','Lava Eel','Lemon Stone','Omni Geode','Ruby','Topaz'],likes:['All Artifacts','Cave Carrot','Quartz'],neutrals:['All Fruit (except Fruit Tree Fruit & Salmonberry)','All Milk','Solar Essence','Void Essence'],dislikes:['All Eggs','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Purple Mushroom','Salmonberry','Snow Yam','Wild Horseradish','Winter Root'],hates:[]},
 Elliott:{birthday:{season:'Fall',day:5},address:"Elliott's Cabin",occupation:'Writer',marriageable:true,loves:['Crab Cakes','Duck Feather','Lobster','Pomegranate','Squid Ink','Tom Kha Soup'],likes:['All Books','All Fruit (except Pomegranate & Salmonberry)','Octopus','Squid'],neutrals:['All Eggs (except Void Egg)','All Fish (except Carp, Lobster, Octopus, Sea Cucumber, Snail & Squid)','Rainbow Shell','Sea Urchin'],dislikes:['All Milk','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Pizza','Purple Mushroom','Snow Yam','Wild Horseradish','Winter Root'],hates:['Amaranth','Quartz','Salmonberry','Sea Cucumber','Super Cucumber']},
 Emily:{birthday:{season:'Spring',day:27},address:'2 Willow Lane',occupation:'Tailor / Stardrop Saloon worker',marriageable:true,loves:['Amethyst','Aquamarine','Cloth','Emerald','Jade','Parrot Egg','Ruby','Survival Burger','Topaz','Wool'],likes:['Daffodil','Quartz'],neutrals:['All Eggs (except Void Egg)','All Fruit (except Fruit Tree Fruit & Salmonberry)','All Milk','Chanterelle','Common Mushroom','Dandelion','Ginger','Hazelnut','Leek','Magma Cap','Morel','Purple Mushroom','Snow Yam','Wild Horseradish','Winter Root'],dislikes:['Fried Eel','Ice Cream','Rice Pudding','Salmonberry','Spicy Eel'],hates:['Fish Taco','Holly','Maki Roll','Salmon Dinner','Sashimi']},
 Evelyn:{birthday:{season:'Winter',day:20},address:'1 River Road',occupation:'Gardener',loves:['Beet','Chocolate Cake','Diamond','Fairy Rose','Raisins','Stuffing','Tulip'],likes:['Broken Glasses','Clam','Cockle','Coral','Daffodil','Mussel','Nautilus Shell','Oyster','Sea Urchin'],neutrals:['All Eggs (except Void Egg)','All Fruit (except Fruit Tree Fruit, Salmonberry & Spice Berry)','Chanterelle','Common Mushroom','Dandelion','Ginger','Hazelnut','Leek','Magma Cap','Morel','Purple Mushroom','Snow Yam','Winter Root'],dislikes:['Quartz','Wild Horseradish'],hates:['All Fish (except Clam, Cockle, Mussel & Oyster)','Clay','Fried Eel','Garlic','Holly','Maki Roll','Salmonberry','Sashimi','Spice Berry','Spicy Eel','Trout Soup']},
 George:{birthday:{season:'Fall',day:24},address:'1 River Road',occupation:'Retired',loves:['Fried Mushroom','Leek'],likes:['Daffodil'],neutrals:['All Eggs (except Void Egg)','All Fruit (except Fruit Tree Fruit & Salmonberry)','All Milk','Chanterelle','Common Mushroom','Ginger','Hazelnut','Magma Cap','Morel','Purple Mushroom','Snow Yam','Winter Root'],dislikes:['All Flowers (except Poppy)','Salmonberry','Wild Horseradish'],hates:['Clay','Dandelion','Holly','Quartz']},
 Gus:{birthday:{season:'Summer',day:8},address:'Stardrop Saloon',occupation:'Saloon owner and chef',loves:['Diamond','Escargot','Fish Taco','Orange','Tropical Curry'],likes:['Daffodil','Truffle'],neutrals:['All Eggs (except Void Egg)','All Fruit (except Fruit Tree Fruit & Salmonberry)','All Milk','Chanterelle','Common Mushroom','Dandelion','Ginger','Hazelnut','Leek','Magma Cap','Morel','Purple Mushroom','Snow Yam','Winter Root'],dislikes:['Salmonberry','Wild Horseradish'],hates:['Coleslaw','Holly','Quartz']},
 Haley:{birthday:{season:'Spring',day:14},address:'2 Willow Lane',occupation:'Photographer',marriageable:true,loves:['Coconut','Fruit Salad','Pink Cake','Sunflower'],likes:['Daffodil'],neutrals:[],dislikes:['All Eggs','All Fruit (except Coconut)','All Milk','All Vegetables (except Hops, Tea Leaves & Wheat)','Chanterelle','Common Mushroom','Dandelion','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Mystic Syrup','Purple Mushroom','Quartz','Snow Yam','Winter Root'],hates:['All Fish','Clay','Prismatic Shard','Wild Horseradish']},
 Harvey:{birthday:{season:'Winter',day:14},address:"Harvey's Clinic",occupation:'Doctor',marriageable:true,loves:['Coffee','Pickles','Super Meal','Truffle Oil','Wine'],likes:['Chanterelle','Common Mushroom','Daffodil','Dandelion','Duck Egg','Duck Feather','Goat Milk','Hazelnut','Holly','Large Goat Milk','Leek','Magma Cap','Morel','Purple Mushroom','Quartz','Spring Onion','Winter Root'],neutrals:['Large Milk','Milk'],dislikes:['Blueberry Tart','Bread','Cheese','Chocolate Cake','Cookie','Cranberry Sauce','Fried Mushroom','Glazed Yams','Goat Cheese','Hashbrowns','Ice Cream','Pancakes','Pink Cake','Pizza','Rhubarb Pie','Rice Pudding'],hates:['Coral','Nautilus Shell','Rainbow Shell','Salmonberry','Spice Berry']},
 Jas:{birthday:{season:'Summer',day:4},address:"Marnie's Ranch",occupation:'Child',loves:['Ancient Doll','Fairy Box','Fairy Rose','Pink Cake','Plum Pudding','Strange Doll (green)','Strange Doll (yellow)'],likes:['Coconut','Daffodil'],neutrals:[],dislikes:['All Eggs','All Fruit (except Coconut & Fruit Tree Fruit)','All Vegetables (except Hops & Wheat)','Chanterelle','Common Mushroom','Dandelion','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Purple Mushroom','Quartz','Snow Yam','Winter Root'],hates:['All Artisan Goods (except Honey, Jelly & Oil)','Beer','Clay','Coffee','Mead','Pale Ale','Piña Colada','Triple Shot Espresso','Wild Horseradish','Wine']},
 Jodi:{birthday:{season:'Fall',day:11},address:'1 Willow Lane',occupation:'Homemaker',loves:['Chocolate Cake','Crispy Bass','Diamond','Eggplant Parmesan','Fried Eel','Pancakes','Rhubarb Pie','Vegetable Medley'],likes:[],neutrals:[],dislikes:['Chanterelle','Common Mushroom','Garlic','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Purple Mushroom','Quartz','Snow Yam','Wild Horseradish','Winter Root'],hates:['Daffodil','Dandelion','Spice Berry']},
 Kent:{birthday:{season:'Spring',day:4},address:'1 Willow Lane',occupation:'Soldier',availability:'Returns to Pelican Town at the start of Year 2.',loves:['Fiddlehead Risotto','Roasted Hazelnuts'],likes:['Daffodil','Dwarvish Safety Manual'],neutrals:['Chanterelle','Common Mushroom','Dandelion','Ginger','Hazelnut','Leek','Magma Cap','Morel','Purple Mushroom','Wild Horseradish','Winter Root'],dislikes:['Piña Colada','Quartz','Snow Yam'],hates:['Algae Soup','All Milk','Holly','Sashimi','Tortilla']},
 Krobus:{birthday:{season:'Winter',day:1},address:'The Sewers',occupation:'Shadow merchant',roommate:true,availability:'Available after you unlock the Sewers.',loves:['Diamond','Iridium Bar','Monster Compendium','Monster Musk','Pumpkin','Void Egg','Void Mayonnaise','Wild Horseradish'],likes:['Gold Bar','Quartz','Seafoam Pudding','Strange Bun'],neutrals:[],dislikes:['All Cooking (except Bread, Fried Egg, Seafoam Pudding & Strange Bun)','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Holly','Leek','Life Elixir','Magma Cap','Morel','Purple Mushroom','Salmonberry','Snow Yam','Winter Root'],hates:[]},
 Leah:{birthday:{season:'Winter',day:23},address:"Leah's Cottage",occupation:'Artist',marriageable:true,loves:['Goat Cheese','Poppyseed Muffin','Salad','Stir Fry','Truffle','Vegetable Medley','Wine'],likes:['Chanterelle','Daffodil','Dandelion','Driftwood','Spring Onion'],neutrals:[],dislikes:['All Foraged Minerals (except Earth Crystal)','All Gems (except Diamond & Prismatic Shard)','Carp Surprise','Cookie','Fried Egg','Ice Cream','Pink Cake','Rice Pudding','Seaweed','Survival Burger','Tortilla'],hates:['Bread','Hashbrowns','Pancakes','Pizza','Void Egg']},
 Leo:{birthday:{season:'Summer',day:26},address:'Ginger Island',occupation:'Islander',availability:'Met on Ginger Island. At 6 hearts, his home base can move to the Valley.',loves:['Duck Feather','Mango','Ostrich Egg','Parrot Egg','Poi'],likes:['Dragon Tooth','Mango Sticky Rice','Nautilus Shell','Quartz','Sea Urchin','Spice Berry'],neutrals:['All Eggs (except Ostrich Egg & Void Egg)','All Fish (except Carp & Snail)','All Fruit (except Fruit Tree Fruit, Mango, Salmonberry & Spice Berry)','Coffee'],dislikes:['All Cooking (except Bread, Fried Egg, Mango Sticky Rice, Poi & Triple Shot Espresso)','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Leek','Life Elixir','Magma Cap','Pickles','Purple Mushroom','Salmonberry','Snow Yam','Wild Horseradish','Winter Root'],hates:['Beer','Holly','Hops','Mead','Morel','Oil','Pale Ale','Piña Colada','Triple Shot Espresso','Unmilled Rice','Wine']},
 Lewis:{birthday:{season:'Spring',day:7},address:"Mayor's Manor",occupation:'Mayor',loves:["Autumn's Bounty",'Glazed Yams','Green Tea','Hot Pepper','Vegetable Medley'],likes:['Blueberry','Cactus Fruit','Coconut'],neutrals:['All Eggs (except Void Egg)','All Fruit (except Blueberry, Cactus Fruit, Coconut, Fruit Tree Fruit, Hot Pepper & Salmonberry)','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Leek','Magma Cap','Morel','Purple Mushroom','Snow Yam','Winter Root'],dislikes:['All Milk','Salmonberry','Wild Horseradish'],hates:['Holly','Quartz']},
 Linus:{birthday:{season:'Winter',day:3},address:'Mountain Tent',occupation:'Hermit',loves:['Blueberry Tart','Cactus Fruit','Coconut',"Dish O' The Sea",'The Alleyway Buffet','Yam'],likes:['Spring Onion'],neutrals:['All Fish (except Snail)','Carp','Wild Bait'],dislikes:['All Foraged Minerals','All Gems (except Diamond & Prismatic Shard)','Treasure Chest'],hates:[]},
 Marnie:{birthday:{season:'Fall',day:18},address:"Marnie's Ranch",occupation:'Rancher',loves:['Diamond',"Farmer's Lunch",'Pink Cake','Pumpkin Pie'],likes:['Quartz','Stardew Valley Almanac'],neutrals:['Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Leek','Magma Cap','Morel','Purple Mushroom','Snow Yam','Winter Root'],dislikes:['Salmonberry','Seaweed','Wild Horseradish'],hates:['Clay','Holly']},
 Maru:{birthday:{season:'Summer',day:10},address:'24 Mountain Road',occupation:'Nurse and inventor',marriageable:true,loves:['Battery Pack','Cauliflower','Cheese Cauliflower','Diamond','Dwarf Gadget','Gold Bar','Iridium Bar',"Miner's Treat",'Pepper Poppers','Radioactive Bar','Rhubarb Pie','Strawberry'],likes:['Chanterelle','Copper Bar','Iron Bar','Magma Cap','Morel','Oak Resin','Pine Tar','Purple Mushroom','Quartz','Radioactive Ore'],neutrals:['All Eggs (except Void Egg)','All Fruit (except Blackberry, Crystal Fruit, Fruit Tree Fruit, Salmonberry & Strawberry)','All Milk','Daffodil','Dandelion','Ginger','Hazelnut','Leek','Wild Horseradish','Winter Root'],dislikes:['Blackberry','Common Mushroom','Crystal Fruit','Maple Syrup','Salmonberry'],hates:['Holly','Honey','Pickles','Snow Yam','Truffle']},
 Pam:{birthday:{season:'Spring',day:18},address:'Trailer',occupation:'Bus driver',availability:'Resumes bus-driving duties after the Bus is repaired.',loves:['Beer','Cactus Fruit','Glazed Yams','Mead','Pale Ale','Parsnip','Parsnip Soup','Piña Colada'],likes:['Daffodil'],neutrals:['All Fish (except Carp, Octopus, Snail & Squid)','Chanterelle','Common Mushroom','Dandelion','Ginger','Hazelnut','Joja Cola','Leek','Magma Cap','Morel','Purple Mushroom','Snow Yam','Winter Root'],dislikes:['All Eggs','Quartz','Wild Horseradish'],hates:['Holly','Octopus','Squid']},
 Penny:{birthday:{season:'Fall',day:2},address:'Trailer',occupation:'Tutor',marriageable:true,loves:['All Books','Diamond','Emerald','Melon','Poppy','Poppyseed Muffin','Price Catalogue','Red Plate','Roots Platter','Sandfish','Tom Kha Soup'],likes:['All Artifacts','Dandelion','Leek'],neutrals:['All Eggs (except Void Egg)','All Fruit (except Fruit Tree Fruit, Grape, Melon & Salmonberry)','Chanterelle','Common Mushroom','Daffodil','Ginger','Hazelnut','Magma Cap','Morel','Snow Yam','Wild Horseradish','Winter Root'],dislikes:['Algae Soup','Duck Feather','Pale Broth','Purple Mushroom','Quartz','Red Mushroom','Salmonberry','Wool'],hates:['Beer','Grape','Holly','Hops','Mead','Pale Ale','Piña Colada',"Rabbit's Foot",'Wine']},
 Pierre:{birthday:{season:'Spring',day:26},address:"Pierre's General Store",occupation:'General store owner',loves:['Fried Calamari','Price Catalogue','Stardrop Tea'],likes:['Daffodil','Dandelion'],neutrals:['All Fruit (except Fruit Tree Fruit & Salmonberry)'],dislikes:['All Foraged Minerals','All Gems (except Diamond & Prismatic Shard)','Chanterelle','Common Mushroom','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Purple Mushroom','Salmonberry','Snow Yam','Wild Horseradish','Winter Root'],hates:['All Fish','Corn','Garlic','Parsnip Soup','Tortilla']},
 Robin:{birthday:{season:'Fall',day:21},address:'24 Mountain Road',occupation:'Carpenter',loves:['Goat Cheese','Peach','Spaghetti',"Woody's Secret"],likes:['Hardwood','Quartz',"Woodcutter's Weekly"],neutrals:['All Eggs (except Void Egg)','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Leek','Magma Cap','Morel','Purple Mushroom','Snow Yam','Winter Root'],dislikes:['Wild Horseradish'],hates:['Holly']},
 Sam:{birthday:{season:'Summer',day:17},address:'1 Willow Lane',occupation:'Musician',marriageable:true,loves:['Cactus Fruit','Maple Bar','Pizza','Tigerseye'],likes:['Joja Cola'],neutrals:['All Fruit (except Cactus Fruit, Fruit Tree Fruit & Salmonberry)','All Milk'],dislikes:['All Vegetables (except Hops, Tea Leaves & Wheat)','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Purple Mushroom','Quartz','Salmonberry','Seaweed','Snow Yam','Wild Horseradish','Winter Root'],hates:['Bone Fragment','Cinder Shard','Coal','Copper Bar','Duck Mayonnaise','Gold Bar','Gold Ore','Iridium Bar','Iridium Ore','Iron Bar','Mayonnaise','Pickles','Refined Quartz']},
 Sandy:{birthday:{season:'Fall',day:15},address:'Oasis',occupation:'Desert shopkeeper',availability:'Available after the Bus to the Calico Desert is repaired.',loves:['Crocus','Daffodil','Mango Sticky Rice','Sweet Pea'],likes:['Quartz','Wool'],neutrals:[],dislikes:[],hates:['Holly']},
 Sebastian:{birthday:{season:'Winter',day:10},address:'24 Mountain Road',occupation:'Freelance programmer',marriageable:true,loves:['Frog Egg','Frozen Tear','Obsidian','Pumpkin Soup','Sashimi','Void Egg'],likes:['Combat Quarterly','Flounder','Monster Compendium','Quartz'],neutrals:['All Fish (except Carp, Flounder & Snail)','All Fruit (except Fruit Tree Fruit & Salmonberry)','All Milk','Jack Be Nimble, Jack Be Thick'],dislikes:['All Flowers (except Poppy)','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Purple Mushroom','Salmonberry','Snow Yam','Wild Horseradish','Winter Root'],hates:['All Artisan Goods (except Coffee, Green Tea & Oil)','All Eggs (except Void Egg)','Clay','Complete Breakfast',"Farmer's Lunch",'Omelet','Piña Colada']},
 Shane:{birthday:{season:'Spring',day:20},address:"Marnie's Ranch",occupation:'JojaMart employee',marriageable:true,loves:['Beer','Hot Pepper','Pepper Poppers','Pizza'],likes:[],neutrals:['All Milk','Strange Bun'],dislikes:['Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Purple Mushroom','Seaweed','Snow Yam','Wild Horseradish','Winter Root'],hates:['Pickles','Quartz']},
 Vincent:{birthday:{season:'Spring',day:10},address:'1 Willow Lane',occupation:'Child',loves:['Cranberry Candy','Frog Egg','Ginger Ale','Grape','Pink Cake','Snail'],likes:['Coconut','Daffodil'],neutrals:[],dislikes:['All Eggs','All Fruit (except Coconut, Grape & Fruit Tree Fruit)','All Vegetables (except Hops, Tea Leaves & Wheat)','Chanterelle','Common Mushroom','Dandelion','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Purple Mushroom','Quartz','Snow Yam','Winter Root'],hates:['All Artisan Goods (except Honey, Jelly & Oil)','Beer','Clay','Coffee','Mead','Pale Ale','Piña Colada','Triple Shot Espresso','Wild Horseradish','Wine']},
 Willy:{birthday:{season:'Summer',day:24},address:'Beach',occupation:'Fisher and shopkeeper',loves:['Catfish','Diamond','Gold Bar','Iridium Bar','Jewels of the Sea','Mead','Octopus','Pumpkin','Sea Cucumber','Sturgeon',"The Art O' Crabbing"],likes:['Bait And Bobber','Coffee','Lingcod','Quartz','Seafoam Pudding','Tiger Trout'],neutrals:['All Eggs (except Void Egg)','All Fish (except Carp, Catfish, Lingcod, Octopus, Sea Cucumber, Snail, Sturgeon & Tiger Trout)','All Fruit (except Fruit Tree Fruit & Salmonberry)','All Milk',"Dish O' The Sea",'Maki Roll','Mutant Carp','Sashimi'],dislikes:['Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Holly','Leek','Life Elixir','Magma Cap','Morel','Most Cooking (except fish dishes he likes or is neutral toward)','Purple Mushroom','Salmonberry','Snow Yam','Wild Horseradish','Winter Root'],hates:[]},
 Wizard:{birthday:{season:'Winter',day:17},address:"Wizard's Tower",occupation:'Wizard',loves:['Book of Mysteries','Purple Mushroom','Solar Essence','Super Cucumber','Void Essence'],likes:['All Geode Minerals','All Trinkets','Iridium Bar','Quartz'],neutrals:['All Fruit (except Fruit Tree Fruit & Salmonberry)'],dislikes:['All Eggs','All Milk','Chanterelle','Common Mushroom','Daffodil','Dandelion','Ginger','Hazelnut','Holly','Leek','Magma Cap','Morel','Salmonberry','Slime','Snow Yam','Wild Horseradish','Winter Root'],hates:[]}
};

export const giftTasteLabels:Record<GiftTaste,{label:string;points:string}>={
 loves:{label:'Loved',points:'+80 friendship'},likes:{label:'Liked',points:'+45'},neutrals:{label:'Neutral',points:'+20'},dislikes:{label:'Disliked',points:'-20'},hates:{label:'Hated',points:'-40'}
};

const exactSpriteAliases:Record<string,string>={
 'Diamond':'Aquamarine','Emerald':'Aquamarine','Jade':'Aquamarine','Ruby':'Aquamarine','Topaz':'Aquamarine','Amethyst':'Aquamarine',
 'Iridium Bar':'Gold Bar','Radioactive Bar':'Gold Bar','Radioactive Ore':'Gold Bar','Gold Ore':'Gold Bar','Iridium Ore':'Gold Bar','Refined Quartz':'Quartz',
 'Coffee':'Wine','Beer':'Wine','Mead':'Wine','Pale Ale':'Wine','Green Tea':'Wine','Piña Colada':'Wine',
 'Void Egg':'Duck Egg','Ostrich Egg':'Large Egg','Parrot Egg':'Duck Egg','Dinosaur Egg':'Large Egg','Frog Egg':'Duck Egg',
 'Mayonnaise':'Cheese','Duck Mayonnaise':'Cheese','Void Mayonnaise':'Cheese','Pickles':'Jelly','Oil':'Truffle Oil',
 'Mango':'Peach','Banana':'Apple','Salmonberry':'Blackberry','Spring Onion':'Leek','Ginger':'Wild Horseradish','Holly':'Crocus',
 'Sea Cucumber':'Sea Urchin','Super Cucumber':'Sea Urchin','Octopus':'Lobster','Squid':'Lobster','Lingcod':'Tiger Trout','Flounder':'Tilapia',
 'Clay':'Stone','Coal':'Stone','Copper Ore':'Copper Bar','Iron Ore':'Iron Bar','Woodcutter\'s Weekly':'Calendar','Mining Monthly':'Calendar','Combat Quarterly':'Calendar','Monster Compendium':'Calendar','Book of Mysteries':'Calendar','Stardew Valley Almanac':'Calendar','Price Catalogue':'Calendar','Jack Be Nimble, Jack Be Thick':'Calendar',
 'Chocolate Cake':'Fried Egg','Pink Cake':'Fried Egg','Complete Breakfast':'Fried Egg','Salmon Dinner':'Maki Roll','Banana Pudding':'Fried Egg','Blackberry Cobbler':'Fried Egg','Spicy Eel':'Eel','Crab Cakes':'Crab','Tom Kha Soup':'Fried Egg','Survival Burger':'Fried Egg','Fish Taco':'Maki Roll','Tropical Curry':'Fried Egg','Stuffing':'Fried Egg','Fried Mushroom':'Common Mushroom','Escargot':'Snail','Blueberry Tart':'Blueberry','Cookie':'Fried Egg','Cranberry Sauce':'Cranberries','Glazed Yams':'Yam','Pancakes':'Fried Egg','Rhubarb Pie':'Fried Egg','Rice Pudding':'Fried Egg','Fairy Rose':'Poppy','Tulip':'Poppy','Coleslaw':'Fried Egg','Plum Pudding':'Fried Egg','Crispy Bass':'Largemouth Bass','Eggplant Parmesan':'Eggplant','Vegetable Medley':'Parsnip','Fiddlehead Risotto':'Fiddlehead Fern','Roasted Hazelnuts':'Hazelnut','Poppyseed Muffin':'Poppy','Salad':'Parsnip','Stir Fry':'Parsnip','Poi':'Fried Egg','Mango Sticky Rice':'Fried Egg','Autumn\'s Bounty':'Pumpkin','Dish O\' The Sea':'Maki Roll','Farmer\'s Lunch':'Fried Egg','Pumpkin Pie':'Pumpkin','Cheese Cauliflower':'Cauliflower','Miner\'s Treat':'Fried Egg','Pepper Poppers':'Hot Pepper','Parsnip Soup':'Parsnip','Red Plate':'Red Cabbage','Roots Platter':'Winter Root','Fried Calamari':'Maki Roll','Spaghetti':'Fried Egg','Maple Bar':'Maple Syrup','Pizza':'Fried Egg','Pumpkin Soup':'Pumpkin','Sashimi':'Maki Roll','Cranberry Candy':'Cranberries','Ginger Ale':'Wild Horseradish','Algae Soup':'Fried Egg','Pale Broth':'Fried Egg','Tortilla':'Fried Egg',
 'Basilisk Paw':'Slime','Bone Flute':'Earth Crystal','Chanterelle':'Common Mushroom','Magma Cap':'Common Mushroom','Field Snack':'Hazelnut','Summer Spangle':'Poppy','Tea Leaves':'Green Bean','Amaranth':'Bok Choy','Artichoke Dip':'Fried Egg','Bean Hotpot':'Fried Egg','Ice Cream':'Fried Egg','Lava Eel':'Eel','All Artifacts':'Earth Crystal','Squid Ink':'Caviar','Fried Eel':'Eel','Beet':'Parsnip','Raisins':'Grape','Broken Glasses':'Quartz','Garlic':'Parsnip','Hashbrowns':'Fried Egg','Ancient Doll':'Prismatic Shard','Fairy Box':'Prismatic Shard','Strange Doll (green)':'Prismatic Shard','Strange Doll (yellow)':'Prismatic Shard','Triple Shot Espresso':'Wine','Monster Musk':'Slime','Carp Surprise':'Carp','Seaweed':'Green Bean','Dragon Tooth':'Fire Quartz','Hops':'Wheat','Unmilled Rice':'Wheat','Treasure Chest':'Gold','Joja Cola':'Wine','Bone Fragment':'Stone','Cinder Shard':'Fire Quartz','Omelet':'Fried Egg','Mutant Carp':'Carp','All Trinkets':"Rabbit's Foot",'Jack-O-Lantern':'Pumpkin','Rice':'Wheat','Tea Set':'Wine','Vinegar':'Wine','Wheat Flour':'Wheat','All Fossils':'Stone','Artifact Trove':'Frozen Geode','Blue Grass Starter':'Hay','Bug Steak':'Slime','Butterfly Powder':'Crocus','Crab Pot':'Crab','Drum Block':'Wood','Energy Tonic':'Wine','Explosive Ammo':'Fire Quartz','Fairy Dust':'Prismatic Shard','Flute Block':'Wood','Golden Bobber':'Gold','Golden Coconut':'Coconut','Golden Mystery Box':'Gold','Golden Tag':'Gold','Grass Starter':'Hay','Green Algae':'Green Bean','Journal Scrap':'Calendar','Muscle Remedy':'Wine','Mystery Box':'Gold','Oil of Garlic':'Wine','Qi Seasoning':'Prismatic Shard','Rain Totem':'Wood','Sap':'Maple Syrup','Secret Note':'Calendar','Tent Kit':'Wood','Torch':'Fire Quartz','White Algae':'Cauliflower',
 'Wool':'Wool','Cloth':'Cloth','Battery Pack':'Iron Bar','Dwarf Gadget':'Iron Bar','Tigerseye':'Aquamarine','Obsidian':'Quartz','Lemon Stone':'Quartz','Omni Geode':'Frozen Geode','Ancient Sword':'Pickaxe','Woody\'s Secret':'Calendar','The Alleyway Buffet':'Calendar','Jewels of the Sea':'Calendar','The Art O\' Crabbing':'Calendar','Bait And Bobber':'Calendar','Dwarvish Safety Manual':'Calendar','Golden Pumpkin':'Pumpkin','Magic Rock Candy':'Crystal Fruit','Pearl':'Aquamarine','Stardrop Tea':'Wine','Rainbow Shell':'Nautilus Shell','Life Elixir':'Wine','Mystic Syrup':'Maple Syrup','Roe':'Caviar','Sweet Gem Berry':'Ancient Fruit','Bread':'Fried Egg','Coral':'Sea Urchin','Sugar':'Fried Egg','Seafoam Pudding':'Fried Egg','Strange Bun':'Fried Egg','Hay':'Hay'
};

const groupSpriteRules:[RegExp,string][]=[
 [/egg/i,'Large Egg'],[/milk/i,'Large Milk'],[/fish|bait|tackle/i,'Catfish'],[/fruit/i,'Apple'],[/vegetable|seed|fertilizer/i,'Parsnip'],[/flower/i,'Poppy'],[/gem|geode|mineral/i,'Aquamarine'],[/mushroom/i,'Common Mushroom'],[/artisan/i,'Cheese'],[/cook|dish|breakfast|dinner|soup|meal/i,'Fried Egg'],[/book/i,'Calendar'],[/building material|fence|floor|path|wood/i,'Wood'],[/metal|ore|bar/i,'Iron Bar'],[/artifact|fossil|trinket/i,'Bundle Green'],[/monster loot|slime/i,'Slime'],[/trash/i,'Stone'],[/sprinkler/i,'Quality Sprinkler'],[/bomb|firework/i,'Fire Quartz'],[/warp totem/i,'Traveling Cart Icon']
];

export function giftSpriteName(name:string,available:Set<string>){
 const clean=name.replace(/^All /,'').replace(/ \(.+\)$/,'').trim();
 if(available.has(name))return name;
 if(available.has(clean))return clean;
 const alias=exactSpriteAliases[name]??exactSpriteAliases[clean];
 if(alias&&available.has(alias))return alias;
 const group=groupSpriteRules.find(([pattern])=>pattern.test(name));
 return group?.[1]&&available.has(group[1])?group[1]:'Bundle Green';
}
